In [70]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.13/dist-packages (5.0.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from optuna) (1.20.0)
Requirement already satisfied: colorlog in /usr/local/lib/python3.13/dist-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from optuna) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from optuna) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from optuna) (2.0.54)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.13/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.3.2.dev0)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.13/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.6)

In [71]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [72]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [73]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [74]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [75]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-10-02 10:07:02,088] A new study created in memory with name: no-name-791715a2-7b20-42f8-b045-b976b189060b
[I 2026-10-02 10:07:02,713] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 147, 'max_depth': 20}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-10-02 10:07:03,212] Trial 1 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 134, 'max_depth': 4}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-10-02 10:07:03,985] Trial 2 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 175, 'max_depth': 4}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-10-02 10:07:04,523] Trial 3 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 103, 'max_depth': 17}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-10-02 10:07:05,302] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 187, 'max_depth': 18}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-10-02 10:07:07,032] Trial 5 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 182, 'max_depth': 19}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-10-02 10:07:08,115] Trial 6 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 118, 'max_depth': 10}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-10-02 10:07:09,853] Trial 7 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 191, 'max_depth': 14}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-10-02 10:07:11,071] Trial 8 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 113, 'max_depth': 11}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-10-02 10:07:12,298] Trial 9 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 88, 'max_depth': 14}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-10-02 10:07:13,201] Trial 10 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 54, 'max_depth': 20}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-10-02 10:07:14,148] Trial 11 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 53, 'max_depth': 19}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-10-02 10:07:14,880] Trial 12 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 66, 'max_depth': 15}. Best is trial 3 with value: 0.7746741154562384.
[I 2026-10-02 10:07:15,703] Trial 13 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 90, 'max_depth': 20}. Best is trial 13 with value: 0.7765363128491621.
[I 2026-10-02 10:07:16,574] Trial 14 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 99, 'max_depth': 18}. Best is trial 13 with value: 0.7765363128491621.
[I 2026-10-02 10:07:17,677] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 147, 'max_depth': 17}. Best is trial 13 with value: 0.7765363128491621.
[I 2026-10-02 10:07:18,306] Trial 16 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 72, 'max_depth': 17}. Best is trial 16 with value: 0.7783985102420856.
[I 2026-10-02 10:07:19,133] Trial 17 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 86, 'max_depth': 20}. Best is trial 16 with value: 0.7783985102420856.
[I 2026-10-02 10:07:19,739] Trial 18 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 67, 'max_depth': 11}. Best is trial 16 with value: 0.7783985102420856.
[I 2026-10-02 10:07:20,737] Trial 19 finished with value: 0.7858472998137803 and parameters: {'n_estimators': 121, 'max_depth': 15}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:21,550] Trial 20 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 142, 'max_depth': 14}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:22,036] Trial 21 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 120, 'max_depth': 15}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:22,733] Trial 22 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 169, 'max_depth': 15}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:23,210] Trial 23 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 117, 'max_depth': 15}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:23,703] Trial 24 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 119, 'max_depth': 14}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:24,524] Trial 25 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 147, 'max_depth': 8}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:25,264] Trial 26 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 129, 'max_depth': 20}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:25,816] Trial 27 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 140, 'max_depth': 11}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:26,358] Trial 28 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 135, 'max_depth': 16}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:26,564] Trial 29 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 51, 'max_depth': 8}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:27,061] Trial 30 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 122, 'max_depth': 16}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:27,448] Trial 31 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 96, 'max_depth': 14}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:28,116] Trial 32 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 164, 'max_depth': 18}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:28,392] Trial 33 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 67, 'max_depth': 17}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:28,857] Trial 34 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 112, 'max_depth': 19}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:29,270] Trial 35 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 101, 'max_depth': 12}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:29,617] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 87, 'max_depth': 12}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:30,241] Trial 37 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 155, 'max_depth': 12}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:30,667] Trial 38 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 106, 'max_depth': 15}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:31,394] Trial 39 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 181, 'max_depth': 11}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:31,919] Trial 40 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 129, 'max_depth': 12}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:32,696] Trial 41 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 200, 'max_depth': 8}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:32,972] Trial 42 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 68, 'max_depth': 5}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:33,366] Trial 43 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 96, 'max_depth': 16}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:33,876] Trial 44 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 126, 'max_depth': 18}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:34,323] Trial 45 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 110, 'max_depth': 16}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:34,749] Trial 46 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 108, 'max_depth': 15}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:35,334] Trial 47 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 127, 'max_depth': 14}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:35,682] Trial 48 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 60, 'max_depth': 18}. Best is trial 19 with value: 0.7858472998137803.
[I 2026-10-02 10:07:36,157] Trial 49 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 78, 'max_depth': 18}. Best is trial 19 with value: 0.7858472998137803.

In [76]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7858472998137803
Best hyperparameters: {'n_estimators': 121, 'max_depth': 15}

In [77]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

## Samplers in Optuna

In [78]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [79]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-10-02 10:07:36,468] A new study created in memory with name: no-name-1ecdf63c-5d9c-4274-8273-c05338af48b3
[I 2026-10-02 10:07:37,300] Trial 0 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 188, 'max_depth': 15}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-10-02 10:07:38,130] Trial 1 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 176, 'max_depth': 20}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-10-02 10:07:38,742] Trial 2 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 124, 'max_depth': 18}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:39,767] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 190, 'max_depth': 15}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:40,436] Trial 4 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 68, 'max_depth': 3}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:41,489] Trial 5 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 120, 'max_depth': 4}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:42,997] Trial 6 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 172, 'max_depth': 15}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:44,325] Trial 7 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 143, 'max_depth': 13}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:45,293] Trial 8 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 84, 'max_depth': 16}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:46,150] Trial 9 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 90, 'max_depth': 10}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:48,138] Trial 10 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 130, 'max_depth': 9}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:49,307] Trial 11 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 105, 'max_depth': 12}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:50,348] Trial 12 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 117, 'max_depth': 6}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:50,831] Trial 13 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 60, 'max_depth': 12}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:51,728] Trial 14 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 103, 'max_depth': 12}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:52,663] Trial 15 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 103, 'max_depth': 14}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:53,588] Trial 16 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 103, 'max_depth': 14}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:54,778] Trial 17 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 117, 'max_depth': 7}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:55,558] Trial 18 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 111, 'max_depth': 19}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:56,142] Trial 19 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 166, 'max_depth': 3}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:56,807] Trial 20 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 168, 'max_depth': 18}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:57,106] Trial 21 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 72, 'max_depth': 15}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:57,494] Trial 22 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 96, 'max_depth': 12}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:57,970] Trial 23 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 117, 'max_depth': 15}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:58,584] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 145, 'max_depth': 11}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:59,472] Trial 25 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 156, 'max_depth': 10}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:07:59,927] Trial 26 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 76, 'max_depth': 19}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:00,152] Trial 27 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 56, 'max_depth': 6}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:00,417] Trial 28 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 65, 'max_depth': 13}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:00,966] Trial 29 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 138, 'max_depth': 19}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:01,510] Trial 30 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 140, 'max_depth': 8}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:02,058] Trial 31 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 138, 'max_depth': 17}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:02,437] Trial 32 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 106, 'max_depth': 3}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:02,720] Trial 33 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 70, 'max_depth': 17}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:03,180] Trial 34 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 114, 'max_depth': 9}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:03,848] Trial 35 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 188, 'max_depth': 4}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:04,376] Trial 36 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 128, 'max_depth': 14}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:05,166] Trial 37 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 199, 'max_depth': 15}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:05,948] Trial 38 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 199, 'max_depth': 13}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:06,509] Trial 39 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 85, 'max_depth': 9}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:07,100] Trial 40 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 117, 'max_depth': 7}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:07,758] Trial 41 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 187, 'max_depth': 3}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:08,169] Trial 42 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 98, 'max_depth': 14}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:08,814] Trial 43 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 163, 'max_depth': 17}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:09,273] Trial 44 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 113, 'max_depth': 8}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:09,649] Trial 45 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 101, 'max_depth': 5}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:10,131] Trial 46 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 94, 'max_depth': 17}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:10,753] Trial 47 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 113, 'max_depth': 7}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:11,222] Trial 48 finished with value: 0.756052141527002 and parameters: {'n_estimators': 84, 'max_depth': 3}. Best is trial 2 with value: 0.7821229050279329.
[I 2026-10-02 10:08:12,055] Trial 49 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 198, 'max_depth': 17}. Best is trial 2 with value: 0.7821229050279329.

In [80]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279329
Best hyperparameters: {'n_estimators': 124, 'max_depth': 18}

In [81]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

In [82]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [83]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-10-02 10:08:12,274] A new study created in memory with name: no-name-637979fe-cc1d-46c1-9231-76949d9b7a10
[I 2026-10-02 10:08:12,666] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-10-02 10:08:13,272] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-10-02 10:08:13,496] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-10-02 10:08:13,898] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-10-02 10:08:14,312] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-10-02 10:08:14,534] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-10-02 10:08:15,086] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-10-02 10:08:15,690] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-10-02 10:08:16,289] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-10-02 10:08:17,094] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-10-02 10:08:17,887] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-10-02 10:08:18,692] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-10-02 10:08:19,419] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-10-02 10:08:19,620] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-10-02 10:08:20,024] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-10-02 10:08:20,237] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [84]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [85]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Optuna Visualizations

In [86]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [87]:
# 1. Optimization History
plot_optimization_history(study).show()

In [88]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [89]:
# 3. Slice Plot
plot_slice(study).show()

In [90]:
# 4. Contour Plot
plot_contour(study).show()

In [91]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

## Optimizing Multiple ML Models

In [92]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [93]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [94]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-10-02 10:08:20,430] A new study created in memory with name: no-name-f32cdddf-f503-4a51-9277-7be9d3cff156
[I 2026-10-02 10:08:20,451] Trial 0 finished with value: 0.7132216014897579 and parameters: {'classifier': 'SVM', 'C': 0.14287233907892002, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 0 with value: 0.7132216014897579.
[I 2026-10-02 10:08:22,875] Trial 1 finished with value: 0.7318435754189944 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 115, 'learning_rate': 0.03401688442413065, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.7318435754189944.
[I 2026-10-02 10:08:24,588] Trial 2 finished with value: 0.7169459962756052 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 108, 'learning_rate': 0.0305395340241417, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.7318435754189944.
[I 2026-10-02 10:08:26,296] Trial 3 finished with value: 0.7430167597765363 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 293, 'learning_rate': 0.2957289627454721, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 3 with value: 0.7430167597765363.
[I 2026-10-02 10:08:26,363] Trial 4 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 17.18053256257204, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:27,193] Trial 5 finished with value: 0.7690875232774674 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 89, 'learning_rate': 0.019467908540720388, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 7}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:27,718] Trial 6 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 147, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:29,365] Trial 7 finished with value: 0.7355679702048418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 147, 'learning_rate': 0.10760643216988798, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:29,391] Trial 8 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 8.89202735372411, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:29,428] Trial 9 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 5.994565480815468, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:30,335] Trial 10 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 286, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:30,399] Trial 11 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 15.612152024043189, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:30,438] Trial 12 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 6.229262790384308, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:30,667] Trial 13 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 94.29188636858619, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:30,692] Trial 14 finished with value: 0.7430167597765364 and parameters: {'classifier': 'SVM', 'C': 1.208988930499349, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:30,723] Trial 15 finished with value: 0.7299813780260708 and parameters: {'classifier': 'SVM', 'C': 37.990970740215516, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:30,749] Trial 16 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.4084493301956016, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:31,600] Trial 17 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 222, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:31,625] Trial 18 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.9848891204777204, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:31,657] Trial 19 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 32.24772820341935, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:31,830] Trial 20 finished with value: 0.7728119180633146 and parameters: {'classifier': 'RandomForest', 'n_estimators': 50, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:31,882] Trial 21 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 11.815493279766935, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:31,971] Trial 22 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 21.627739972093988, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:32,007] Trial 23 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 5.190297882862713, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:32,032] Trial 24 finished with value: 0.6927374301675977 and parameters: {'classifier': 'SVM', 'C': 16.27817452499471, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:32,242] Trial 25 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 72.75163796365997, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:32,277] Trial 26 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.047248694544395, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 4 with value: 0.7858472998137801.
[I 2026-10-02 10:08:32,299] Trial 27 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7328216554450425, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 27 with value: 0.7858472998137803.
[I 2026-10-02 10:08:33,025] Trial 28 finished with value: 0.7802607076350094 and parameters: {'classifier': 'RandomForest', 'n_estimators': 217, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 27 with value: 0.7858472998137803.
[I 2026-10-02 10:08:33,064] Trial 29 finished with value: 0.7411545623836125 and parameters: {'classifier': 'SVM', 'C': 0.5682741657075253, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 27 with value: 0.7858472998137803.
[I 2026-10-02 10:08:33,109] Trial 30 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.45609690098183325, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 27 with value: 0.7858472998137803.
[I 2026-10-02 10:08:33,141] Trial 31 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11288928027838552, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:33,174] Trial 32 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10709792113917257, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:33,206] Trial 33 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1045270131606128, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:35,481] Trial 34 finished with value: 0.7616387337057727 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 223, 'learning_rate': 0.011474990324118762, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 8}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:35,501] Trial 35 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10894444067028676, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:37,943] Trial 36 finished with value: 0.702048417132216 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 193, 'learning_rate': 0.09616793656353065, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:37,964] Trial 37 finished with value: 0.7039106145251397 and parameters: {'classifier': 'SVM', 'C': 0.10115196255033337, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:37,984] Trial 38 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21601866641660614, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:38,739] Trial 39 finished with value: 0.74487895716946 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 54, 'learning_rate': 0.1129382631168373, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:38,760] Trial 40 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.243949333804632, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:38,779] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10060893120320617, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:38,798] Trial 42 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10517218736265642, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:38,817] Trial 43 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23506779261702715, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:38,837] Trial 44 finished with value: 0.7169459962756052 and parameters: {'classifier': 'SVM', 'C': 0.16784956537068194, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:39,774] Trial 45 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 256, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:39,795] Trial 46 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.3599589548005995, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:41,156] Trial 47 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 171, 'learning_rate': 0.28104271984008194, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:41,178] Trial 48 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14124154288021096, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:41,198] Trial 49 finished with value: 0.7169459962756052 and parameters: {'classifier': 'SVM', 'C': 0.15805234974848853, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:41,223] Trial 50 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3061356710114603, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:41,251] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12048752959695233, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:41,275] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.152860426164127, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:41,297] Trial 53 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16464288807096136, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:41,319] Trial 54 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15920864729545017, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:41,342] Trial 55 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2607516525636621, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:42,256] Trial 56 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 260, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:42,283] Trial 57 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15319703996893216, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:42,312] Trial 58 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.20380154840447762, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:42,337] Trial 59 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.3878963820510013, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:42,357] Trial 60 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1526618178389712, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:42,377] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13791901823577166, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:42,397] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1499322071433326, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:42,420] Trial 63 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.18445327484651391, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:42,440] Trial 64 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2901156920455145, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:42,460] Trial 65 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13433429443874711, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:42,480] Trial 66 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13907626551485547, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:42,757] Trial 67 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 80, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:42,777] Trial 68 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21215822968480957, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:44,090] Trial 69 finished with value: 0.756052141527002 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 146, 'learning_rate': 0.049956668885812565, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:44,115] Trial 70 finished with value: 0.750465549348231 and parameters: {'classifier': 'SVM', 'C': 0.13776108489419644, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:44,134] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13790530713593174, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:44,154] Trial 72 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19302276120471726, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:44,173] Trial 73 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.30571690311185035, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:44,192] Trial 74 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13492750383338065, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:44,220] Trial 75 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.18771563252857698, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:44,241] Trial 76 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13092712233778672, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:44,275] Trial 77 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7266168602257093, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:44,312] Trial 78 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.29345594075615267, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:44,354] Trial 79 finished with value: 0.7430167597765364 and parameters: {'classifier': 'SVM', 'C': 0.5036717795664498, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:44,386] Trial 80 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2387777844860733, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.
[I 2026-10-02 10:08:44,416] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1250985462473991, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 31 with value: 0.7895716945996275.

In [95]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.11288928027838552, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7895716945996275

In [96]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,system_attrs_tpe:relative_params:0,state
0,0,0.713222,2026-10-02 10:08:20.431704,2026-10-02 10:08:20.451440,0 days 00:00:00.019736,0.142872,NaN,SVM,auto,poly,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.731844,2026-10-02 10:08:20.452363,2026-10-02 10:08:22.875730,0 days 00:00:02.423367,NaN,NaN,GradientBoosting,NaN,NaN,0.034017,10.0,2.0,4.0,115.0,NaN,COMPLETE
2,2,0.716946,2026-10-02 10:08:22.876587,2026-10-02 10:08:24.588681,0 days 00:00:01.712094,NaN,NaN,GradientBoosting,NaN,NaN,0.030540,14.0,1.0,9.0,108.0,NaN,COMPLETE
3,3,0.743017,2026-10-02 10:08:24.589494,2026-10-02 10:08:26.296117,0 days 00:00:01.706623,NaN,NaN,GradientBoosting,NaN,NaN,0.295729,5.0,5.0,8.0,293.0,NaN,COMPLETE
4,4,0.785847,2026-10-02 10:08:26.296974,2026-10-02 10:08:26.363921,0 days 00:00:00.066947,17.180533,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.765363,2026-10-02 10:08:49.358342,2026-10-02 10:08:49.387315,0 days 00:00:00.028973,0.101175,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,"{""classifier"": ""SVM""}",COMPLETE
96,96,0.785847,2026-10-02 10:08:49.388014,2026-10-02 10:08:49.408505,0 days 00:00:00.020491,0.207882,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,"{""classifier"": ""SVM""}",COMPLETE
97,97,0.789572,2026-10-02 10:08:49.409270,2026-10-02 10:08:49.429420,0 days 00:00:00.020150,0.146160,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,"{""classifier"": ""SVM""}",COMPLETE
98,98,0.724395,2026-10-02 10:08:49.430108,2026-10-02 10:08:49.451097,0 days 00:00:00.020989,0.268294,NaN,SVM,auto,poly,NaN,NaN,NaN,NaN,NaN,"{""classifier"": ""SVM""}",COMPLETE
99,99,0.741155,2026-10-02 10:08:49.451790,2026-10-02 10:08:50.362625,0 days 00:00:00.910835,NaN,NaN,GradientBoosting,NaN,NaN,0.169976,7.0,9.0,9.0,132.0,"{""classifier"": ""GradientBoosting""}",COMPLETE

In [97]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 79
GradientBoosting    12
RandomForest         9
Name: count, dtype: int64

In [98]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.739292
RandomForest        0.765984
SVM                 0.775358
Name: value, dtype: float64

In [99]:
# 1. Optimization History
plot_optimization_history(study).show()

In [100]:
# 3. Slice Plot
plot_slice(study).show()

In [101]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [102]:
!pip install optuna-integration[xgboost]

Requirement already satisfied: optuna-integration[xgboost] in /usr/local/lib/python3.13/dist-packages (5.0.0)
Requirement already satisfied: optuna in /usr/local/lib/python3.13/dist-packages (from optuna-integration[xgboost]) (5.0.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (from optuna-integration[xgboost]) (3.4.1)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (1.20.0)
Requirement already satisfied: colorlog in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (6.12.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.54)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost->optuna-integration[xgboost]) (2.31.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.2.dev0)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.13/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.5.6)

In [103]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

[I 2026-10-02 10:08:54,712] A new study created in memory with name: no-name-45043a9c-c88e-4172-b863-e065c05a1411

[0]	train-mlogloss:1.00093	eval-mlogloss:0.99805
[1]	train-mlogloss:0.90937	eval-mlogloss:0.90414
[2]	train-mlogloss:0.86877	eval-mlogloss:0.87191
[3]	train-mlogloss:0.83440	eval-mlogloss:0.83640
[4]	train-mlogloss:0.76577	eval-mlogloss:0.76474
[5]	train-mlogloss:0.69586	eval-mlogloss:0.69170
[6]	train-mlogloss:0.67350	eval-mlogloss:0.66791
[7]	train-mlogloss:0.64665	eval-mlogloss:0.63703
[8]	train-mlogloss:0.59645	eval-mlogloss:0.58294
[9]	train-mlogloss:0.54703	eval-mlogloss:0.52692
[10]	train-mlogloss:0.51308	eval-mlogloss:0.48743
[11]	train-mlogloss:0.48075	eval-mlogloss:0.45249
[12]	train-mlogloss:0.45038	eval-mlogloss:0.42224
[13]	train-mlogloss:0.43107	eval-mlogloss:0.40298
[14]	train-mlogloss:0.40579	eval-mlogloss:0.37579
[15]	train-mlogloss:0.38212	eval-mlogloss:0.34921
[16]	train-mlogloss:0.36096	eval-mlogloss:0.32528
[17]	train-mlogloss:0.33420	eval-mlogloss:0.29694
[18]	train-mlogloss:0.31532	eval-mlogloss:0.27680
[19]	train-mlogloss:0.30063	eval-mlogloss:0.26013
[20]	train-mlogloss:0.29202	eval-mlogloss:0.25290
[21]	train-mlogloss:0.27877	eval-mlogloss:0.23760
[22]	train-mlogloss:0.26672	eval-mlogloss:0.22398
[23]	train-mlogloss:0.26453	eval-mlogloss:0.22124
[24]	train-mlogloss:0.25153	eval-mlogloss:0.20551
[25]	train-mlogloss:0.23887	eval-mlogloss:0.19015
[26]	train-mlogloss:0.23223	eval-mlogloss:0.18209
[27]	train-mlogloss:0.23010	eval-mlogloss:0.17954
[28]	train-mlogloss:0.22488	eval-mlogloss:0.17430
[29]	train-mlogloss:0.21909	eval-mlogloss:0.16688
[30]	train-mlogloss:0.21866	eval-mlogloss:0.16693
[31]	train-mlogloss:0.21493	eval-mlogloss:0.16193
[32]	train-mlogloss:0.21132	eval-mlogloss:0.15714
[33]	train-mlogloss:0.20934	eval-mlogloss:0.15594
[34]	train-mlogloss:0.20280	eval-mlogloss:0.14798
[35]	train-mlogloss:0.19970	eval-mlogloss:0.14503
[36]	train-mlogloss:0.19666	eval-mlogloss:0.14092
[37]	train-mlogloss:0.19648	eval-mlogloss:0.14034
[38]	train-mlogloss:0.19318	eval-mlogloss:0.13676
[39]	train-mlogloss:0.19252	eval-mlogloss:0.13636
[40]	train-mlogloss:0.19051	eval-mlogloss:0.13358
[41]	train-mlogloss:0.18996	eval-mlogloss:0.13384
[42]	train-mlogloss:0.18992	eval-mlogloss:0.13362
[43]	train-mlogloss:0.18902	eval-mlogloss:0.13375
[44]	train-mlogloss:0.18847	eval-mlogloss:0.13406
[45]	train-mlogloss:0.18602	eval-mlogloss:0.13036
[46]	train-mlogloss:0.18598	eval-mlogloss:0.13048
[47]	train-mlogloss:0.18412	eval-mlogloss:0.12747
[48]	train-mlogloss:0.18413	eval-mlogloss:0.12698
[49]	train-mlogloss:0.18346	eval-mlogloss:0.12657
[50]	train-mlogloss:0.18169	eval-mlogloss:0.12388
[51]	train-mlogloss:0.18100	eval-mlogloss:0.12383
[52]	train-mlogloss:0.17874	eval-mlogloss:0.12112
[53]	train-mlogloss:0.17737	eval-mlogloss:0.11928
[54]	train-mlogloss:0.17548	eval-mlogloss:0.11610
[55]	train-mlogloss:0.17541	eval-mlogloss:0.11534
[56]	train-mlogloss:0.17351	eval-mlogloss:0.11325
[57]	train-mlogloss:0.17333	eval-mlogloss:0.11306
[58]	train-mlogloss:0.17286	eval-mlogloss:0.11271
[59]	train-mlogloss:0.17294	eval-mlogloss:0.11281
[60]	train-mlogloss:0.17291	eval-mlogloss:0.11238
[61]	train-mlogloss:0.17285	eval-mlogloss:0.11250
[62]	train-mlogloss:0.17262	eval-mlogloss:0.11229
[63]	train-mlogloss:0.17252	eval-mlogloss:0.11238
[64]	train-mlogloss:0.17242	eval-mlogloss:0.11228
[65]	train-mlogloss:0.17243	eval-mlogloss:0.11209
[66]	train-mlogloss:0.17226	eval-mlogloss:0.11181
[67]	train-mlogloss:0.17222	eval-mlogloss:0.11156
[68]	train-mlogloss:0.17218	eval-mlogloss:0.11168
[69]	train-mlogloss:0.17212	eval-mlogloss:0.11157
[70]	train-mlogloss:0.17181	eval-mlogloss:0.11111
[71]	train-mlogloss:0.17176	eval-mlogloss:0.11127
[72]	train-mlogloss:0.17158	eval-mlogloss:0.11112
[73]	train-mlogloss:0.17141	eval-mlogloss:0.11079
[74]	train-mlogloss:0.17140	eval-mlogloss:0.11083
[75]	train-mlogloss:0.17127	eval-mlogloss:0.11068
[76]	train-mlogloss:0.17135	eval-mlogloss:0.11076
[77]	train-mlogloss:0.17116	eval-mlogloss:0.11072
[78]	train-mlogloss:0.17067	eval-mlogloss:0.11123
[79]	train-mlogloss:0.16951	eval-mlogloss:0.10931
[80]	train-mlogloss:0.16946	eval-mlogloss:0.10890
[81]	train-mlogloss:0.16943	eval-mlogloss:0.10875
[82]	train-mlogloss:0.16942	eval-mlogloss:0.10865
[83]	train-mlogloss:0.16895	eval-mlogloss:0.10804
[84]	train-mlogloss:0.16830	eval-mlogloss:0.10923
[85]	train-mlogloss:0.16820	eval-mlogloss:0.10909
[86]	train-mlogloss:0.16820	eval-mlogloss:0.10924
[87]	train-mlogloss:0.16802	eval-mlogloss:0.10895
[88]	train-mlogloss:0.16755	eval-mlogloss:0.10857
[89]	train-mlogloss:0.16753	eval-mlogloss:0.10824
[90]	train-mlogloss:0.16727	eval-mlogloss:0.10792
[91]	train-mlogloss:0.16728	eval-mlogloss:0.10763
[92]	train-mlogloss:0.16723	eval-mlogloss:0.10774
[93]	train-mlogloss:0.16696	eval-mlogloss:0.10744
[94]	train-mlogloss:0.16689	eval-mlogloss:0.10753
[95]	train-mlogloss:0.16685	eval-mlogloss:0.10769
[96]	train-mlogloss:0.16650	eval-mlogloss:0.10739
[97]	train-mlogloss:0.16652	eval-mlogloss:0.10751
[98]	train-mlogloss:0.16649	eval-mlogloss:0.10720
[99]	train-mlogloss:0.16635	eval-mlogloss:0.10756
[100]	train-mlogloss:0.16635	eval-mlogloss:0.10732
[101]	train-mlogloss:0.16637	eval-mlogloss:0.10763
[102]	train-mlogloss:0.16640	eval-mlogloss:0.10781
[103]	train-mlogloss:0.16617	eval-mlogloss:0.10786
[104]	train-mlogloss:0.16591	eval-mlogloss:0.10751
[105]	train-mlogloss:0.16589	eval-mlogloss:0.10743
[106]	train-mlogloss:0.16591	eval-mlogloss:0.10756
[107]	train-mlogloss:0.16592	eval-mlogloss:0.10782
[108]	train-mlogloss:0.16578	eval-mlogloss:0.10752
[109]	train-mlogloss:0.16555	eval-mlogloss:0.10700
[110]	train-mlogloss:0.16552	eval-mlogloss:0.10693
[111]	train-mlogloss:0.16539	eval-mlogloss:0.10695
[112]	train-mlogloss:0.16510	eval-mlogloss:0.10625
[113]	train-mlogloss:0.16445	eval-mlogloss:0.10644
[114]	train-mlogloss:0.16438	eval-mlogloss:0.10626
[115]	train-mlogloss:0.16419	eval-mlogloss:0.10608
[116]	train-mlogloss:0.16413	eval-mlogloss:0.10589
[117]	train-mlogloss:0.16413	eval-mlogloss:0.10578
[118]	train-mlogloss:0.16409	eval-mlogloss:0.10531
[119]	train-mlogloss:0.16411	eval-mlogloss:0.10526
[120]	train-mlogloss:0.16403	eval-mlogloss:0.10486
[121]	train-mlogloss:0.16402	eval-mlogloss:0.10512
[122]	train-mlogloss:0.16225	eval-mlogloss:0.10342
[123]	train-mlogloss:0.16213	eval-mlogloss:0.10303
[124]	train-mlogloss:0.16202	eval-mlogloss:0.10282
[125]	train-mlogloss:0.16192	eval-mlogloss:0.10301
[126]	train-mlogloss:0.16183	eval-mlogloss:0.10292
[127]	train-mlogloss:0.16183	eval-mlogloss:0.10294
[128]	train-mlogloss:0.16183	eval-mlogloss:0.10311
[129]	train-mlogloss:0.16171	eval-mlogloss:0.10294
[130]	train-mlogloss:0.16170	eval-mlogloss:0.10287
[131]	train-mlogloss:0.16123	eval-mlogloss:0.10241
[132]	train-mlogloss:0.16098	eval-mlogloss:0.10211
[133]	train-mlogloss:0.16089	eval-mlogloss:0.10186
[134]	train-mlogloss:0.16070	eval-mlogloss:0.10170
[135]	train-mlogloss:0.16056	eval-mlogloss:0.10160
[136]	train-mlogloss:0.16057	eval-mlogloss:0.10173
[137]	train-mlogloss:0.16055	eval-mlogloss:0.10150
[138]	train-mlogloss:0.16055	eval-mlogloss:0.10157
[139]	train-mlogloss:0.16040	eval-mlogloss:0.10149
[140]	train-mlogloss:0.16036	eval-mlogloss:0.10154
[141]	train-mlogloss:0.16036	eval-mlogloss:0.10140
[142]	train-mlogloss:0.16004	eval-mlogloss:0.10121
[143]	train-mlogloss:0.16002	eval-mlogloss:0.10097
[144]	train-mlogloss:0.16001	eval-mlogloss:0.10092
[145]	train-mlogloss:0.15997	eval-mlogloss:0.10074
[146]	train-mlogloss:0.15972	eval-mlogloss:0.10046
[147]	train-mlogloss:0.15834	eval-mlogloss:0.09892
[148]	train-mlogloss:0.15836	eval-mlogloss:0.09873
[149]	train-mlogloss:0.15833	eval-mlogloss:0.09834
[150]	train-mlogloss:0.15810	eval-mlogloss:0.09827
[151]	train-mlogloss:0.15807	eval-mlogloss:0.09789
[152]	train-mlogloss:0.15788	eval-mlogloss:0.09768
[153]	train-mlogloss:0.15786	eval-mlogloss:0.09743
[154]	train-mlogloss:0.15785	eval-mlogloss:0.09764
[155]	train-mlogloss:0.15786	eval-mlogloss:0.09766
[156]	train-mlogloss:0.15788	eval-mlogloss:0.09747
[157]	train-mlogloss:0.15790	eval-mlogloss:0.09750
[158]	train-mlogloss:0.15790	eval-mlogloss:0.09767
[159]	train-mlogloss:0.15760	eval-mlogloss:0.09736
[160]	train-mlogloss:0.15739	eval-mlogloss:0.09713
[161]	train-mlogloss:0.15736	eval-mlogloss:0.09692
[162]	train-mlogloss:0.15723	eval-mlogloss:0.09670
[163]	train-mlogloss:0.15720	eval-mlogloss:0.09675
[164]	train-mlogloss:0.15720	eval-mlogloss:0.09664
[165]	train-mlogloss:0.15719	eval-mlogloss:0.09648
[166]	train-mlogloss:0.15718	eval-mlogloss:0.09657
[167]	train-mlogloss:0.15718	eval-mlogloss:0.09651
[168]	train-mlogloss:0.15720	eval-mlogloss:0.09673
[169]	train-mlogloss:0.15716	eval-mlogloss:0.09585
[170]	train-mlogloss:0.15714	eval-mlogloss:0.09594
[171]	train-mlogloss:0.15712	eval-mlogloss:0.09584
[172]	train-mlogloss:0.15708	eval-mlogloss:0.09589
[173]	train-mlogloss:0.15708	eval-mlogloss:0.09588
[174]	train-mlogloss:0.15708	eval-mlogloss:0.09604
[175]	train-mlogloss:0.15707	eval-mlogloss:0.09571
[176]	train-mlogloss:0.15686	eval-mlogloss:0.09560
[177]	train-mlogloss:0.15686	eval-mlogloss:0.09546
[178]	train-mlogloss:0.15686	eval-mlogloss:0.09544
[179]	train-mlogloss:0.15686	eval-mlogloss:0.09548
[180]	train-mlogloss:0.15697	eval-mlogloss:0.09553
[181]	train-mlogloss:0.15700	eval-mlogloss:0.09561
[182]	train-mlogloss:0.15701	eval-mlogloss:0.09539
[183]	train-mlogloss:0.15691	eval-mlogloss:0.09527
[184]	train-mlogloss:0.15675	eval-mlogloss:0.09507
[185]	train-mlogloss:0.15670	eval-mlogloss:0.09512
[186]	train-mlogloss:0.15669	eval-mlogloss:0.09536
[187]	train-mlogloss:0.15670	eval-mlogloss:0.09522
[188]	train-mlogloss:0.15667	eval-mlogloss:0.09531
[189]	train-mlogloss:0.15670	eval-mlogloss:0.09541
[190]	train-mlogloss:0.15672	eval-mlogloss:0.09530
[191]	train-mlogloss:0.15672	eval-mlogloss:0.09527
[192]	train-mlogloss:0.15672	eval-mlogloss:0.09533
[193]	train-mlogloss:0.15671	eval-mlogloss:0.09546
[194]	train-mlogloss:0.15664	eval-mlogloss:0.09541
[195]	train-mlogloss:0.15649	eval-mlogloss:0.09537
[196]	train-mlogloss:0.15647	eval-mlogloss:0.09472
[197]	train-mlogloss:0.15642	eval-mlogloss:0.09473
[198]	train-mlogloss:0.15642	eval-mlogloss:0.09480
[199]	train-mlogloss:0.15639	eval-mlogloss:0.09494
[200]	train-mlogloss:0.15640	eval-mlogloss:0.09489
[201]	train-mlogloss:0.15640	eval-mlogloss:0.09482
[202]	train-mlogloss:0.15637	eval-mlogloss:0.09472
[203]	train-mlogloss:0.15637	eval-mlogloss:0.09476
[204]	train-mlogloss:0.15644	eval-mlogloss:0.09463
[205]	train-mlogloss:0.15635	eval-mlogloss:0.09459
[206]	train-mlogloss:0.15634	eval-mlogloss:0.09453
[207]	train-mlogloss:0.15631	eval-mlogloss:0.09456
[208]	train-mlogloss:0.15635	eval-mlogloss:0.09465
[209]	train-mlogloss:0.15634	eval-mlogloss:0.09473
[210]	train-mlogloss:0.15635	eval-mlogloss:0.09469
[211]	train-mlogloss:0.15636	eval-mlogloss:0.09501
[212]	train-mlogloss:0.15635	eval-mlogloss:0.09504
[213]	train-mlogloss:0.15582	eval-mlogloss:0.09430
[214]	train-mlogloss:0.15586	eval-mlogloss:0.09420
[215]	train-mlogloss:0.15579	eval-mlogloss:0.09398
[216]	train-mlogloss:0.15580	eval-mlogloss:0.09383
[217]	train-mlogloss:0.15576	eval-mlogloss:0.09373
[218]	train-mlogloss:0.15576	eval-mlogloss:0.09388
[219]	train-mlogloss:0.15572	eval-mlogloss:0.09400
[220]	train-mlogloss:0.15570	eval-mlogloss:0.09397
[221]	train-mlogloss:0.15569	eval-mlogloss:0.09375
[222]	train-mlogloss:0.15564	eval-mlogloss:0.09381
[223]	train-mlogloss:0.15551	eval-mlogloss:0.09356
[224]	train-mlogloss:0.15555	eval-mlogloss:0.09340
[225]	train-mlogloss:0.15554	eval-mlogloss:0.09342
[226]	train-mlogloss:0.15560	eval-mlogloss:0.09343
[227]	train-mlogloss:0.15550	eval-mlogloss:0.09362
[228]	train-mlogloss:0.15537	eval-mlogloss:0.09362
[229]	train-mlogloss:0.15537	eval-mlogloss:0.09349
[230]	train-mlogloss:0.15527	eval-mlogloss:0.09322
[231]	train-mlogloss:0.15528	eval-mlogloss:0.09348
[232]	train-mlogloss:0.15528	eval-mlogloss:0.09335
[233]	train-mlogloss:0.15527	eval-mlogloss:0.09271
[234]	train-mlogloss:0.15526	eval-mlogloss:0.09257
[235]	train-mlogloss:0.15526	eval-mlogloss:0.09270
[236]	train-mlogloss:0.15529	eval-mlogloss:0.09282
[237]	train-mlogloss:0.15529	eval-mlogloss:0.09279
[238]	train-mlogloss:0.15530	eval-mlogloss:0.09283
[239]	train-mlogloss:0.15521	eval-mlogloss:0.09296
[240]	train-mlogloss:0.15526	eval-mlogloss:0.09292
[241]	train-mlogloss:0.15524	eval-mlogloss:0.09265
[242]	train-mlogloss:0.15515	eval-mlogloss:0.09252
[243]	train-mlogloss:0.15514	eval-mlogloss:0.09263
[244]	train-mlogloss:0.15492	eval-mlogloss:0.09247
[245]	train-mlogloss:0.15482	eval-mlogloss:0.09265
[246]	train-mlogloss:0.15482	eval-mlogloss:0.09265
[247]	train-mlogloss:0.15482	eval-mlogloss:0.09261
[248]	train-mlogloss:0.15478	eval-mlogloss:0.09292
[249]	train-mlogloss:0.15470	eval-mlogloss:0.09273
[250]	train-mlogloss:0.15470	eval-mlogloss:0.09264
[251]	train-mlogloss:0.15450	eval-mlogloss:0.09231
[252]	train-mlogloss:0.15451	eval-mlogloss:0.09227
[253]	train-mlogloss:0.15453	eval-mlogloss:0.09233
[254]	train-mlogloss:0.15452	eval-mlogloss:0.09237
[255]	train-mlogloss:0.15455	eval-mlogloss:0.09245
[256]	train-mlogloss:0.15444	eval-mlogloss:0.09237
[257]	train-mlogloss:0.15433	eval-mlogloss:0.09232
[258]	train-mlogloss:0.15430	eval-mlogloss:0.09240
[259]	train-mlogloss:0.15432	eval-mlogloss:0.09243
[260]	train-mlogloss:0.15434	eval-mlogloss:0.09236
[261]	train-mlogloss:0.15432	eval-mlogloss:0.09239
[262]	train-mlogloss:0.15430	eval-mlogloss:0.09230
[263]	train-mlogloss:0.15428	eval-mlogloss:0.09238
[264]	train-mlogloss:0.15421	eval-mlogloss:0.09238
[265]	train-mlogloss:0.15420	eval-mlogloss:0.09262
[266]	train-mlogloss:0.15420	eval-mlogloss:0.09256
[267]	train-mlogloss:0.15404	eval-mlogloss:0.09221
[268]	train-mlogloss:0.15404	eval-mlogloss:0.09204
[269]	train-mlogloss:0.15402	eval-mlogloss:0.09214
[270]	train-mlogloss:0.15403	eval-mlogloss:0.09209
[271]	train-mlogloss:0.15403	eval-mlogloss:0.09234
[272]	train-mlogloss:0.15402	eval-mlogloss:0.09173
[273]	train-mlogloss:0.15403	eval-mlogloss:0.09177
[274]	train-mlogloss:0.15403	eval-mlogloss:0.09175
[275]	train-mlogloss:0.15402	eval-mlogloss:0.09172
[276]	train-mlogloss:0.15402	eval-mlogloss:0.09181
[277]	train-mlogloss:0.15402	eval-mlogloss:0.09186
[278]	train-mlogloss:0.15387	eval-mlogloss:0.09157
[279]	train-mlogloss:0.15387	eval-mlogloss:0.09166
[280]	train-mlogloss:0.15387	eval-mlogloss:0.09140
[281]	train-mlogloss:0.15388	eval-mlogloss:0.09132
[282]	train-mlogloss:0.15388	eval-mlogloss:0.09129
[283]	train-mlogloss:0.15388	eval-mlogloss:0.09150
[284]	train-mlogloss:0.15389	eval-mlogloss:0.09132
[285]	train-mlogloss:0.15388	eval-mlogloss:0.09138
[286]	train-mlogloss:0.15388	eval-mlogloss:0.09152
[287]	train-mlogloss:0.15388	eval-mlogloss:0.09163
[288]	train-mlogloss:0.15388	eval-mlogloss:0.09159
[289]	train-mlogloss:0.15387	eval-mlogloss:0.09160
[290]	train-mlogloss:0.15381	eval-mlogloss:0.09164
[291]	train-mlogloss:0.15381	eval-mlogloss:0.09152
[292]	train-mlogloss:0.15381	eval-mlogloss:0.09158
[293]	train-mlogloss:0.15379	eval-mlogloss:0.09168
[294]	train-mlogloss:0.15379	eval-mlogloss:0.09182
[295]	train-mlogloss:0.15366	eval-mlogloss:0.09159
[296]	train-mlogloss:0.15355	eval-mlogloss:0.09150
[297]	train-mlogloss:0.15356	eval-mlogloss:0.09161
[298]	train-mlogloss:0.15355	eval-mlogloss:0.09152
[299]	train-mlogloss:0.15356	eval-mlogloss:0.09167

[I 2026-10-02 10:08:55,312] Trial 0 finished with value: 1.0 and parameters: {'lambda': 1.2228682677245145e-06, 'alpha': 0.001356651354882829, 'eta': 0.10290696426865867, 'gamma': 6.497256432362295e-06, 'max_depth': 8, 'min_child_weight': 6, 'subsample': 0.7562278153728188, 'colsample_bytree': 0.4121805001705988}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.04946	eval-mlogloss:1.04728
[1]	train-mlogloss:1.00396	eval-mlogloss:0.99939
[2]	train-mlogloss:0.96100	eval-mlogloss:0.95300
[3]	train-mlogloss:0.92126	eval-mlogloss:0.91252
[4]	train-mlogloss:0.88213	eval-mlogloss:0.87159
[5]	train-mlogloss:0.84642	eval-mlogloss:0.83480
[6]	train-mlogloss:0.81301	eval-mlogloss:0.79917
[7]	train-mlogloss:0.78141	eval-mlogloss:0.76665
[8]	train-mlogloss:0.75092	eval-mlogloss:0.73457
[9]	train-mlogloss:0.72210	eval-mlogloss:0.70381
[10]	train-mlogloss:0.69479	eval-mlogloss:0.67539
[11]	train-mlogloss:0.66944	eval-mlogloss:0.64869
[12]	train-mlogloss:0.64450	eval-mlogloss:0.62269
[13]	train-mlogloss:0.62106	eval-mlogloss:0.59785
[14]	train-mlogloss:0.59834	eval-mlogloss:0.57573
[15]	train-mlogloss:0.57650	eval-mlogloss:0.55304
[16]	train-mlogloss:0.55611	eval-mlogloss:0.53126
[17]	train-mlogloss:0.53706	eval-mlogloss:0.51104
[18]	train-mlogloss:0.51827	eval-mlogloss:0.49124
[19]	train-mlogloss:0.50093	eval-mlogloss:0.47351
[20]	train-mlogloss:0.48425	eval-mlogloss:0.45583
[21]	train-mlogloss:0.46825	eval-mlogloss:0.43960
[22]	train-mlogloss:0.45341	eval-mlogloss:0.42366
[23]	train-mlogloss:0.43887	eval-mlogloss:0.40890
[24]	train-mlogloss:0.42427	eval-mlogloss:0.39356
[25]	train-mlogloss:0.41047	eval-mlogloss:0.37907
[26]	train-mlogloss:0.39752	eval-mlogloss:0.36500
[27]	train-mlogloss:0.38478	eval-mlogloss:0.35161
[28]	train-mlogloss:0.37361	eval-mlogloss:0.34006
[29]	train-mlogloss:0.36200	eval-mlogloss:0.32825
[30]	train-mlogloss:0.35075	eval-mlogloss:0.31764
[31]	train-mlogloss:0.34027	eval-mlogloss:0.30643
[32]	train-mlogloss:0.32992	eval-mlogloss:0.29534
[33]	train-mlogloss:0.32066	eval-mlogloss:0.28558
[34]	train-mlogloss:0.31151	eval-mlogloss:0.27595
[35]	train-mlogloss:0.30268	eval-mlogloss:0.26676
[36]	train-mlogloss:0.29468	eval-mlogloss:0.25767
[37]	train-mlogloss:0.28652	eval-mlogloss:0.24866
[38]	train-mlogloss:0.27854	eval-mlogloss:0.23996
[39]	train-mlogloss:0.27090	eval-mlogloss:0.23165
[40]	train-mlogloss:0.26385	eval-mlogloss:0.22419
[41]	train-mlogloss:0.25710	eval-mlogloss:0.21750
[42]	train-mlogloss:0.24982	eval-mlogloss:0.21097
[43]	train-mlogloss:0.24334	eval-mlogloss:0.20378
[44]	train-mlogloss:0.23700	eval-mlogloss:0.19923
[45]	train-mlogloss:0.23123	eval-mlogloss:0.19272
[46]	train-mlogloss:0.22535	eval-mlogloss:0.18572
[47]	train-mlogloss:0.21973	eval-mlogloss:0.17954
[48]	train-mlogloss:0.21446	eval-mlogloss:0.17460
[49]	train-mlogloss:0.20927	eval-mlogloss:0.16932
[50]	train-mlogloss:0.20461	eval-mlogloss:0.16410
[51]	train-mlogloss:0.19978	eval-mlogloss:0.15866
[52]	train-mlogloss:0.19504	eval-mlogloss:0.15400
[53]	train-mlogloss:0.19047	eval-mlogloss:0.14985
[54]	train-mlogloss:0.18583	eval-mlogloss:0.14433
[55]	train-mlogloss:0.18158	eval-mlogloss:0.13940
[56]	train-mlogloss:0.17813	eval-mlogloss:0.13592
[57]	train-mlogloss:0.17517	eval-mlogloss:0.13387
[58]	train-mlogloss:0.17151	eval-mlogloss:0.12992
[59]	train-mlogloss:0.16837	eval-mlogloss:0.12656
[60]	train-mlogloss:0.16505	eval-mlogloss:0.12313
[61]	train-mlogloss:0.16186	eval-mlogloss:0.12067
[62]	train-mlogloss:0.15876	eval-mlogloss:0.11744
[63]	train-mlogloss:0.15625	eval-mlogloss:0.11415
[64]	train-mlogloss:0.15333	eval-mlogloss:0.11151
[65]	train-mlogloss:0.15082	eval-mlogloss:0.10870
[66]	train-mlogloss:0.14852	eval-mlogloss:0.10585
[67]	train-mlogloss:0.14575	eval-mlogloss:0.10224
[68]	train-mlogloss:0.14388	eval-mlogloss:0.10008
[69]	train-mlogloss:0.14183	eval-mlogloss:0.09786
[70]	train-mlogloss:0.13973	eval-mlogloss:0.09567
[71]	train-mlogloss:0.13836	eval-mlogloss:0.09379
[72]	train-mlogloss:0.13661	eval-mlogloss:0.09178
[73]	train-mlogloss:0.13490	eval-mlogloss:0.08945
[74]	train-mlogloss:0.13316	eval-mlogloss:0.08720
[75]	train-mlogloss:0.13134	eval-mlogloss:0.08530
[76]	train-mlogloss:0.12986	eval-mlogloss:0.08387
[77]	train-mlogloss:0.12809	eval-mlogloss:0.08199
[78]	train-mlogloss:0.12722	eval-mlogloss:0.08052
[79]	train-mlogloss:0.12563	eval-mlogloss:0.07845
[80]	train-mlogloss:0.12512	eval-mlogloss:0.07777
[81]	train-mlogloss:0.12497	eval-mlogloss:0.07780
[82]	train-mlogloss:0.12429	eval-mlogloss:0.07682
[83]	train-mlogloss:0.12317	eval-mlogloss:0.07560
[84]	train-mlogloss:0.12277	eval-mlogloss:0.07577
[85]	train-mlogloss:0.12245	eval-mlogloss:0.07574
[86]	train-mlogloss:0.12196	eval-mlogloss:0.07505
[87]	train-mlogloss:0.12145	eval-mlogloss:0.07496
[88]	train-mlogloss:0.12089	eval-mlogloss:0.07425
[89]	train-mlogloss:0.12058	eval-mlogloss:0.07415
[90]	train-mlogloss:0.12015	eval-mlogloss:0.07344
[91]	train-mlogloss:0.11986	eval-mlogloss:0.07274
[92]	train-mlogloss:0.11936	eval-mlogloss:0.07205
[93]	train-mlogloss:0.11914	eval-mlogloss:0.07182
[94]	train-mlogloss:0.11889	eval-mlogloss:0.07145
[95]	train-mlogloss:0.11845	eval-mlogloss:0.07076
[96]	train-mlogloss:0.11789	eval-mlogloss:0.06995
[97]	train-mlogloss:0.11760	eval-mlogloss:0.06963
[98]	train-mlogloss:0.11708	eval-mlogloss:0.06864
[99]	train-mlogloss:0.11677	eval-mlogloss:0.06790
[100]	train-mlogloss:0.11634	eval-mlogloss:0.06705
[101]	train-mlogloss:0.11526	eval-mlogloss:0.06603
[102]	train-mlogloss:0.11484	eval-mlogloss:0.06550
[103]	train-mlogloss:0.11428	eval-mlogloss:0.06544
[104]	train-mlogloss:0.11380	eval-mlogloss:0.06494
[105]	train-mlogloss:0.11347	eval-mlogloss:0.06450
[106]	train-mlogloss:0.11305	eval-mlogloss:0.06381
[107]	train-mlogloss:0.11272	eval-mlogloss:0.06348
[108]	train-mlogloss:0.11273	eval-mlogloss:0.06312
[109]	train-mlogloss:0.11257	eval-mlogloss:0.06317
[110]	train-mlogloss:0.11219	eval-mlogloss:0.06259
[111]	train-mlogloss:0.11202	eval-mlogloss:0.06245
[112]	train-mlogloss:0.11175	eval-mlogloss:0.06210
[113]	train-mlogloss:0.11138	eval-mlogloss:0.06149
[114]	train-mlogloss:0.11105	eval-mlogloss:0.06114
[115]	train-mlogloss:0.11067	eval-mlogloss:0.06059
[116]	train-mlogloss:0.11048	eval-mlogloss:0.06033
[117]	train-mlogloss:0.11009	eval-mlogloss:0.05979
[118]	train-mlogloss:0.10980	eval-mlogloss:0.05995
[119]	train-mlogloss:0.10949	eval-mlogloss:0.05956
[120]	train-mlogloss:0.10907	eval-mlogloss:0.05899
[121]	train-mlogloss:0.10877	eval-mlogloss:0.05872
[122]	train-mlogloss:0.10856	eval-mlogloss:0.05862
[123]	train-mlogloss:0.10847	eval-mlogloss:0.05885
[124]	train-mlogloss:0.10824	eval-mlogloss:0.05811
[125]	train-mlogloss:0.10798	eval-mlogloss:0.05815
[126]	train-mlogloss:0.10795	eval-mlogloss:0.05802
[127]	train-mlogloss:0.10793	eval-mlogloss:0.05813
[128]	train-mlogloss:0.10743	eval-mlogloss:0.05765
[129]	train-mlogloss:0.10721	eval-mlogloss:0.05701
[130]	train-mlogloss:0.10676	eval-mlogloss:0.05632
[131]	train-mlogloss:0.10655	eval-mlogloss:0.05605
[132]	train-mlogloss:0.10636	eval-mlogloss:0.05566
[133]	train-mlogloss:0.10628	eval-mlogloss:0.05556
[134]	train-mlogloss:0.10613	eval-mlogloss:0.05507
[135]	train-mlogloss:0.10607	eval-mlogloss:0.05505
[136]	train-mlogloss:0.10594	eval-mlogloss:0.05485
[137]	train-mlogloss:0.10583	eval-mlogloss:0.05443
[138]	train-mlogloss:0.10568	eval-mlogloss:0.05405
[139]	train-mlogloss:0.10557	eval-mlogloss:0.05372
[140]	train-mlogloss:0.10529	eval-mlogloss:0.05388
[141]	train-mlogloss:0.10511	eval-mlogloss:0.05403
[142]	train-mlogloss:0.10488	eval-mlogloss:0.05380
[143]	train-mlogloss:0.10469	eval-mlogloss:0.05389
[144]	train-mlogloss:0.10453	eval-mlogloss:0.05365
[145]	train-mlogloss:0.10429	eval-mlogloss:0.05320
[146]	train-mlogloss:0.10409	eval-mlogloss:0.05330
[147]	train-mlogloss:0.10391	eval-mlogloss:0.05334
[148]	train-mlogloss:0.10371	eval-mlogloss:0.05303
[149]	train-mlogloss:0.10351	eval-mlogloss:0.05277
[150]	train-mlogloss:0.10334	eval-mlogloss:0.05261
[151]	train-mlogloss:0.10318	eval-mlogloss:0.05233
[152]	train-mlogloss:0.10298	eval-mlogloss:0.05230
[153]	train-mlogloss:0.10285	eval-mlogloss:0.05238
[154]	train-mlogloss:0.10272	eval-mlogloss:0.05242
[155]	train-mlogloss:0.10244	eval-mlogloss:0.05203
[156]	train-mlogloss:0.10220	eval-mlogloss:0.05170
[157]	train-mlogloss:0.10219	eval-mlogloss:0.05173
[158]	train-mlogloss:0.10217	eval-mlogloss:0.05177
[159]	train-mlogloss:0.10198	eval-mlogloss:0.05181
[160]	train-mlogloss:0.10179	eval-mlogloss:0.05183
[161]	train-mlogloss:0.10180	eval-mlogloss:0.05184
[162]	train-mlogloss:0.10180	eval-mlogloss:0.05184
[163]	train-mlogloss:0.10169	eval-mlogloss:0.05212
[164]	train-mlogloss:0.10170	eval-mlogloss:0.05211
[165]	train-mlogloss:0.10158	eval-mlogloss:0.05185
[166]	train-mlogloss:0.10142	eval-mlogloss:0.05204
[167]	train-mlogloss:0.10124	eval-mlogloss:0.05182
[168]	train-mlogloss:0.10122	eval-mlogloss:0.05151
[169]	train-mlogloss:0.10121	eval-mlogloss:0.05125
[170]	train-mlogloss:0.10097	eval-mlogloss:0.05103
[171]	train-mlogloss:0.10086	eval-mlogloss:0.05078
[172]	train-mlogloss:0.10061	eval-mlogloss:0.05028
[173]	train-mlogloss:0.10060	eval-mlogloss:0.05030
[174]	train-mlogloss:0.10039	eval-mlogloss:0.05012
[175]	train-mlogloss:0.10031	eval-mlogloss:0.05001
[176]	train-mlogloss:0.10012	eval-mlogloss:0.04981
[177]	train-mlogloss:0.09992	eval-mlogloss:0.04959
[178]	train-mlogloss:0.09983	eval-mlogloss:0.04949
[179]	train-mlogloss:0.09964	eval-mlogloss:0.04928
[180]	train-mlogloss:0.09953	eval-mlogloss:0.04883
[181]	train-mlogloss:0.09954	eval-mlogloss:0.04874
[182]	train-mlogloss:0.09944	eval-mlogloss:0.04849
[183]	train-mlogloss:0.09943	eval-mlogloss:0.04855
[184]	train-mlogloss:0.09936	eval-mlogloss:0.04852
[185]	train-mlogloss:0.09928	eval-mlogloss:0.04852
[186]	train-mlogloss:0.09926	eval-mlogloss:0.04868
[187]	train-mlogloss:0.09924	eval-mlogloss:0.04854
[188]	train-mlogloss:0.09908	eval-mlogloss:0.04858
[189]	train-mlogloss:0.09911	eval-mlogloss:0.04858
[190]	train-mlogloss:0.09915	eval-mlogloss:0.04854
[191]	train-mlogloss:0.09912	eval-mlogloss:0.04856
[192]	train-mlogloss:0.09907	eval-mlogloss:0.04838
[193]	train-mlogloss:0.09900	eval-mlogloss:0.04837
[194]	train-mlogloss:0.09888	eval-mlogloss:0.04839
[195]	train-mlogloss:0.09880	eval-mlogloss:0.04803
[196]	train-mlogloss:0.09871	eval-mlogloss:0.04791
[197]	train-mlogloss:0.09855	eval-mlogloss:0.04811
[198]	train-mlogloss:0.09847	eval-mlogloss:0.04829
[199]	train-mlogloss:0.09827	eval-mlogloss:0.04808
[200]	train-mlogloss:0.09821	eval-mlogloss:0.04791
[201]	train-mlogloss:0.09800	eval-mlogloss:0.04763
[202]	train-mlogloss:0.09798	eval-mlogloss:0.04764
[203]	train-mlogloss:0.09798	eval-mlogloss:0.04754
[204]	train-mlogloss:0.09779	eval-mlogloss:0.04750
[205]	train-mlogloss:0.09768	eval-mlogloss:0.04733
[206]	train-mlogloss:0.09768	eval-mlogloss:0.04746
[207]	train-mlogloss:0.09768	eval-mlogloss:0.04761
[208]	train-mlogloss:0.09765	eval-mlogloss:0.04758
[209]	train-mlogloss:0.09764	eval-mlogloss:0.04760
[210]	train-mlogloss:0.09763	eval-mlogloss:0.04762
[211]	train-mlogloss:0.09758	eval-mlogloss:0.04755
[212]	train-mlogloss:0.09739	eval-mlogloss:0.04726
[213]	train-mlogloss:0.09712	eval-mlogloss:0.04692
[214]	train-mlogloss:0.09709	eval-mlogloss:0.04698
[215]	train-mlogloss:0.09705	eval-mlogloss:0.04707
[216]	train-mlogloss:0.09697	eval-mlogloss:0.04708
[217]	train-mlogloss:0.09680	eval-mlogloss:0.04722
[218]	train-mlogloss:0.09666	eval-mlogloss:0.04714
[219]	train-mlogloss:0.09640	eval-mlogloss:0.04673
[220]	train-mlogloss:0.09639	eval-mlogloss:0.04670
[221]	train-mlogloss:0.09632	eval-mlogloss:0.04642
[222]	train-mlogloss:0.09614	eval-mlogloss:0.04624
[223]	train-mlogloss:0.09610	eval-mlogloss:0.04616
[224]	train-mlogloss:0.09610	eval-mlogloss:0.04621
[225]	train-mlogloss:0.09609	eval-mlogloss:0.04631
[226]	train-mlogloss:0.09598	eval-mlogloss:0.04614
[227]	train-mlogloss:0.09592	eval-mlogloss:0.04609
[228]	train-mlogloss:0.09588	eval-mlogloss:0.04598
[229]	train-mlogloss:0.09582	eval-mlogloss:0.04600
[230]	train-mlogloss:0.09575	eval-mlogloss:0.04629
[231]	train-mlogloss:0.09572	eval-mlogloss:0.04636
[232]	train-mlogloss:0.09573	eval-mlogloss:0.04650
[233]	train-mlogloss:0.09565	eval-mlogloss:0.04634
[234]	train-mlogloss:0.09557	eval-mlogloss:0.04625
[235]	train-mlogloss:0.09545	eval-mlogloss:0.04607
[236]	train-mlogloss:0.09542	eval-mlogloss:0.04594
[237]	train-mlogloss:0.09541	eval-mlogloss:0.04578
[238]	train-mlogloss:0.09523	eval-mlogloss:0.04584
[239]	train-mlogloss:0.09522	eval-mlogloss:0.04587
[240]	train-mlogloss:0.09525	eval-mlogloss:0.04580
[241]	train-mlogloss:0.09504	eval-mlogloss:0.04541
[242]	train-mlogloss:0.09504	eval-mlogloss:0.04565
[243]	train-mlogloss:0.09482	eval-mlogloss:0.04519
[244]	train-mlogloss:0.09472	eval-mlogloss:0.04518
[245]	train-mlogloss:0.09466	eval-mlogloss:0.04508
[246]	train-mlogloss:0.09465	eval-mlogloss:0.04513
[247]	train-mlogloss:0.09461	eval-mlogloss:0.04523
[248]	train-mlogloss:0.09461	eval-mlogloss:0.04511
[249]	train-mlogloss:0.09462	eval-mlogloss:0.04510
[250]	train-mlogloss:0.09457	eval-mlogloss:0.04510
[251]	train-mlogloss:0.09457	eval-mlogloss:0.04515
[252]	train-mlogloss:0.09451	eval-mlogloss:0.04515
[253]	train-mlogloss:0.09451	eval-mlogloss:0.04504
[254]	train-mlogloss:0.09450	eval-mlogloss:0.04517
[255]	train-mlogloss:0.09448	eval-mlogloss:0.04506
[256]	train-mlogloss:0.09441	eval-mlogloss:0.04492
[257]	train-mlogloss:0.09440	eval-mlogloss:0.04493
[258]	train-mlogloss:0.09439	eval-mlogloss:0.04488
[259]	train-mlogloss:0.09435	eval-mlogloss:0.04481
[260]	train-mlogloss:0.09433	eval-mlogloss:0.04479
[261]	train-mlogloss:0.09433	eval-mlogloss:0.04489
[262]	train-mlogloss:0.09433	eval-mlogloss:0.04489
[263]	train-mlogloss:0.09433	eval-mlogloss:0.04478
[264]	train-mlogloss:0.09431	eval-mlogloss:0.04475
[265]	train-mlogloss:0.09428	eval-mlogloss:0.04480
[266]	train-mlogloss:0.09425	eval-mlogloss:0.04467
[267]	train-mlogloss:0.09419	eval-mlogloss:0.04464
[268]	train-mlogloss:0.09420	eval-mlogloss:0.04453
[269]	train-mlogloss:0.09420	eval-mlogloss:0.04451
[270]	train-mlogloss:0.09413	eval-mlogloss:0.04423
[271]	train-mlogloss:0.09411	eval-mlogloss:0.04428
[272]	train-mlogloss:0.09411	eval-mlogloss:0.04443
[273]	train-mlogloss:0.09411	eval-mlogloss:0.04429
[274]	train-mlogloss:0.09400	eval-mlogloss:0.04428
[275]	train-mlogloss:0.09384	eval-mlogloss:0.04441
[276]	train-mlogloss:0.09383	eval-mlogloss:0.04431
[277]	train-mlogloss:0.09383	eval-mlogloss:0.04428
[278]	train-mlogloss:0.09383	eval-mlogloss:0.04438
[279]	train-mlogloss:0.09384	eval-mlogloss:0.04438
[280]	train-mlogloss:0.09382	eval-mlogloss:0.04415
[281]	train-mlogloss:0.09363	eval-mlogloss:0.04431
[282]	train-mlogloss:0.09351	eval-mlogloss:0.04442
[283]	train-mlogloss:0.09333	eval-mlogloss:0.04435
[284]	train-mlogloss:0.09333	eval-mlogloss:0.04435
[285]	train-mlogloss:0.09328	eval-mlogloss:0.04437
[286]	train-mlogloss:0.09328	eval-mlogloss:0.04443
[287]	train-mlogloss:0.09321	eval-mlogloss:0.04437
[288]	train-mlogloss:0.09321	eval-mlogloss:0.04433
[289]	train-mlogloss:0.09322	eval-mlogloss:0.04452
[290]	train-mlogloss:0.09321	eval-mlogloss:0.04462
[291]	train-mlogloss:0.09310	eval-mlogloss:0.04473
[292]	train-mlogloss:0.09299	eval-mlogloss:0.04453
[293]	train-mlogloss:0.09298	eval-mlogloss:0.04456
[294]	train-mlogloss:0.09298	eval-mlogloss:0.04461
[295]	train-mlogloss:0.09294	eval-mlogloss:0.04459
[296]	train-mlogloss:0.09293	eval-mlogloss:0.04460
[297]	train-mlogloss:0.09290	eval-mlogloss:0.04461
[298]	train-mlogloss:0.09289	eval-mlogloss:0.04456
[299]	train-mlogloss:0.09287	eval-mlogloss:0.04463

[I 2026-10-02 10:08:55,992] Trial 1 finished with value: 1.0 and parameters: {'lambda': 0.007080610727302091, 'alpha': 0.0005400665061186119, 'eta': 0.03741815191721627, 'gamma': 9.55155223337928e-05, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.6765911656580488, 'colsample_bytree': 0.8292703498453438}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.04698	eval-mlogloss:1.05254
[1]	train-mlogloss:0.98914	eval-mlogloss:0.99146

[I 2026-10-02 10:08:56,011] Trial 2 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.89104	eval-mlogloss:0.87246
[1]	train-mlogloss:0.73797	eval-mlogloss:0.70832

[I 2026-10-02 10:08:56,026] Trial 3 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.79895	eval-mlogloss:0.79333
[1]	train-mlogloss:0.57829	eval-mlogloss:0.56029

[I 2026-10-02 10:08:56,037] Trial 4 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.85617	eval-mlogloss:0.83711
[1]	train-mlogloss:0.68673	eval-mlogloss:0.65272

[I 2026-10-02 10:08:56,049] Trial 5 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.82774	eval-mlogloss:0.81479
[1]	train-mlogloss:0.64790	eval-mlogloss:0.62273

[I 2026-10-02 10:08:56,060] Trial 6 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.80900	eval-mlogloss:0.78223
[1]	train-mlogloss:0.62187	eval-mlogloss:0.58893

[I 2026-10-02 10:08:56,108] Trial 7 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.88930	eval-mlogloss:0.86934
[1]	train-mlogloss:0.74679	eval-mlogloss:0.72345

[I 2026-10-02 10:08:56,126] Trial 8 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.88682	eval-mlogloss:0.87888
[1]	train-mlogloss:0.67658	eval-mlogloss:0.65691

[I 2026-10-02 10:08:56,145] Trial 9 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03389	eval-mlogloss:1.03205
[1]	train-mlogloss:0.97260	eval-mlogloss:0.96838
[2]	train-mlogloss:0.94514	eval-mlogloss:0.94651
[3]	train-mlogloss:0.92047	eval-mlogloss:0.92109
[4]	train-mlogloss:0.86900	eval-mlogloss:0.86767
[5]	train-mlogloss:0.81459	eval-mlogloss:0.81194
[6]	train-mlogloss:0.79652	eval-mlogloss:0.79273
[7]	train-mlogloss:0.77405	eval-mlogloss:0.76802

[I 2026-10-02 10:08:56,196] Trial 10 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.02268	eval-mlogloss:1.01939
[1]	train-mlogloss:0.94366	eval-mlogloss:0.93600

[I 2026-10-02 10:08:56,226] Trial 11 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07406	eval-mlogloss:1.07622
[1]	train-mlogloss:1.04999	eval-mlogloss:1.05174
[2]	train-mlogloss:1.03694	eval-mlogloss:1.04218
[3]	train-mlogloss:1.02514	eval-mlogloss:1.03297
[4]	train-mlogloss:1.00260	eval-mlogloss:1.01053
[5]	train-mlogloss:0.97802	eval-mlogloss:0.98441
[6]	train-mlogloss:0.96675	eval-mlogloss:0.97415
[7]	train-mlogloss:0.95343	eval-mlogloss:0.96188
[8]	train-mlogloss:0.93297	eval-mlogloss:0.94121
[9]	train-mlogloss:0.91085	eval-mlogloss:0.91756
[10]	train-mlogloss:0.89327	eval-mlogloss:0.89846
[11]	train-mlogloss:0.87566	eval-mlogloss:0.87963
[12]	train-mlogloss:0.85784	eval-mlogloss:0.86152
[13]	train-mlogloss:0.84428	eval-mlogloss:0.84980
[14]	train-mlogloss:0.82716	eval-mlogloss:0.83276
[15]	train-mlogloss:0.81072	eval-mlogloss:0.81603
[16]	train-mlogloss:0.79494	eval-mlogloss:0.79925
[17]	train-mlogloss:0.77512	eval-mlogloss:0.77806
[18]	train-mlogloss:0.75923	eval-mlogloss:0.76186
[19]	train-mlogloss:0.74368	eval-mlogloss:0.74663
[20]	train-mlogloss:0.73460	eval-mlogloss:0.73855
[21]	train-mlogloss:0.71933	eval-mlogloss:0.72401
[22]	train-mlogloss:0.70639	eval-mlogloss:0.70983
[23]	train-mlogloss:0.69986	eval-mlogloss:0.70473
[24]	train-mlogloss:0.68373	eval-mlogloss:0.68674
[25]	train-mlogloss:0.66762	eval-mlogloss:0.66930
[26]	train-mlogloss:0.65762	eval-mlogloss:0.65842
[27]	train-mlogloss:0.65147	eval-mlogloss:0.65278
[28]	train-mlogloss:0.64216	eval-mlogloss:0.64361
[29]	train-mlogloss:0.63016	eval-mlogloss:0.63108
[30]	train-mlogloss:0.62312	eval-mlogloss:0.62499
[31]	train-mlogloss:0.61237	eval-mlogloss:0.61367
[32]	train-mlogloss:0.60101	eval-mlogloss:0.60092
[33]	train-mlogloss:0.59644	eval-mlogloss:0.59676
[34]	train-mlogloss:0.58270	eval-mlogloss:0.58172
[35]	train-mlogloss:0.57311	eval-mlogloss:0.57241
[36]	train-mlogloss:0.56244	eval-mlogloss:0.56019
[37]	train-mlogloss:0.55658	eval-mlogloss:0.55578
[38]	train-mlogloss:0.55007	eval-mlogloss:0.54929
[39]	train-mlogloss:0.54445	eval-mlogloss:0.54407
[40]	train-mlogloss:0.53723	eval-mlogloss:0.53693
[41]	train-mlogloss:0.52978	eval-mlogloss:0.52991
[42]	train-mlogloss:0.52126	eval-mlogloss:0.52128
[43]	train-mlogloss:0.51457	eval-mlogloss:0.51407
[44]	train-mlogloss:0.50675	eval-mlogloss:0.50631
[45]	train-mlogloss:0.49632	eval-mlogloss:0.49435
[46]	train-mlogloss:0.49092	eval-mlogloss:0.48871
[47]	train-mlogloss:0.48288	eval-mlogloss:0.47954
[48]	train-mlogloss:0.47741	eval-mlogloss:0.47288
[49]	train-mlogloss:0.47289	eval-mlogloss:0.46904
[50]	train-mlogloss:0.46796	eval-mlogloss:0.46428
[51]	train-mlogloss:0.46079	eval-mlogloss:0.45728
[52]	train-mlogloss:0.45132	eval-mlogloss:0.44701
[53]	train-mlogloss:0.44482	eval-mlogloss:0.43961
[54]	train-mlogloss:0.43586	eval-mlogloss:0.42905
[55]	train-mlogloss:0.42896	eval-mlogloss:0.42183
[56]	train-mlogloss:0.42285	eval-mlogloss:0.41599
[57]	train-mlogloss:0.41981	eval-mlogloss:0.41377
[58]	train-mlogloss:0.41759	eval-mlogloss:0.41221
[59]	train-mlogloss:0.40935	eval-mlogloss:0.40300
[60]	train-mlogloss:0.40434	eval-mlogloss:0.39767
[61]	train-mlogloss:0.40031	eval-mlogloss:0.39374
[62]	train-mlogloss:0.39478	eval-mlogloss:0.38796
[63]	train-mlogloss:0.39140	eval-mlogloss:0.38531
[64]	train-mlogloss:0.38846	eval-mlogloss:0.38286
[65]	train-mlogloss:0.38674	eval-mlogloss:0.38215
[66]	train-mlogloss:0.37931	eval-mlogloss:0.37394
[67]	train-mlogloss:0.37558	eval-mlogloss:0.37070
[68]	train-mlogloss:0.37192	eval-mlogloss:0.36722
[69]	train-mlogloss:0.36596	eval-mlogloss:0.36056
[70]	train-mlogloss:0.36274	eval-mlogloss:0.35813
[71]	train-mlogloss:0.35713	eval-mlogloss:0.35215
[72]	train-mlogloss:0.35154	eval-mlogloss:0.34627
[73]	train-mlogloss:0.34947	eval-mlogloss:0.34486
[74]	train-mlogloss:0.34474	eval-mlogloss:0.33986
[75]	train-mlogloss:0.34274	eval-mlogloss:0.33874
[76]	train-mlogloss:0.33775	eval-mlogloss:0.33377
[77]	train-mlogloss:0.33582	eval-mlogloss:0.33233
[78]	train-mlogloss:0.33135	eval-mlogloss:0.32699
[79]	train-mlogloss:0.32604	eval-mlogloss:0.32075
[80]	train-mlogloss:0.32424	eval-mlogloss:0.31917
[81]	train-mlogloss:0.32030	eval-mlogloss:0.31553
[82]	train-mlogloss:0.31907	eval-mlogloss:0.31506
[83]	train-mlogloss:0.31366	eval-mlogloss:0.30889
[84]	train-mlogloss:0.31209	eval-mlogloss:0.30834
[85]	train-mlogloss:0.30634	eval-mlogloss:0.30140
[86]	train-mlogloss:0.30367	eval-mlogloss:0.29928
[87]	train-mlogloss:0.29985	eval-mlogloss:0.29518
[88]	train-mlogloss:0.29566	eval-mlogloss:0.29069
[89]	train-mlogloss:0.29325	eval-mlogloss:0.28855
[90]	train-mlogloss:0.28899	eval-mlogloss:0.28416
[91]	train-mlogloss:0.28692	eval-mlogloss:0.28246
[92]	train-mlogloss:0.28318	eval-mlogloss:0.27872
[93]	train-mlogloss:0.27977	eval-mlogloss:0.27511
[94]	train-mlogloss:0.27765	eval-mlogloss:0.27309
[95]	train-mlogloss:0.27369	eval-mlogloss:0.26842
[96]	train-mlogloss:0.27128	eval-mlogloss:0.26565
[97]	train-mlogloss:0.26690	eval-mlogloss:0.26077
[98]	train-mlogloss:0.26540	eval-mlogloss:0.25992
[99]	train-mlogloss:0.26194	eval-mlogloss:0.25562
[100]	train-mlogloss:0.26079	eval-mlogloss:0.25510
[101]	train-mlogloss:0.25958	eval-mlogloss:0.25465
[102]	train-mlogloss:0.25573	eval-mlogloss:0.25002
[103]	train-mlogloss:0.25265	eval-mlogloss:0.24694
[104]	train-mlogloss:0.25015	eval-mlogloss:0.24409
[105]	train-mlogloss:0.24603	eval-mlogloss:0.23905
[106]	train-mlogloss:0.24453	eval-mlogloss:0.23791
[107]	train-mlogloss:0.24255	eval-mlogloss:0.23616
[108]	train-mlogloss:0.23993	eval-mlogloss:0.23321
[109]	train-mlogloss:0.23690	eval-mlogloss:0.23000
[110]	train-mlogloss:0.23500	eval-mlogloss:0.22803
[111]	train-mlogloss:0.23315	eval-mlogloss:0.22621
[112]	train-mlogloss:0.23009	eval-mlogloss:0.22283
[113]	train-mlogloss:0.22935	eval-mlogloss:0.22260
[114]	train-mlogloss:0.22668	eval-mlogloss:0.21970
[115]	train-mlogloss:0.22337	eval-mlogloss:0.21603
[116]	train-mlogloss:0.22159	eval-mlogloss:0.21470
[117]	train-mlogloss:0.21886	eval-mlogloss:0.21169
[118]	train-mlogloss:0.21667	eval-mlogloss:0.20994
[119]	train-mlogloss:0.21393	eval-mlogloss:0.20660
[120]	train-mlogloss:0.21076	eval-mlogloss:0.20309
[121]	train-mlogloss:0.20847	eval-mlogloss:0.20065
[122]	train-mlogloss:0.20548	eval-mlogloss:0.19721
[123]	train-mlogloss:0.20369	eval-mlogloss:0.19509
[124]	train-mlogloss:0.20205	eval-mlogloss:0.19345
[125]	train-mlogloss:0.19953	eval-mlogloss:0.19084
[126]	train-mlogloss:0.19815	eval-mlogloss:0.18962
[127]	train-mlogloss:0.19621	eval-mlogloss:0.18725
[128]	train-mlogloss:0.19503	eval-mlogloss:0.18612
[129]	train-mlogloss:0.19389	eval-mlogloss:0.18554
[130]	train-mlogloss:0.19347	eval-mlogloss:0.18564
[131]	train-mlogloss:0.19260	eval-mlogloss:0.18499
[132]	train-mlogloss:0.19058	eval-mlogloss:0.18242
[133]	train-mlogloss:0.18900	eval-mlogloss:0.18057
[134]	train-mlogloss:0.18638	eval-mlogloss:0.17701
[135]	train-mlogloss:0.18563	eval-mlogloss:0.17673
[136]	train-mlogloss:0.18394	eval-mlogloss:0.17517
[137]	train-mlogloss:0.18206	eval-mlogloss:0.17231
[138]	train-mlogloss:0.18039	eval-mlogloss:0.17057
[139]	train-mlogloss:0.17795	eval-mlogloss:0.16772
[140]	train-mlogloss:0.17639	eval-mlogloss:0.16578
[141]	train-mlogloss:0.17485	eval-mlogloss:0.16431
[142]	train-mlogloss:0.17381	eval-mlogloss:0.16331
[143]	train-mlogloss:0.17215	eval-mlogloss:0.16205
[144]	train-mlogloss:0.17083	eval-mlogloss:0.16052
[145]	train-mlogloss:0.16880	eval-mlogloss:0.15805
[146]	train-mlogloss:0.16833	eval-mlogloss:0.15797
[147]	train-mlogloss:0.16682	eval-mlogloss:0.15612
[148]	train-mlogloss:0.16476	eval-mlogloss:0.15326
[149]	train-mlogloss:0.16397	eval-mlogloss:0.15272
[150]	train-mlogloss:0.16249	eval-mlogloss:0.15107
[151]	train-mlogloss:0.16210	eval-mlogloss:0.15082
[152]	train-mlogloss:0.16107	eval-mlogloss:0.14971
[153]	train-mlogloss:0.15965	eval-mlogloss:0.14795
[154]	train-mlogloss:0.15927	eval-mlogloss:0.14803
[155]	train-mlogloss:0.15799	eval-mlogloss:0.14676
[156]	train-mlogloss:0.15642	eval-mlogloss:0.14468
[157]	train-mlogloss:0.15451	eval-mlogloss:0.14210
[158]	train-mlogloss:0.15315	eval-mlogloss:0.14016
[159]	train-mlogloss:0.15151	eval-mlogloss:0.13821
[160]	train-mlogloss:0.15062	eval-mlogloss:0.13765
[161]	train-mlogloss:0.14956	eval-mlogloss:0.13667
[162]	train-mlogloss:0.14784	eval-mlogloss:0.13431
[163]	train-mlogloss:0.14677	eval-mlogloss:0.13306
[164]	train-mlogloss:0.14556	eval-mlogloss:0.13181
[165]	train-mlogloss:0.14471	eval-mlogloss:0.13085
[166]	train-mlogloss:0.14386	eval-mlogloss:0.12994
[167]	train-mlogloss:0.14303	eval-mlogloss:0.12885
[168]	train-mlogloss:0.14287	eval-mlogloss:0.12858
[169]	train-mlogloss:0.14171	eval-mlogloss:0.12721
[170]	train-mlogloss:0.14018	eval-mlogloss:0.12535
[171]	train-mlogloss:0.13912	eval-mlogloss:0.12421
[172]	train-mlogloss:0.13768	eval-mlogloss:0.12258
[173]	train-mlogloss:0.13667	eval-mlogloss:0.12172
[174]	train-mlogloss:0.13555	eval-mlogloss:0.12073
[175]	train-mlogloss:0.13488	eval-mlogloss:0.12040
[176]	train-mlogloss:0.13398	eval-mlogloss:0.11916
[177]	train-mlogloss:0.13312	eval-mlogloss:0.11808
[178]	train-mlogloss:0.13192	eval-mlogloss:0.11627
[179]	train-mlogloss:0.13108	eval-mlogloss:0.11544
[180]	train-mlogloss:0.13011	eval-mlogloss:0.11461
[181]	train-mlogloss:0.12927	eval-mlogloss:0.11357
[182]	train-mlogloss:0.12847	eval-mlogloss:0.11259
[183]	train-mlogloss:0.12772	eval-mlogloss:0.11180
[184]	train-mlogloss:0.12681	eval-mlogloss:0.11103
[185]	train-mlogloss:0.12593	eval-mlogloss:0.11019
[186]	train-mlogloss:0.12565	eval-mlogloss:0.11017
[187]	train-mlogloss:0.12486	eval-mlogloss:0.10924
[188]	train-mlogloss:0.12370	eval-mlogloss:0.10767
[189]	train-mlogloss:0.12314	eval-mlogloss:0.10707
[190]	train-mlogloss:0.12257	eval-mlogloss:0.10650
[191]	train-mlogloss:0.12179	eval-mlogloss:0.10576
[192]	train-mlogloss:0.12068	eval-mlogloss:0.10443
[193]	train-mlogloss:0.12006	eval-mlogloss:0.10377
[194]	train-mlogloss:0.11977	eval-mlogloss:0.10372
[195]	train-mlogloss:0.11921	eval-mlogloss:0.10284
[196]	train-mlogloss:0.11879	eval-mlogloss:0.10259
[197]	train-mlogloss:0.11800	eval-mlogloss:0.10194
[198]	train-mlogloss:0.11721	eval-mlogloss:0.10088
[199]	train-mlogloss:0.11650	eval-mlogloss:0.10019
[200]	train-mlogloss:0.11583	eval-mlogloss:0.09968
[201]	train-mlogloss:0.11556	eval-mlogloss:0.09953
[202]	train-mlogloss:0.11492	eval-mlogloss:0.09875
[203]	train-mlogloss:0.11454	eval-mlogloss:0.09858
[204]	train-mlogloss:0.11383	eval-mlogloss:0.09792
[205]	train-mlogloss:0.11324	eval-mlogloss:0.09736
[206]	train-mlogloss:0.11279	eval-mlogloss:0.09694
[207]	train-mlogloss:0.11217	eval-mlogloss:0.09624
[208]	train-mlogloss:0.11150	eval-mlogloss:0.09570
[209]	train-mlogloss:0.11114	eval-mlogloss:0.09557
[210]	train-mlogloss:0.11065	eval-mlogloss:0.09503
[211]	train-mlogloss:0.11035	eval-mlogloss:0.09492
[212]	train-mlogloss:0.10979	eval-mlogloss:0.09418
[213]	train-mlogloss:0.10896	eval-mlogloss:0.09302
[214]	train-mlogloss:0.10864	eval-mlogloss:0.09260
[215]	train-mlogloss:0.10785	eval-mlogloss:0.09121
[216]	train-mlogloss:0.10735	eval-mlogloss:0.09069
[217]	train-mlogloss:0.10691	eval-mlogloss:0.09000
[218]	train-mlogloss:0.10622	eval-mlogloss:0.08906
[219]	train-mlogloss:0.10537	eval-mlogloss:0.08796
[220]	train-mlogloss:0.10483	eval-mlogloss:0.08708
[221]	train-mlogloss:0.10439	eval-mlogloss:0.08670
[222]	train-mlogloss:0.10378	eval-mlogloss:0.08597
[223]	train-mlogloss:0.10364	eval-mlogloss:0.08587
[224]	train-mlogloss:0.10312	eval-mlogloss:0.08554
[225]	train-mlogloss:0.10285	eval-mlogloss:0.08532
[226]	train-mlogloss:0.10253	eval-mlogloss:0.08508
[227]	train-mlogloss:0.10181	eval-mlogloss:0.08409
[228]	train-mlogloss:0.10132	eval-mlogloss:0.08363
[229]	train-mlogloss:0.10107	eval-mlogloss:0.08354
[230]	train-mlogloss:0.10047	eval-mlogloss:0.08305
[231]	train-mlogloss:0.10015	eval-mlogloss:0.08294
[232]	train-mlogloss:0.09944	eval-mlogloss:0.08189
[233]	train-mlogloss:0.09925	eval-mlogloss:0.08185
[234]	train-mlogloss:0.09896	eval-mlogloss:0.08178
[235]	train-mlogloss:0.09836	eval-mlogloss:0.08105
[236]	train-mlogloss:0.09788	eval-mlogloss:0.08076
[237]	train-mlogloss:0.09753	eval-mlogloss:0.08024
[238]	train-mlogloss:0.09711	eval-mlogloss:0.07994
[239]	train-mlogloss:0.09659	eval-mlogloss:0.07919
[240]	train-mlogloss:0.09613	eval-mlogloss:0.07849
[241]	train-mlogloss:0.09583	eval-mlogloss:0.07839
[242]	train-mlogloss:0.09539	eval-mlogloss:0.07802
[243]	train-mlogloss:0.09502	eval-mlogloss:0.07757
[244]	train-mlogloss:0.09468	eval-mlogloss:0.07746
[245]	train-mlogloss:0.09420	eval-mlogloss:0.07695
[246]	train-mlogloss:0.09375	eval-mlogloss:0.07601
[247]	train-mlogloss:0.09341	eval-mlogloss:0.07548
[248]	train-mlogloss:0.09304	eval-mlogloss:0.07518
[249]	train-mlogloss:0.09260	eval-mlogloss:0.07522
[250]	train-mlogloss:0.09247	eval-mlogloss:0.07484
[251]	train-mlogloss:0.09199	eval-mlogloss:0.07400
[252]	train-mlogloss:0.09142	eval-mlogloss:0.07294
[253]	train-mlogloss:0.09094	eval-mlogloss:0.07193
[254]	train-mlogloss:0.09089	eval-mlogloss:0.07199
[255]	train-mlogloss:0.09061	eval-mlogloss:0.07155
[256]	train-mlogloss:0.09011	eval-mlogloss:0.07076
[257]	train-mlogloss:0.09000	eval-mlogloss:0.07087
[258]	train-mlogloss:0.08962	eval-mlogloss:0.07050
[259]	train-mlogloss:0.08912	eval-mlogloss:0.06960
[260]	train-mlogloss:0.08873	eval-mlogloss:0.06922
[261]	train-mlogloss:0.08851	eval-mlogloss:0.06900
[262]	train-mlogloss:0.08838	eval-mlogloss:0.06898
[263]	train-mlogloss:0.08788	eval-mlogloss:0.06804
[264]	train-mlogloss:0.08740	eval-mlogloss:0.06766
[265]	train-mlogloss:0.08703	eval-mlogloss:0.06701
[266]	train-mlogloss:0.08666	eval-mlogloss:0.06658
[267]	train-mlogloss:0.08634	eval-mlogloss:0.06655
[268]	train-mlogloss:0.08603	eval-mlogloss:0.06582
[269]	train-mlogloss:0.08585	eval-mlogloss:0.06552
[270]	train-mlogloss:0.08566	eval-mlogloss:0.06551
[271]	train-mlogloss:0.08534	eval-mlogloss:0.06484
[272]	train-mlogloss:0.08511	eval-mlogloss:0.06467
[273]	train-mlogloss:0.08499	eval-mlogloss:0.06462
[274]	train-mlogloss:0.08466	eval-mlogloss:0.06451
[275]	train-mlogloss:0.08440	eval-mlogloss:0.06441
[276]	train-mlogloss:0.08411	eval-mlogloss:0.06394
[277]	train-mlogloss:0.08365	eval-mlogloss:0.06306
[278]	train-mlogloss:0.08339	eval-mlogloss:0.06301
[279]	train-mlogloss:0.08317	eval-mlogloss:0.06268
[280]	train-mlogloss:0.08305	eval-mlogloss:0.06254
[281]	train-mlogloss:0.08267	eval-mlogloss:0.06225
[282]	train-mlogloss:0.08251	eval-mlogloss:0.06216
[283]	train-mlogloss:0.08216	eval-mlogloss:0.06191
[284]	train-mlogloss:0.08195	eval-mlogloss:0.06148
[285]	train-mlogloss:0.08173	eval-mlogloss:0.06113
[286]	train-mlogloss:0.08150	eval-mlogloss:0.06109
[287]	train-mlogloss:0.08122	eval-mlogloss:0.06068
[288]	train-mlogloss:0.08107	eval-mlogloss:0.06045
[289]	train-mlogloss:0.08083	eval-mlogloss:0.06069
[290]	train-mlogloss:0.08048	eval-mlogloss:0.06006
[291]	train-mlogloss:0.08037	eval-mlogloss:0.06009
[292]	train-mlogloss:0.08018	eval-mlogloss:0.05993
[293]	train-mlogloss:0.07995	eval-mlogloss:0.05945
[294]	train-mlogloss:0.07974	eval-mlogloss:0.05930
[295]	train-mlogloss:0.07955	eval-mlogloss:0.05893
[296]	train-mlogloss:0.07941	eval-mlogloss:0.05853
[297]	train-mlogloss:0.07928	eval-mlogloss:0.05827
[298]	train-mlogloss:0.07916	eval-mlogloss:0.05801
[299]	train-mlogloss:0.07891	eval-mlogloss:0.05741

[I 2026-10-02 10:08:57,637] Trial 12 finished with value: 1.0 and parameters: {'lambda': 0.309842202800158, 'alpha': 0.0732983950692934, 'eta': 0.02452700698896433, 'gamma': 0.0001424405471423251, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6663668995094004, 'colsample_bytree': 0.40719576876482544}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.00200	eval-mlogloss:0.99668
[1]	train-mlogloss:0.89848	eval-mlogloss:0.88753

[I 2026-10-02 10:08:57,654] Trial 13 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03771	eval-mlogloss:1.03626
[1]	train-mlogloss:0.96664	eval-mlogloss:0.96160

[I 2026-10-02 10:08:57,675] Trial 14 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.02948	eval-mlogloss:1.02767
[1]	train-mlogloss:0.95345	eval-mlogloss:0.94699

[I 2026-10-02 10:08:57,699] Trial 15 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.95567	eval-mlogloss:0.95085
[1]	train-mlogloss:0.80994	eval-mlogloss:0.80116

[I 2026-10-02 10:08:57,729] Trial 16 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.04585	eval-mlogloss:1.04458
[1]	train-mlogloss:0.98365	eval-mlogloss:0.97898

[I 2026-10-02 10:08:57,788] Trial 17 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.02354	eval-mlogloss:1.02059
[1]	train-mlogloss:0.93677	eval-mlogloss:0.92963

[I 2026-10-02 10:08:58,068] Trial 18 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07084	eval-mlogloss:1.07371
[1]	train-mlogloss:1.03995	eval-mlogloss:1.04149
[2]	train-mlogloss:1.01083	eval-mlogloss:1.01117
[3]	train-mlogloss:0.98388	eval-mlogloss:0.98620
[4]	train-mlogloss:0.95698	eval-mlogloss:0.95923
[5]	train-mlogloss:0.93222	eval-mlogloss:0.93512
[6]	train-mlogloss:0.90798	eval-mlogloss:0.91230
[7]	train-mlogloss:0.88787	eval-mlogloss:0.89313

[I 2026-10-02 10:08:58,308] Trial 19 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.97553	eval-mlogloss:0.97074
[1]	train-mlogloss:0.86571	eval-mlogloss:0.85629

[I 2026-10-02 10:08:58,325] Trial 20 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07438	eval-mlogloss:1.07735
[1]	train-mlogloss:1.05094	eval-mlogloss:1.05321
[2]	train-mlogloss:1.03800	eval-mlogloss:1.04408
[3]	train-mlogloss:1.02529	eval-mlogloss:1.03408
[4]	train-mlogloss:1.00281	eval-mlogloss:1.01156
[5]	train-mlogloss:0.97907	eval-mlogloss:0.98666
[6]	train-mlogloss:0.96755	eval-mlogloss:0.97642
[7]	train-mlogloss:0.95401	eval-mlogloss:0.96415
[8]	train-mlogloss:0.93368	eval-mlogloss:0.94360
[9]	train-mlogloss:0.91173	eval-mlogloss:0.92068
[10]	train-mlogloss:0.89450	eval-mlogloss:0.90230
[11]	train-mlogloss:0.87707	eval-mlogloss:0.88394
[12]	train-mlogloss:0.85990	eval-mlogloss:0.86680
[13]	train-mlogloss:0.84632	eval-mlogloss:0.85447
[14]	train-mlogloss:0.82955	eval-mlogloss:0.83786
[15]	train-mlogloss:0.81338	eval-mlogloss:0.82144
[16]	train-mlogloss:0.79805	eval-mlogloss:0.80547
[17]	train-mlogloss:0.77849	eval-mlogloss:0.78462
[18]	train-mlogloss:0.76310	eval-mlogloss:0.76899
[19]	train-mlogloss:0.74786	eval-mlogloss:0.75417
[20]	train-mlogloss:0.73906	eval-mlogloss:0.74622
[21]	train-mlogloss:0.72384	eval-mlogloss:0.73141
[22]	train-mlogloss:0.71109	eval-mlogloss:0.71757
[23]	train-mlogloss:0.70451	eval-mlogloss:0.71246
[24]	train-mlogloss:0.68836	eval-mlogloss:0.69461
[25]	train-mlogloss:0.67251	eval-mlogloss:0.67757
[26]	train-mlogloss:0.66243	eval-mlogloss:0.66656
[27]	train-mlogloss:0.65614	eval-mlogloss:0.66074
[28]	train-mlogloss:0.64681	eval-mlogloss:0.65161
[29]	train-mlogloss:0.63496	eval-mlogloss:0.63958
[30]	train-mlogloss:0.62800	eval-mlogloss:0.63377
[31]	train-mlogloss:0.61744	eval-mlogloss:0.62257
[32]	train-mlogloss:0.60657	eval-mlogloss:0.61050
[33]	train-mlogloss:0.60196	eval-mlogloss:0.60624
[34]	train-mlogloss:0.58844	eval-mlogloss:0.59154
[35]	train-mlogloss:0.57906	eval-mlogloss:0.58224
[36]	train-mlogloss:0.56813	eval-mlogloss:0.56952
[37]	train-mlogloss:0.56233	eval-mlogloss:0.56578
[38]	train-mlogloss:0.55569	eval-mlogloss:0.55918
[39]	train-mlogloss:0.54985	eval-mlogloss:0.55358
[40]	train-mlogloss:0.54267	eval-mlogloss:0.54674
[41]	train-mlogloss:0.53530	eval-mlogloss:0.53966
[42]	train-mlogloss:0.52688	eval-mlogloss:0.53097
[43]	train-mlogloss:0.52001	eval-mlogloss:0.52368
[44]	train-mlogloss:0.51218	eval-mlogloss:0.51574
[45]	train-mlogloss:0.50174	eval-mlogloss:0.50378
[46]	train-mlogloss:0.49605	eval-mlogloss:0.49820
[47]	train-mlogloss:0.48792	eval-mlogloss:0.48893
[48]	train-mlogloss:0.48235	eval-mlogloss:0.48225
[49]	train-mlogloss:0.47792	eval-mlogloss:0.47835
[50]	train-mlogloss:0.47267	eval-mlogloss:0.47320
[51]	train-mlogloss:0.46564	eval-mlogloss:0.46633
[52]	train-mlogloss:0.45616	eval-mlogloss:0.45621
[53]	train-mlogloss:0.44953	eval-mlogloss:0.44892
[54]	train-mlogloss:0.44065	eval-mlogloss:0.43863
[55]	train-mlogloss:0.43385	eval-mlogloss:0.43153
[56]	train-mlogloss:0.42757	eval-mlogloss:0.42549
[57]	train-mlogloss:0.42442	eval-mlogloss:0.42314
[58]	train-mlogloss:0.42221	eval-mlogloss:0.42208
[59]	train-mlogloss:0.41399	eval-mlogloss:0.41292
[60]	train-mlogloss:0.40903	eval-mlogloss:0.40768
[61]	train-mlogloss:0.40484	eval-mlogloss:0.40372
[62]	train-mlogloss:0.39926	eval-mlogloss:0.39785
[63]	train-mlogloss:0.39574	eval-mlogloss:0.39508
[64]	train-mlogloss:0.39263	eval-mlogloss:0.39237
[65]	train-mlogloss:0.39082	eval-mlogloss:0.39139
[66]	train-mlogloss:0.38338	eval-mlogloss:0.38329
[67]	train-mlogloss:0.37955	eval-mlogloss:0.37998
[68]	train-mlogloss:0.37577	eval-mlogloss:0.37629
[69]	train-mlogloss:0.36974	eval-mlogloss:0.36935
[70]	train-mlogloss:0.36644	eval-mlogloss:0.36668
[71]	train-mlogloss:0.36076	eval-mlogloss:0.36044
[72]	train-mlogloss:0.35496	eval-mlogloss:0.35377
[73]	train-mlogloss:0.35278	eval-mlogloss:0.35208
[74]	train-mlogloss:0.34816	eval-mlogloss:0.34724
[75]	train-mlogloss:0.34603	eval-mlogloss:0.34602
[76]	train-mlogloss:0.34107	eval-mlogloss:0.34097
[77]	train-mlogloss:0.33912	eval-mlogloss:0.33912
[78]	train-mlogloss:0.33464	eval-mlogloss:0.33395
[79]	train-mlogloss:0.32938	eval-mlogloss:0.32771
[80]	train-mlogloss:0.32748	eval-mlogloss:0.32609
[81]	train-mlogloss:0.32343	eval-mlogloss:0.32224
[82]	train-mlogloss:0.32212	eval-mlogloss:0.32199
[83]	train-mlogloss:0.31665	eval-mlogloss:0.31572
[84]	train-mlogloss:0.31506	eval-mlogloss:0.31523
[85]	train-mlogloss:0.30944	eval-mlogloss:0.30849
[86]	train-mlogloss:0.30676	eval-mlogloss:0.30621
[87]	train-mlogloss:0.30275	eval-mlogloss:0.30162
[88]	train-mlogloss:0.29848	eval-mlogloss:0.29711
[89]	train-mlogloss:0.29594	eval-mlogloss:0.29475
[90]	train-mlogloss:0.29167	eval-mlogloss:0.29037
[91]	train-mlogloss:0.28961	eval-mlogloss:0.28877
[92]	train-mlogloss:0.28583	eval-mlogloss:0.28491
[93]	train-mlogloss:0.28233	eval-mlogloss:0.28141
[94]	train-mlogloss:0.28014	eval-mlogloss:0.27944
[95]	train-mlogloss:0.27618	eval-mlogloss:0.27467
[96]	train-mlogloss:0.27373	eval-mlogloss:0.27207
[97]	train-mlogloss:0.26928	eval-mlogloss:0.26695
[98]	train-mlogloss:0.26771	eval-mlogloss:0.26621
[99]	train-mlogloss:0.26418	eval-mlogloss:0.26175
[100]	train-mlogloss:0.26298	eval-mlogloss:0.26101
[101]	train-mlogloss:0.26175	eval-mlogloss:0.26051
[102]	train-mlogloss:0.25771	eval-mlogloss:0.25554
[103]	train-mlogloss:0.25456	eval-mlogloss:0.25244
[104]	train-mlogloss:0.25207	eval-mlogloss:0.24925
[105]	train-mlogloss:0.24795	eval-mlogloss:0.24422
[106]	train-mlogloss:0.24645	eval-mlogloss:0.24303
[107]	train-mlogloss:0.24446	eval-mlogloss:0.24118
[108]	train-mlogloss:0.24165	eval-mlogloss:0.23781
[109]	train-mlogloss:0.23858	eval-mlogloss:0.23453
[110]	train-mlogloss:0.23664	eval-mlogloss:0.23259
[111]	train-mlogloss:0.23469	eval-mlogloss:0.23053
[112]	train-mlogloss:0.23155	eval-mlogloss:0.22708
[113]	train-mlogloss:0.23064	eval-mlogloss:0.22666
[114]	train-mlogloss:0.22792	eval-mlogloss:0.22369
[115]	train-mlogloss:0.22446	eval-mlogloss:0.21990
[116]	train-mlogloss:0.22269	eval-mlogloss:0.21850
[117]	train-mlogloss:0.21992	eval-mlogloss:0.21554
[118]	train-mlogloss:0.21768	eval-mlogloss:0.21351
[119]	train-mlogloss:0.21488	eval-mlogloss:0.21007
[120]	train-mlogloss:0.21157	eval-mlogloss:0.20660
[121]	train-mlogloss:0.20931	eval-mlogloss:0.20418
[122]	train-mlogloss:0.20626	eval-mlogloss:0.20062
[123]	train-mlogloss:0.20438	eval-mlogloss:0.19838
[124]	train-mlogloss:0.20261	eval-mlogloss:0.19655
[125]	train-mlogloss:0.20005	eval-mlogloss:0.19376
[126]	train-mlogloss:0.19864	eval-mlogloss:0.19241
[127]	train-mlogloss:0.19663	eval-mlogloss:0.19009
[128]	train-mlogloss:0.19536	eval-mlogloss:0.18884
[129]	train-mlogloss:0.19411	eval-mlogloss:0.18790
[130]	train-mlogloss:0.19366	eval-mlogloss:0.18799
[131]	train-mlogloss:0.19267	eval-mlogloss:0.18727
[132]	train-mlogloss:0.19060	eval-mlogloss:0.18472
[133]	train-mlogloss:0.18899	eval-mlogloss:0.18273
[134]	train-mlogloss:0.18631	eval-mlogloss:0.17908
[135]	train-mlogloss:0.18549	eval-mlogloss:0.17884
[136]	train-mlogloss:0.18371	eval-mlogloss:0.17710
[137]	train-mlogloss:0.18177	eval-mlogloss:0.17428
[138]	train-mlogloss:0.17995	eval-mlogloss:0.17228
[139]	train-mlogloss:0.17745	eval-mlogloss:0.16944
[140]	train-mlogloss:0.17583	eval-mlogloss:0.16738
[141]	train-mlogloss:0.17426	eval-mlogloss:0.16557
[142]	train-mlogloss:0.17314	eval-mlogloss:0.16467
[143]	train-mlogloss:0.17145	eval-mlogloss:0.16333
[144]	train-mlogloss:0.17011	eval-mlogloss:0.16156
[145]	train-mlogloss:0.16797	eval-mlogloss:0.15891
[146]	train-mlogloss:0.16751	eval-mlogloss:0.15891
[147]	train-mlogloss:0.16594	eval-mlogloss:0.15696
[148]	train-mlogloss:0.16384	eval-mlogloss:0.15403
[149]	train-mlogloss:0.16299	eval-mlogloss:0.15356
[150]	train-mlogloss:0.16153	eval-mlogloss:0.15170
[151]	train-mlogloss:0.16109	eval-mlogloss:0.15151
[152]	train-mlogloss:0.16000	eval-mlogloss:0.15039
[153]	train-mlogloss:0.15852	eval-mlogloss:0.14859
[154]	train-mlogloss:0.15805	eval-mlogloss:0.14862
[155]	train-mlogloss:0.15671	eval-mlogloss:0.14715
[156]	train-mlogloss:0.15515	eval-mlogloss:0.14518
[157]	train-mlogloss:0.15320	eval-mlogloss:0.14249
[158]	train-mlogloss:0.15180	eval-mlogloss:0.14049
[159]	train-mlogloss:0.15028	eval-mlogloss:0.13873
[160]	train-mlogloss:0.14939	eval-mlogloss:0.13811
[161]	train-mlogloss:0.14827	eval-mlogloss:0.13680
[162]	train-mlogloss:0.14652	eval-mlogloss:0.13443
[163]	train-mlogloss:0.14547	eval-mlogloss:0.13338
[164]	train-mlogloss:0.14421	eval-mlogloss:0.13217
[165]	train-mlogloss:0.14333	eval-mlogloss:0.13121
[166]	train-mlogloss:0.14243	eval-mlogloss:0.13031
[167]	train-mlogloss:0.14155	eval-mlogloss:0.12924
[168]	train-mlogloss:0.14133	eval-mlogloss:0.12913
[169]	train-mlogloss:0.14012	eval-mlogloss:0.12785
[170]	train-mlogloss:0.13855	eval-mlogloss:0.12591
[171]	train-mlogloss:0.13745	eval-mlogloss:0.12490
[172]	train-mlogloss:0.13598	eval-mlogloss:0.12320
[173]	train-mlogloss:0.13493	eval-mlogloss:0.12212
[174]	train-mlogloss:0.13382	eval-mlogloss:0.12109
[175]	train-mlogloss:0.13312	eval-mlogloss:0.12074
[176]	train-mlogloss:0.13212	eval-mlogloss:0.11944
[177]	train-mlogloss:0.13119	eval-mlogloss:0.11826
[178]	train-mlogloss:0.12997	eval-mlogloss:0.11637
[179]	train-mlogloss:0.12907	eval-mlogloss:0.11547
[180]	train-mlogloss:0.12808	eval-mlogloss:0.11460
[181]	train-mlogloss:0.12722	eval-mlogloss:0.11355
[182]	train-mlogloss:0.12639	eval-mlogloss:0.11261
[183]	train-mlogloss:0.12554	eval-mlogloss:0.11159
[184]	train-mlogloss:0.12460	eval-mlogloss:0.11080
[185]	train-mlogloss:0.12367	eval-mlogloss:0.11000
[186]	train-mlogloss:0.12341	eval-mlogloss:0.10995
[187]	train-mlogloss:0.12258	eval-mlogloss:0.10904
[188]	train-mlogloss:0.12143	eval-mlogloss:0.10755
[189]	train-mlogloss:0.12090	eval-mlogloss:0.10702
[190]	train-mlogloss:0.12022	eval-mlogloss:0.10647
[191]	train-mlogloss:0.11939	eval-mlogloss:0.10567
[192]	train-mlogloss:0.11831	eval-mlogloss:0.10443
[193]	train-mlogloss:0.11767	eval-mlogloss:0.10373
[194]	train-mlogloss:0.11735	eval-mlogloss:0.10368
[195]	train-mlogloss:0.11677	eval-mlogloss:0.10275
[196]	train-mlogloss:0.11630	eval-mlogloss:0.10251
[197]	train-mlogloss:0.11551	eval-mlogloss:0.10186
[198]	train-mlogloss:0.11469	eval-mlogloss:0.10072
[199]	train-mlogloss:0.11396	eval-mlogloss:0.09998
[200]	train-mlogloss:0.11327	eval-mlogloss:0.09941
[201]	train-mlogloss:0.11296	eval-mlogloss:0.09936
[202]	train-mlogloss:0.11238	eval-mlogloss:0.09871
[203]	train-mlogloss:0.11196	eval-mlogloss:0.09858
[204]	train-mlogloss:0.11120	eval-mlogloss:0.09790
[205]	train-mlogloss:0.11064	eval-mlogloss:0.09730
[206]	train-mlogloss:0.11021	eval-mlogloss:0.09705
[207]	train-mlogloss:0.10959	eval-mlogloss:0.09650
[208]	train-mlogloss:0.10887	eval-mlogloss:0.09595
[209]	train-mlogloss:0.10846	eval-mlogloss:0.09579
[210]	train-mlogloss:0.10795	eval-mlogloss:0.09517
[211]	train-mlogloss:0.10765	eval-mlogloss:0.09510
[212]	train-mlogloss:0.10705	eval-mlogloss:0.09432
[213]	train-mlogloss:0.10633	eval-mlogloss:0.09315
[214]	train-mlogloss:0.10588	eval-mlogloss:0.09299
[215]	train-mlogloss:0.10507	eval-mlogloss:0.09151
[216]	train-mlogloss:0.10443	eval-mlogloss:0.09100
[217]	train-mlogloss:0.10392	eval-mlogloss:0.09018
[218]	train-mlogloss:0.10321	eval-mlogloss:0.08922
[219]	train-mlogloss:0.10239	eval-mlogloss:0.08803
[220]	train-mlogloss:0.10180	eval-mlogloss:0.08732
[221]	train-mlogloss:0.10135	eval-mlogloss:0.08693
[222]	train-mlogloss:0.10073	eval-mlogloss:0.08617
[223]	train-mlogloss:0.10059	eval-mlogloss:0.08598
[224]	train-mlogloss:0.10011	eval-mlogloss:0.08551
[225]	train-mlogloss:0.09976	eval-mlogloss:0.08526
[226]	train-mlogloss:0.09947	eval-mlogloss:0.08503
[227]	train-mlogloss:0.09871	eval-mlogloss:0.08395
[228]	train-mlogloss:0.09815	eval-mlogloss:0.08340
[229]	train-mlogloss:0.09785	eval-mlogloss:0.08317
[230]	train-mlogloss:0.09725	eval-mlogloss:0.08270
[231]	train-mlogloss:0.09694	eval-mlogloss:0.08258
[232]	train-mlogloss:0.09621	eval-mlogloss:0.08147
[233]	train-mlogloss:0.09603	eval-mlogloss:0.08144
[234]	train-mlogloss:0.09575	eval-mlogloss:0.08139
[235]	train-mlogloss:0.09511	eval-mlogloss:0.08051
[236]	train-mlogloss:0.09464	eval-mlogloss:0.08010
[237]	train-mlogloss:0.09428	eval-mlogloss:0.07955
[238]	train-mlogloss:0.09386	eval-mlogloss:0.07914
[239]	train-mlogloss:0.09338	eval-mlogloss:0.07831
[240]	train-mlogloss:0.09295	eval-mlogloss:0.07761
[241]	train-mlogloss:0.09268	eval-mlogloss:0.07752
[242]	train-mlogloss:0.09232	eval-mlogloss:0.07728
[243]	train-mlogloss:0.09197	eval-mlogloss:0.07679
[244]	train-mlogloss:0.09162	eval-mlogloss:0.07678
[245]	train-mlogloss:0.09109	eval-mlogloss:0.07615
[246]	train-mlogloss:0.09061	eval-mlogloss:0.07515
[247]	train-mlogloss:0.09027	eval-mlogloss:0.07454
[248]	train-mlogloss:0.08989	eval-mlogloss:0.07422
[249]	train-mlogloss:0.08945	eval-mlogloss:0.07423
[250]	train-mlogloss:0.08929	eval-mlogloss:0.07385
[251]	train-mlogloss:0.08875	eval-mlogloss:0.07299
[252]	train-mlogloss:0.08821	eval-mlogloss:0.07197
[253]	train-mlogloss:0.08775	eval-mlogloss:0.07087
[254]	train-mlogloss:0.08762	eval-mlogloss:0.07102
[255]	train-mlogloss:0.08728	eval-mlogloss:0.07048
[256]	train-mlogloss:0.08683	eval-mlogloss:0.06976
[257]	train-mlogloss:0.08670	eval-mlogloss:0.06973
[258]	train-mlogloss:0.08631	eval-mlogloss:0.06931
[259]	train-mlogloss:0.08580	eval-mlogloss:0.06848
[260]	train-mlogloss:0.08541	eval-mlogloss:0.06807
[261]	train-mlogloss:0.08517	eval-mlogloss:0.06782
[262]	train-mlogloss:0.08502	eval-mlogloss:0.06779
[263]	train-mlogloss:0.08451	eval-mlogloss:0.06682
[264]	train-mlogloss:0.08399	eval-mlogloss:0.06639
[265]	train-mlogloss:0.08358	eval-mlogloss:0.06565
[266]	train-mlogloss:0.08326	eval-mlogloss:0.06499
[267]	train-mlogloss:0.08285	eval-mlogloss:0.06498
[268]	train-mlogloss:0.08254	eval-mlogloss:0.06424
[269]	train-mlogloss:0.08233	eval-mlogloss:0.06394
[270]	train-mlogloss:0.08214	eval-mlogloss:0.06395
[271]	train-mlogloss:0.08186	eval-mlogloss:0.06340
[272]	train-mlogloss:0.08161	eval-mlogloss:0.06333
[273]	train-mlogloss:0.08151	eval-mlogloss:0.06324
[274]	train-mlogloss:0.08118	eval-mlogloss:0.06314
[275]	train-mlogloss:0.08090	eval-mlogloss:0.06295
[276]	train-mlogloss:0.08053	eval-mlogloss:0.06239
[277]	train-mlogloss:0.08008	eval-mlogloss:0.06163
[278]	train-mlogloss:0.07985	eval-mlogloss:0.06143
[279]	train-mlogloss:0.07958	eval-mlogloss:0.06114
[280]	train-mlogloss:0.07938	eval-mlogloss:0.06089
[281]	train-mlogloss:0.07898	eval-mlogloss:0.06061
[282]	train-mlogloss:0.07880	eval-mlogloss:0.06043
[283]	train-mlogloss:0.07843	eval-mlogloss:0.06019
[284]	train-mlogloss:0.07823	eval-mlogloss:0.05985
[285]	train-mlogloss:0.07792	eval-mlogloss:0.05942
[286]	train-mlogloss:0.07772	eval-mlogloss:0.05935
[287]	train-mlogloss:0.07737	eval-mlogloss:0.05891
[288]	train-mlogloss:0.07723	eval-mlogloss:0.05879
[289]	train-mlogloss:0.07704	eval-mlogloss:0.05902
[290]	train-mlogloss:0.07666	eval-mlogloss:0.05832
[291]	train-mlogloss:0.07655	eval-mlogloss:0.05836
[292]	train-mlogloss:0.07637	eval-mlogloss:0.05819
[293]	train-mlogloss:0.07618	eval-mlogloss:0.05784
[294]	train-mlogloss:0.07596	eval-mlogloss:0.05756
[295]	train-mlogloss:0.07575	eval-mlogloss:0.05719
[296]	train-mlogloss:0.07547	eval-mlogloss:0.05690
[297]	train-mlogloss:0.07534	eval-mlogloss:0.05660
[298]	train-mlogloss:0.07525	eval-mlogloss:0.05628
[299]	train-mlogloss:0.07505	eval-mlogloss:0.05568

[I 2026-10-02 10:08:59,457] Trial 21 finished with value: 1.0 and parameters: {'lambda': 0.04078219786498899, 'alpha': 0.07671283319314715, 'eta': 0.02337635726477124, 'gamma': 0.02426400342782148, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7144617718330325, 'colsample_bytree': 0.44062241910149225}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.05935	eval-mlogloss:1.05971
[1]	train-mlogloss:1.01904	eval-mlogloss:1.01863
[2]	train-mlogloss:0.99933	eval-mlogloss:1.00478
[3]	train-mlogloss:0.98134	eval-mlogloss:0.98684
[4]	train-mlogloss:0.94535	eval-mlogloss:0.95110
[5]	train-mlogloss:0.90790	eval-mlogloss:0.91237
[6]	train-mlogloss:0.89307	eval-mlogloss:0.89722
[7]	train-mlogloss:0.87448	eval-mlogloss:0.87712

[I 2026-10-02 10:08:59,490] Trial 22 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.04232	eval-mlogloss:1.04208
[1]	train-mlogloss:0.98883	eval-mlogloss:0.98775
[2]	train-mlogloss:0.96331	eval-mlogloss:0.96319
[3]	train-mlogloss:0.93953	eval-mlogloss:0.94325
[4]	train-mlogloss:0.89350	eval-mlogloss:0.89671
[5]	train-mlogloss:0.84559	eval-mlogloss:0.84485
[6]	train-mlogloss:0.82602	eval-mlogloss:0.82923
[7]	train-mlogloss:0.80299	eval-mlogloss:0.80513

[I 2026-10-02 10:08:59,541] Trial 23 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.00143	eval-mlogloss:0.99552
[1]	train-mlogloss:0.91611	eval-mlogloss:0.90523

[I 2026-10-02 10:08:59,662] Trial 24 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.00597	eval-mlogloss:1.00084
[1]	train-mlogloss:0.91648	eval-mlogloss:0.91015

[I 2026-10-02 10:08:59,691] Trial 25 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.02813	eval-mlogloss:1.03215
[1]	train-mlogloss:0.96480	eval-mlogloss:0.96834

[I 2026-10-02 10:08:59,716] Trial 26 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.01231	eval-mlogloss:1.00861
[1]	train-mlogloss:0.91400	eval-mlogloss:0.90471

[I 2026-10-02 10:08:59,745] Trial 27 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05805	eval-mlogloss:1.05803
[1]	train-mlogloss:1.01746	eval-mlogloss:1.01536
[2]	train-mlogloss:0.99727	eval-mlogloss:0.99933
[3]	train-mlogloss:0.97881	eval-mlogloss:0.98060
[4]	train-mlogloss:0.94214	eval-mlogloss:0.94267
[5]	train-mlogloss:0.90390	eval-mlogloss:0.90322
[6]	train-mlogloss:0.88814	eval-mlogloss:0.88792
[7]	train-mlogloss:0.86928	eval-mlogloss:0.86970

[I 2026-10-02 10:08:59,801] Trial 28 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.07763	eval-mlogloss:1.08007
[1]	train-mlogloss:1.05735	eval-mlogloss:1.05916
[2]	train-mlogloss:1.04614	eval-mlogloss:1.05151
[3]	train-mlogloss:1.03508	eval-mlogloss:1.04258
[4]	train-mlogloss:1.01581	eval-mlogloss:1.02316
[5]	train-mlogloss:0.99493	eval-mlogloss:1.00133
[6]	train-mlogloss:0.98514	eval-mlogloss:0.99214
[7]	train-mlogloss:0.97335	eval-mlogloss:0.98082
[8]	train-mlogloss:0.95557	eval-mlogloss:0.96280
[9]	train-mlogloss:0.93606	eval-mlogloss:0.94255
[10]	train-mlogloss:0.92051	eval-mlogloss:0.92625
[11]	train-mlogloss:0.90467	eval-mlogloss:0.90952
[12]	train-mlogloss:0.88924	eval-mlogloss:0.89415
[13]	train-mlogloss:0.87717	eval-mlogloss:0.88340
[14]	train-mlogloss:0.86199	eval-mlogloss:0.86847
[15]	train-mlogloss:0.84736	eval-mlogloss:0.85315
[16]	train-mlogloss:0.83343	eval-mlogloss:0.83863
[17]	train-mlogloss:0.81580	eval-mlogloss:0.81988
[18]	train-mlogloss:0.80176	eval-mlogloss:0.80562
[19]	train-mlogloss:0.78789	eval-mlogloss:0.79261
[20]	train-mlogloss:0.77966	eval-mlogloss:0.78517
[21]	train-mlogloss:0.76557	eval-mlogloss:0.77161
[22]	train-mlogloss:0.75363	eval-mlogloss:0.75901
[23]	train-mlogloss:0.74747	eval-mlogloss:0.75419
[24]	train-mlogloss:0.73239	eval-mlogloss:0.73763
[25]	train-mlogloss:0.71762	eval-mlogloss:0.72181
[26]	train-mlogloss:0.70821	eval-mlogloss:0.71137
[27]	train-mlogloss:0.70207	eval-mlogloss:0.70617
[28]	train-mlogloss:0.69320	eval-mlogloss:0.69752
[29]	train-mlogloss:0.68182	eval-mlogloss:0.68656
[30]	train-mlogloss:0.67521	eval-mlogloss:0.68097
[31]	train-mlogloss:0.66518	eval-mlogloss:0.67035
[32]	train-mlogloss:0.65487	eval-mlogloss:0.65905
[33]	train-mlogloss:0.65033	eval-mlogloss:0.65513
[34]	train-mlogloss:0.63747	eval-mlogloss:0.64132
[35]	train-mlogloss:0.62838	eval-mlogloss:0.63235
[36]	train-mlogloss:0.61797	eval-mlogloss:0.62034
[37]	train-mlogloss:0.61224	eval-mlogloss:0.61617
[38]	train-mlogloss:0.60577	eval-mlogloss:0.60968
[39]	train-mlogloss:0.60024	eval-mlogloss:0.60428
[40]	train-mlogloss:0.59330	eval-mlogloss:0.59750
[41]	train-mlogloss:0.58634	eval-mlogloss:0.59081
[42]	train-mlogloss:0.57807	eval-mlogloss:0.58222
[43]	train-mlogloss:0.57148	eval-mlogloss:0.57536
[44]	train-mlogloss:0.56372	eval-mlogloss:0.56783
[45]	train-mlogloss:0.55347	eval-mlogloss:0.55620
[46]	train-mlogloss:0.54795	eval-mlogloss:0.55078
[47]	train-mlogloss:0.54013	eval-mlogloss:0.54194
[48]	train-mlogloss:0.53441	eval-mlogloss:0.53525
[49]	train-mlogloss:0.52987	eval-mlogloss:0.53145
[50]	train-mlogloss:0.52457	eval-mlogloss:0.52627
[51]	train-mlogloss:0.51758	eval-mlogloss:0.51958
[52]	train-mlogloss:0.50815	eval-mlogloss:0.50962
[53]	train-mlogloss:0.50144	eval-mlogloss:0.50246
[54]	train-mlogloss:0.49255	eval-mlogloss:0.49233
[55]	train-mlogloss:0.48584	eval-mlogloss:0.48541
[56]	train-mlogloss:0.47948	eval-mlogloss:0.47914
[57]	train-mlogloss:0.47616	eval-mlogloss:0.47644
[58]	train-mlogloss:0.47384	eval-mlogloss:0.47515
[59]	train-mlogloss:0.46567	eval-mlogloss:0.46614
[60]	train-mlogloss:0.46056	eval-mlogloss:0.46072
[61]	train-mlogloss:0.45633	eval-mlogloss:0.45668
[62]	train-mlogloss:0.45063	eval-mlogloss:0.45065
[63]	train-mlogloss:0.44694	eval-mlogloss:0.44777
[64]	train-mlogloss:0.44355	eval-mlogloss:0.44508
[65]	train-mlogloss:0.44165	eval-mlogloss:0.44397
[66]	train-mlogloss:0.43412	eval-mlogloss:0.43585
[67]	train-mlogloss:0.43010	eval-mlogloss:0.43236
[68]	train-mlogloss:0.42633	eval-mlogloss:0.42883
[69]	train-mlogloss:0.42014	eval-mlogloss:0.42183
[70]	train-mlogloss:0.41679	eval-mlogloss:0.41894
[71]	train-mlogloss:0.41089	eval-mlogloss:0.41258
[72]	train-mlogloss:0.40489	eval-mlogloss:0.40575
[73]	train-mlogloss:0.40258	eval-mlogloss:0.40394
[74]	train-mlogloss:0.39778	eval-mlogloss:0.39900
[75]	train-mlogloss:0.39549	eval-mlogloss:0.39740
[76]	train-mlogloss:0.39025	eval-mlogloss:0.39220
[77]	train-mlogloss:0.38820	eval-mlogloss:0.39046
[78]	train-mlogloss:0.38369	eval-mlogloss:0.38545
[79]	train-mlogloss:0.37824	eval-mlogloss:0.37910
[80]	train-mlogloss:0.37626	eval-mlogloss:0.37745
[81]	train-mlogloss:0.37195	eval-mlogloss:0.37295
[82]	train-mlogloss:0.37054	eval-mlogloss:0.37262
[83]	train-mlogloss:0.36485	eval-mlogloss:0.36604
[84]	train-mlogloss:0.36321	eval-mlogloss:0.36518
[85]	train-mlogloss:0.35731	eval-mlogloss:0.35827
[86]	train-mlogloss:0.35429	eval-mlogloss:0.35583
[87]	train-mlogloss:0.35004	eval-mlogloss:0.35107
[88]	train-mlogloss:0.34551	eval-mlogloss:0.34648
[89]	train-mlogloss:0.34262	eval-mlogloss:0.34397
[90]	train-mlogloss:0.33815	eval-mlogloss:0.33920
[91]	train-mlogloss:0.33589	eval-mlogloss:0.33740
[92]	train-mlogloss:0.33175	eval-mlogloss:0.33339
[93]	train-mlogloss:0.32802	eval-mlogloss:0.32965
[94]	train-mlogloss:0.32563	eval-mlogloss:0.32711
[95]	train-mlogloss:0.32138	eval-mlogloss:0.32212
[96]	train-mlogloss:0.31877	eval-mlogloss:0.31931
[97]	train-mlogloss:0.31404	eval-mlogloss:0.31396
[98]	train-mlogloss:0.31211	eval-mlogloss:0.31298
[99]	train-mlogloss:0.30835	eval-mlogloss:0.30839
[100]	train-mlogloss:0.30691	eval-mlogloss:0.30753
[101]	train-mlogloss:0.30546	eval-mlogloss:0.30701
[102]	train-mlogloss:0.30107	eval-mlogloss:0.30172
[103]	train-mlogloss:0.29771	eval-mlogloss:0.29831
[104]	train-mlogloss:0.29506	eval-mlogloss:0.29512
[105]	train-mlogloss:0.29063	eval-mlogloss:0.28982
[106]	train-mlogloss:0.28895	eval-mlogloss:0.28868
[107]	train-mlogloss:0.28673	eval-mlogloss:0.28670
[108]	train-mlogloss:0.28352	eval-mlogloss:0.28294
[109]	train-mlogloss:0.28029	eval-mlogloss:0.27954
[110]	train-mlogloss:0.27803	eval-mlogloss:0.27728
[111]	train-mlogloss:0.27574	eval-mlogloss:0.27508
[112]	train-mlogloss:0.27233	eval-mlogloss:0.27137
[113]	train-mlogloss:0.27132	eval-mlogloss:0.27099
[114]	train-mlogloss:0.26831	eval-mlogloss:0.26772
[115]	train-mlogloss:0.26454	eval-mlogloss:0.26365
[116]	train-mlogloss:0.26262	eval-mlogloss:0.26199
[117]	train-mlogloss:0.25953	eval-mlogloss:0.25869
[118]	train-mlogloss:0.25699	eval-mlogloss:0.25639
[119]	train-mlogloss:0.25395	eval-mlogloss:0.25277
[120]	train-mlogloss:0.25036	eval-mlogloss:0.24892
[121]	train-mlogloss:0.24783	eval-mlogloss:0.24637
[122]	train-mlogloss:0.24452	eval-mlogloss:0.24262
[123]	train-mlogloss:0.24235	eval-mlogloss:0.24020
[124]	train-mlogloss:0.24036	eval-mlogloss:0.23803
[125]	train-mlogloss:0.23746	eval-mlogloss:0.23473
[126]	train-mlogloss:0.23581	eval-mlogloss:0.23305
[127]	train-mlogloss:0.23345	eval-mlogloss:0.23028
[128]	train-mlogloss:0.23194	eval-mlogloss:0.22891
[129]	train-mlogloss:0.23049	eval-mlogloss:0.22793
[130]	train-mlogloss:0.22989	eval-mlogloss:0.22802
[131]	train-mlogloss:0.22870	eval-mlogloss:0.22711
[132]	train-mlogloss:0.22635	eval-mlogloss:0.22428
[133]	train-mlogloss:0.22456	eval-mlogloss:0.22212
[134]	train-mlogloss:0.22154	eval-mlogloss:0.21817
[135]	train-mlogloss:0.22066	eval-mlogloss:0.21761
[136]	train-mlogloss:0.21869	eval-mlogloss:0.21561
[137]	train-mlogloss:0.21650	eval-mlogloss:0.21254
[138]	train-mlogloss:0.21436	eval-mlogloss:0.21021
[139]	train-mlogloss:0.21162	eval-mlogloss:0.20712
[140]	train-mlogloss:0.20970	eval-mlogloss:0.20472
[141]	train-mlogloss:0.20787	eval-mlogloss:0.20277
[142]	train-mlogloss:0.20661	eval-mlogloss:0.20166
[143]	train-mlogloss:0.20471	eval-mlogloss:0.20002
[144]	train-mlogloss:0.20321	eval-mlogloss:0.19812
[145]	train-mlogloss:0.20074	eval-mlogloss:0.19515
[146]	train-mlogloss:0.20020	eval-mlogloss:0.19493
[147]	train-mlogloss:0.19834	eval-mlogloss:0.19269
[148]	train-mlogloss:0.19593	eval-mlogloss:0.18943
[149]	train-mlogloss:0.19496	eval-mlogloss:0.18872
[150]	train-mlogloss:0.19323	eval-mlogloss:0.18673
[151]	train-mlogloss:0.19268	eval-mlogloss:0.18630
[152]	train-mlogloss:0.19145	eval-mlogloss:0.18488
[153]	train-mlogloss:0.18976	eval-mlogloss:0.18285
[154]	train-mlogloss:0.18915	eval-mlogloss:0.18277
[155]	train-mlogloss:0.18751	eval-mlogloss:0.18103
[156]	train-mlogloss:0.18563	eval-mlogloss:0.17884
[157]	train-mlogloss:0.18337	eval-mlogloss:0.17586
[158]	train-mlogloss:0.18173	eval-mlogloss:0.17358
[159]	train-mlogloss:0.17993	eval-mlogloss:0.17152
[160]	train-mlogloss:0.17891	eval-mlogloss:0.17076
[161]	train-mlogloss:0.17763	eval-mlogloss:0.16918
[162]	train-mlogloss:0.17566	eval-mlogloss:0.16660
[163]	train-mlogloss:0.17447	eval-mlogloss:0.16535
[164]	train-mlogloss:0.17300	eval-mlogloss:0.16386
[165]	train-mlogloss:0.17201	eval-mlogloss:0.16277
[166]	train-mlogloss:0.17088	eval-mlogloss:0.16157
[167]	train-mlogloss:0.16974	eval-mlogloss:0.16036
[168]	train-mlogloss:0.16943	eval-mlogloss:0.16020
[169]	train-mlogloss:0.16801	eval-mlogloss:0.15871
[170]	train-mlogloss:0.16619	eval-mlogloss:0.15626
[171]	train-mlogloss:0.16478	eval-mlogloss:0.15501
[172]	train-mlogloss:0.16305	eval-mlogloss:0.15306
[173]	train-mlogloss:0.16178	eval-mlogloss:0.15175
[174]	train-mlogloss:0.16056	eval-mlogloss:0.15049
[175]	train-mlogloss:0.15981	eval-mlogloss:0.15008
[176]	train-mlogloss:0.15857	eval-mlogloss:0.14868
[177]	train-mlogloss:0.15733	eval-mlogloss:0.14733
[178]	train-mlogloss:0.15590	eval-mlogloss:0.14527
[179]	train-mlogloss:0.15479	eval-mlogloss:0.14412
[180]	train-mlogloss:0.15365	eval-mlogloss:0.14302
[181]	train-mlogloss:0.15255	eval-mlogloss:0.14172
[182]	train-mlogloss:0.15154	eval-mlogloss:0.14066
[183]	train-mlogloss:0.15052	eval-mlogloss:0.13957
[184]	train-mlogloss:0.14936	eval-mlogloss:0.13850
[185]	train-mlogloss:0.14827	eval-mlogloss:0.13752
[186]	train-mlogloss:0.14793	eval-mlogloss:0.13738
[187]	train-mlogloss:0.14695	eval-mlogloss:0.13630
[188]	train-mlogloss:0.14547	eval-mlogloss:0.13440
[189]	train-mlogloss:0.14480	eval-mlogloss:0.13367
[190]	train-mlogloss:0.14396	eval-mlogloss:0.13303
[191]	train-mlogloss:0.14302	eval-mlogloss:0.13203
[192]	train-mlogloss:0.14169	eval-mlogloss:0.13047
[193]	train-mlogloss:0.14096	eval-mlogloss:0.12960
[194]	train-mlogloss:0.14059	eval-mlogloss:0.12952
[195]	train-mlogloss:0.13976	eval-mlogloss:0.12866
[196]	train-mlogloss:0.13913	eval-mlogloss:0.12839
[197]	train-mlogloss:0.13821	eval-mlogloss:0.12772
[198]	train-mlogloss:0.13721	eval-mlogloss:0.12642
[199]	train-mlogloss:0.13630	eval-mlogloss:0.12564
[200]	train-mlogloss:0.13536	eval-mlogloss:0.12484
[201]	train-mlogloss:0.13502	eval-mlogloss:0.12474
[202]	train-mlogloss:0.13431	eval-mlogloss:0.12397
[203]	train-mlogloss:0.13374	eval-mlogloss:0.12386
[204]	train-mlogloss:0.13287	eval-mlogloss:0.12301
[205]	train-mlogloss:0.13206	eval-mlogloss:0.12206
[206]	train-mlogloss:0.13147	eval-mlogloss:0.12147
[207]	train-mlogloss:0.13058	eval-mlogloss:0.12077
[208]	train-mlogloss:0.12973	eval-mlogloss:0.11994
[209]	train-mlogloss:0.12931	eval-mlogloss:0.11966
[210]	train-mlogloss:0.12858	eval-mlogloss:0.11883
[211]	train-mlogloss:0.12809	eval-mlogloss:0.11876
[212]	train-mlogloss:0.12726	eval-mlogloss:0.11778
[213]	train-mlogloss:0.12632	eval-mlogloss:0.11649
[214]	train-mlogloss:0.12577	eval-mlogloss:0.11608
[215]	train-mlogloss:0.12471	eval-mlogloss:0.11440
[216]	train-mlogloss:0.12397	eval-mlogloss:0.11365
[217]	train-mlogloss:0.12325	eval-mlogloss:0.11263
[218]	train-mlogloss:0.12220	eval-mlogloss:0.11128
[219]	train-mlogloss:0.12108	eval-mlogloss:0.10984
[220]	train-mlogloss:0.12040	eval-mlogloss:0.10897
[221]	train-mlogloss:0.11979	eval-mlogloss:0.10856
[222]	train-mlogloss:0.11888	eval-mlogloss:0.10741
[223]	train-mlogloss:0.11852	eval-mlogloss:0.10720
[224]	train-mlogloss:0.11785	eval-mlogloss:0.10671
[225]	train-mlogloss:0.11743	eval-mlogloss:0.10633
[226]	train-mlogloss:0.11694	eval-mlogloss:0.10596
[227]	train-mlogloss:0.11594	eval-mlogloss:0.10471
[228]	train-mlogloss:0.11517	eval-mlogloss:0.10390
[229]	train-mlogloss:0.11479	eval-mlogloss:0.10375
[230]	train-mlogloss:0.11410	eval-mlogloss:0.10309
[231]	train-mlogloss:0.11372	eval-mlogloss:0.10292
[232]	train-mlogloss:0.11275	eval-mlogloss:0.10164
[233]	train-mlogloss:0.11256	eval-mlogloss:0.10158
[234]	train-mlogloss:0.11222	eval-mlogloss:0.10148
[235]	train-mlogloss:0.11138	eval-mlogloss:0.10036
[236]	train-mlogloss:0.11078	eval-mlogloss:0.09993
[237]	train-mlogloss:0.11026	eval-mlogloss:0.09934
[238]	train-mlogloss:0.10969	eval-mlogloss:0.09884
[239]	train-mlogloss:0.10906	eval-mlogloss:0.09784
[240]	train-mlogloss:0.10853	eval-mlogloss:0.09704
[241]	train-mlogloss:0.10822	eval-mlogloss:0.09701
[242]	train-mlogloss:0.10781	eval-mlogloss:0.09669
[243]	train-mlogloss:0.10744	eval-mlogloss:0.09634
[244]	train-mlogloss:0.10706	eval-mlogloss:0.09634
[245]	train-mlogloss:0.10639	eval-mlogloss:0.09559
[246]	train-mlogloss:0.10578	eval-mlogloss:0.09465
[247]	train-mlogloss:0.10528	eval-mlogloss:0.09382
[248]	train-mlogloss:0.10476	eval-mlogloss:0.09347
[249]	train-mlogloss:0.10420	eval-mlogloss:0.09336
[250]	train-mlogloss:0.10392	eval-mlogloss:0.09283
[251]	train-mlogloss:0.10329	eval-mlogloss:0.09185
[252]	train-mlogloss:0.10256	eval-mlogloss:0.09072
[253]	train-mlogloss:0.10190	eval-mlogloss:0.08950
[254]	train-mlogloss:0.10173	eval-mlogloss:0.08964
[255]	train-mlogloss:0.10130	eval-mlogloss:0.08893
[256]	train-mlogloss:0.10073	eval-mlogloss:0.08803
[257]	train-mlogloss:0.10058	eval-mlogloss:0.08799
[258]	train-mlogloss:0.10006	eval-mlogloss:0.08736
[259]	train-mlogloss:0.09946	eval-mlogloss:0.08637
[260]	train-mlogloss:0.09905	eval-mlogloss:0.08582
[261]	train-mlogloss:0.09871	eval-mlogloss:0.08542
[262]	train-mlogloss:0.09854	eval-mlogloss:0.08540
[263]	train-mlogloss:0.09791	eval-mlogloss:0.08438
[264]	train-mlogloss:0.09726	eval-mlogloss:0.08368
[265]	train-mlogloss:0.09674	eval-mlogloss:0.08285
[266]	train-mlogloss:0.09632	eval-mlogloss:0.08219
[267]	train-mlogloss:0.09584	eval-mlogloss:0.08188
[268]	train-mlogloss:0.09541	eval-mlogloss:0.08097
[269]	train-mlogloss:0.09517	eval-mlogloss:0.08063
[270]	train-mlogloss:0.09490	eval-mlogloss:0.08056
[271]	train-mlogloss:0.09450	eval-mlogloss:0.07995
[272]	train-mlogloss:0.09422	eval-mlogloss:0.07992
[273]	train-mlogloss:0.09401	eval-mlogloss:0.07972
[274]	train-mlogloss:0.09365	eval-mlogloss:0.07963
[275]	train-mlogloss:0.09331	eval-mlogloss:0.07926
[276]	train-mlogloss:0.09277	eval-mlogloss:0.07845
[277]	train-mlogloss:0.09225	eval-mlogloss:0.07756
[278]	train-mlogloss:0.09202	eval-mlogloss:0.07737
[279]	train-mlogloss:0.09155	eval-mlogloss:0.07688
[280]	train-mlogloss:0.09130	eval-mlogloss:0.07658
[281]	train-mlogloss:0.09079	eval-mlogloss:0.07610
[282]	train-mlogloss:0.09052	eval-mlogloss:0.07587
[283]	train-mlogloss:0.09009	eval-mlogloss:0.07557
[284]	train-mlogloss:0.08980	eval-mlogloss:0.07515
[285]	train-mlogloss:0.08939	eval-mlogloss:0.07483
[286]	train-mlogloss:0.08914	eval-mlogloss:0.07471
[287]	train-mlogloss:0.08862	eval-mlogloss:0.07405
[288]	train-mlogloss:0.08829	eval-mlogloss:0.07365
[289]	train-mlogloss:0.08807	eval-mlogloss:0.07385
[290]	train-mlogloss:0.08752	eval-mlogloss:0.07300
[291]	train-mlogloss:0.08734	eval-mlogloss:0.07294
[292]	train-mlogloss:0.08707	eval-mlogloss:0.07271
[293]	train-mlogloss:0.08663	eval-mlogloss:0.07208
[294]	train-mlogloss:0.08626	eval-mlogloss:0.07168
[295]	train-mlogloss:0.08599	eval-mlogloss:0.07128
[296]	train-mlogloss:0.08560	eval-mlogloss:0.07076
[297]	train-mlogloss:0.08519	eval-mlogloss:0.07012
[298]	train-mlogloss:0.08494	eval-mlogloss:0.06964
[299]	train-mlogloss:0.08460	eval-mlogloss:0.06887

[I 2026-10-02 10:09:01,865] Trial 29 finished with value: 1.0 and parameters: {'lambda': 0.0006475170333926193, 'alpha': 0.1033043907966489, 'eta': 0.020064235719641076, 'gamma': 0.00019479213827576665, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.7526019605108932, 'colsample_bytree': 0.4428000903926535}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.00216	eval-mlogloss:1.00195
[1]	train-mlogloss:0.91470	eval-mlogloss:0.91305

[I 2026-10-02 10:09:02,349] Trial 30 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08496	eval-mlogloss:1.08695
[1]	train-mlogloss:1.07172	eval-mlogloss:1.07315
[2]	train-mlogloss:1.06435	eval-mlogloss:1.06830
[3]	train-mlogloss:1.05699	eval-mlogloss:1.06207
[4]	train-mlogloss:1.04407	eval-mlogloss:1.04900
[5]	train-mlogloss:1.03003	eval-mlogloss:1.03420
[6]	train-mlogloss:1.02342	eval-mlogloss:1.02826
[7]	train-mlogloss:1.01524	eval-mlogloss:1.02039
[8]	train-mlogloss:1.00295	eval-mlogloss:1.00795
[9]	train-mlogloss:0.98948	eval-mlogloss:0.99410
[10]	train-mlogloss:0.97860	eval-mlogloss:0.98283
[11]	train-mlogloss:0.96738	eval-mlogloss:0.97094
[12]	train-mlogloss:0.95638	eval-mlogloss:0.95990
[13]	train-mlogloss:0.94774	eval-mlogloss:0.95185
[14]	train-mlogloss:0.93667	eval-mlogloss:0.94097
[15]	train-mlogloss:0.92583	eval-mlogloss:0.92977
[16]	train-mlogloss:0.91555	eval-mlogloss:0.91921
[17]	train-mlogloss:0.90246	eval-mlogloss:0.90537
[18]	train-mlogloss:0.89198	eval-mlogloss:0.89463
[19]	train-mlogloss:0.88151	eval-mlogloss:0.88460
[20]	train-mlogloss:0.87532	eval-mlogloss:0.87905
[21]	train-mlogloss:0.86459	eval-mlogloss:0.86850
[22]	train-mlogloss:0.85533	eval-mlogloss:0.85873
[23]	train-mlogloss:0.85046	eval-mlogloss:0.85479
[24]	train-mlogloss:0.83884	eval-mlogloss:0.84223
[25]	train-mlogloss:0.82729	eval-mlogloss:0.83000
[26]	train-mlogloss:0.81979	eval-mlogloss:0.82187
[27]	train-mlogloss:0.81498	eval-mlogloss:0.81734
[28]	train-mlogloss:0.80792	eval-mlogloss:0.81045
[29]	train-mlogloss:0.79887	eval-mlogloss:0.80142
[30]	train-mlogloss:0.79348	eval-mlogloss:0.79673
[31]	train-mlogloss:0.78534	eval-mlogloss:0.78810
[32]	train-mlogloss:0.77692	eval-mlogloss:0.77905
[33]	train-mlogloss:0.77315	eval-mlogloss:0.77570
[34]	train-mlogloss:0.76263	eval-mlogloss:0.76451
[35]	train-mlogloss:0.75494	eval-mlogloss:0.75681
[36]	train-mlogloss:0.74632	eval-mlogloss:0.74691
[37]	train-mlogloss:0.74149	eval-mlogloss:0.74309
[38]	train-mlogloss:0.73593	eval-mlogloss:0.73752
[39]	train-mlogloss:0.73116	eval-mlogloss:0.73274
[40]	train-mlogloss:0.72517	eval-mlogloss:0.72683
[41]	train-mlogloss:0.71932	eval-mlogloss:0.72126
[42]	train-mlogloss:0.71223	eval-mlogloss:0.71390
[43]	train-mlogloss:0.70656	eval-mlogloss:0.70800
[44]	train-mlogloss:0.69989	eval-mlogloss:0.70146
[45]	train-mlogloss:0.69098	eval-mlogloss:0.69166
[46]	train-mlogloss:0.68610	eval-mlogloss:0.68709
[47]	train-mlogloss:0.67919	eval-mlogloss:0.67950
[48]	train-mlogloss:0.67395	eval-mlogloss:0.67369
[49]	train-mlogloss:0.66987	eval-mlogloss:0.67012
[50]	train-mlogloss:0.66507	eval-mlogloss:0.66519
[51]	train-mlogloss:0.65887	eval-mlogloss:0.65929
[52]	train-mlogloss:0.65047	eval-mlogloss:0.65037
[53]	train-mlogloss:0.64431	eval-mlogloss:0.64373
[54]	train-mlogloss:0.63621	eval-mlogloss:0.63474
[55]	train-mlogloss:0.62998	eval-mlogloss:0.62835
[56]	train-mlogloss:0.62416	eval-mlogloss:0.62237
[57]	train-mlogloss:0.62103	eval-mlogloss:0.61943
[58]	train-mlogloss:0.61888	eval-mlogloss:0.61809
[59]	train-mlogloss:0.61133	eval-mlogloss:0.60978
[60]	train-mlogloss:0.60646	eval-mlogloss:0.60492
[61]	train-mlogloss:0.60257	eval-mlogloss:0.60133
[62]	train-mlogloss:0.59706	eval-mlogloss:0.59567
[63]	train-mlogloss:0.59354	eval-mlogloss:0.59258
[64]	train-mlogloss:0.59022	eval-mlogloss:0.58968
[65]	train-mlogloss:0.58832	eval-mlogloss:0.58843
[66]	train-mlogloss:0.58114	eval-mlogloss:0.58075
[67]	train-mlogloss:0.57727	eval-mlogloss:0.57735
[68]	train-mlogloss:0.57357	eval-mlogloss:0.57424
[69]	train-mlogloss:0.56762	eval-mlogloss:0.56754
[70]	train-mlogloss:0.56424	eval-mlogloss:0.56462
[71]	train-mlogloss:0.55854	eval-mlogloss:0.55819
[72]	train-mlogloss:0.55269	eval-mlogloss:0.55181
[73]	train-mlogloss:0.55033	eval-mlogloss:0.54955
[74]	train-mlogloss:0.54550	eval-mlogloss:0.54454
[75]	train-mlogloss:0.54329	eval-mlogloss:0.54275
[76]	train-mlogloss:0.53804	eval-mlogloss:0.53726
[77]	train-mlogloss:0.53601	eval-mlogloss:0.53517
[78]	train-mlogloss:0.53140	eval-mlogloss:0.53032
[79]	train-mlogloss:0.52593	eval-mlogloss:0.52413
[80]	train-mlogloss:0.52378	eval-mlogloss:0.52227
[81]	train-mlogloss:0.51930	eval-mlogloss:0.51763
[82]	train-mlogloss:0.51789	eval-mlogloss:0.51684
[83]	train-mlogloss:0.51206	eval-mlogloss:0.51034
[84]	train-mlogloss:0.51019	eval-mlogloss:0.50895
[85]	train-mlogloss:0.50416	eval-mlogloss:0.50222
[86]	train-mlogloss:0.50094	eval-mlogloss:0.49927
[87]	train-mlogloss:0.49657	eval-mlogloss:0.49465
[88]	train-mlogloss:0.49183	eval-mlogloss:0.48982
[89]	train-mlogloss:0.48872	eval-mlogloss:0.48656
[90]	train-mlogloss:0.48398	eval-mlogloss:0.48160
[91]	train-mlogloss:0.48146	eval-mlogloss:0.47959
[92]	train-mlogloss:0.47704	eval-mlogloss:0.47478
[93]	train-mlogloss:0.47307	eval-mlogloss:0.47051
[94]	train-mlogloss:0.47049	eval-mlogloss:0.46784
[95]	train-mlogloss:0.46592	eval-mlogloss:0.46265
[96]	train-mlogloss:0.46300	eval-mlogloss:0.45957
[97]	train-mlogloss:0.45786	eval-mlogloss:0.45384
[98]	train-mlogloss:0.45573	eval-mlogloss:0.45227
[99]	train-mlogloss:0.45167	eval-mlogloss:0.44763
[100]	train-mlogloss:0.44999	eval-mlogloss:0.44593
[101]	train-mlogloss:0.44835	eval-mlogloss:0.44473
[102]	train-mlogloss:0.44354	eval-mlogloss:0.43921
[103]	train-mlogloss:0.44007	eval-mlogloss:0.43570
[104]	train-mlogloss:0.43706	eval-mlogloss:0.43233
[105]	train-mlogloss:0.43213	eval-mlogloss:0.42681
[106]	train-mlogloss:0.43014	eval-mlogloss:0.42528
[107]	train-mlogloss:0.42764	eval-mlogloss:0.42291
[108]	train-mlogloss:0.42403	eval-mlogloss:0.41885
[109]	train-mlogloss:0.42041	eval-mlogloss:0.41485
[110]	train-mlogloss:0.41780	eval-mlogloss:0.41218
[111]	train-mlogloss:0.41519	eval-mlogloss:0.40941
[112]	train-mlogloss:0.41134	eval-mlogloss:0.40527
[113]	train-mlogloss:0.41018	eval-mlogloss:0.40457
[114]	train-mlogloss:0.40678	eval-mlogloss:0.40080
[115]	train-mlogloss:0.40245	eval-mlogloss:0.39605
[116]	train-mlogloss:0.40009	eval-mlogloss:0.39365
[117]	train-mlogloss:0.39664	eval-mlogloss:0.38987
[118]	train-mlogloss:0.39359	eval-mlogloss:0.38695
[119]	train-mlogloss:0.39001	eval-mlogloss:0.38295
[120]	train-mlogloss:0.38592	eval-mlogloss:0.37860
[121]	train-mlogloss:0.38280	eval-mlogloss:0.37540
[122]	train-mlogloss:0.37885	eval-mlogloss:0.37098
[123]	train-mlogloss:0.37623	eval-mlogloss:0.36815
[124]	train-mlogloss:0.37375	eval-mlogloss:0.36521
[125]	train-mlogloss:0.37032	eval-mlogloss:0.36156
[126]	train-mlogloss:0.36841	eval-mlogloss:0.35947
[127]	train-mlogloss:0.36555	eval-mlogloss:0.35622
[128]	train-mlogloss:0.36358	eval-mlogloss:0.35429
[129]	train-mlogloss:0.36162	eval-mlogloss:0.35253
[130]	train-mlogloss:0.36086	eval-mlogloss:0.35224
[131]	train-mlogloss:0.35941	eval-mlogloss:0.35065
[132]	train-mlogloss:0.35656	eval-mlogloss:0.34752
[133]	train-mlogloss:0.35431	eval-mlogloss:0.34507
[134]	train-mlogloss:0.35064	eval-mlogloss:0.34081
[135]	train-mlogloss:0.34958	eval-mlogloss:0.33993
[136]	train-mlogloss:0.34717	eval-mlogloss:0.33737
[137]	train-mlogloss:0.34441	eval-mlogloss:0.33395
[138]	train-mlogloss:0.34173	eval-mlogloss:0.33103
[139]	train-mlogloss:0.33830	eval-mlogloss:0.32730
[140]	train-mlogloss:0.33579	eval-mlogloss:0.32434
[141]	train-mlogloss:0.33357	eval-mlogloss:0.32190
[142]	train-mlogloss:0.33179	eval-mlogloss:0.32027
[143]	train-mlogloss:0.32937	eval-mlogloss:0.31795
[144]	train-mlogloss:0.32750	eval-mlogloss:0.31576
[145]	train-mlogloss:0.32428	eval-mlogloss:0.31204
[146]	train-mlogloss:0.32366	eval-mlogloss:0.31153
[147]	train-mlogloss:0.32128	eval-mlogloss:0.30875
[148]	train-mlogloss:0.31813	eval-mlogloss:0.30498
[149]	train-mlogloss:0.31687	eval-mlogloss:0.30396
[150]	train-mlogloss:0.31460	eval-mlogloss:0.30134
[151]	train-mlogloss:0.31378	eval-mlogloss:0.30062
[152]	train-mlogloss:0.31220	eval-mlogloss:0.29875
[153]	train-mlogloss:0.30994	eval-mlogloss:0.29624
[154]	train-mlogloss:0.30901	eval-mlogloss:0.29566
[155]	train-mlogloss:0.30683	eval-mlogloss:0.29310
[156]	train-mlogloss:0.30434	eval-mlogloss:0.29016
[157]	train-mlogloss:0.30141	eval-mlogloss:0.28667
[158]	train-mlogloss:0.29921	eval-mlogloss:0.28396
[159]	train-mlogloss:0.29684	eval-mlogloss:0.28137
[160]	train-mlogloss:0.29561	eval-mlogloss:0.28027
[161]	train-mlogloss:0.29377	eval-mlogloss:0.27818
[162]	train-mlogloss:0.29103	eval-mlogloss:0.27495
[163]	train-mlogloss:0.28950	eval-mlogloss:0.27319
[164]	train-mlogloss:0.28758	eval-mlogloss:0.27125
[165]	train-mlogloss:0.28623	eval-mlogloss:0.26966
[166]	train-mlogloss:0.28449	eval-mlogloss:0.26804
[167]	train-mlogloss:0.28288	eval-mlogloss:0.26618
[168]	train-mlogloss:0.28242	eval-mlogloss:0.26582
[169]	train-mlogloss:0.28045	eval-mlogloss:0.26377
[170]	train-mlogloss:0.27792	eval-mlogloss:0.26065
[171]	train-mlogloss:0.27601	eval-mlogloss:0.25852
[172]	train-mlogloss:0.27356	eval-mlogloss:0.25585
[173]	train-mlogloss:0.27170	eval-mlogloss:0.25380
[174]	train-mlogloss:0.27000	eval-mlogloss:0.25195
[175]	train-mlogloss:0.26894	eval-mlogloss:0.25116
[176]	train-mlogloss:0.26731	eval-mlogloss:0.24916
[177]	train-mlogloss:0.26547	eval-mlogloss:0.24721
[178]	train-mlogloss:0.26343	eval-mlogloss:0.24468
[179]	train-mlogloss:0.26171	eval-mlogloss:0.24288
[180]	train-mlogloss:0.26006	eval-mlogloss:0.24106
[181]	train-mlogloss:0.25849	eval-mlogloss:0.23926
[182]	train-mlogloss:0.25700	eval-mlogloss:0.23760
[183]	train-mlogloss:0.25549	eval-mlogloss:0.23598
[184]	train-mlogloss:0.25389	eval-mlogloss:0.23421
[185]	train-mlogloss:0.25243	eval-mlogloss:0.23262
[186]	train-mlogloss:0.25188	eval-mlogloss:0.23211
[187]	train-mlogloss:0.25044	eval-mlogloss:0.23044
[188]	train-mlogloss:0.24827	eval-mlogloss:0.22785
[189]	train-mlogloss:0.24728	eval-mlogloss:0.22681
[190]	train-mlogloss:0.24615	eval-mlogloss:0.22546
[191]	train-mlogloss:0.24473	eval-mlogloss:0.22385
[192]	train-mlogloss:0.24272	eval-mlogloss:0.22158
[193]	train-mlogloss:0.24167	eval-mlogloss:0.22040
[194]	train-mlogloss:0.24115	eval-mlogloss:0.21999
[195]	train-mlogloss:0.23998	eval-mlogloss:0.21861
[196]	train-mlogloss:0.23899	eval-mlogloss:0.21788
[197]	train-mlogloss:0.23762	eval-mlogloss:0.21653
[198]	train-mlogloss:0.23604	eval-mlogloss:0.21456
[199]	train-mlogloss:0.23467	eval-mlogloss:0.21303
[200]	train-mlogloss:0.23322	eval-mlogloss:0.21152
[201]	train-mlogloss:0.23278	eval-mlogloss:0.21112
[202]	train-mlogloss:0.23166	eval-mlogloss:0.20993
[203]	train-mlogloss:0.23075	eval-mlogloss:0.20917
[204]	train-mlogloss:0.22946	eval-mlogloss:0.20784
[205]	train-mlogloss:0.22820	eval-mlogloss:0.20649
[206]	train-mlogloss:0.22720	eval-mlogloss:0.20561
[207]	train-mlogloss:0.22580	eval-mlogloss:0.20433
[208]	train-mlogloss:0.22456	eval-mlogloss:0.20301
[209]	train-mlogloss:0.22383	eval-mlogloss:0.20224
[210]	train-mlogloss:0.22268	eval-mlogloss:0.20094
[211]	train-mlogloss:0.22187	eval-mlogloss:0.20029
[212]	train-mlogloss:0.22063	eval-mlogloss:0.19886
[213]	train-mlogloss:0.21917	eval-mlogloss:0.19711
[214]	train-mlogloss:0.21840	eval-mlogloss:0.19634
[215]	train-mlogloss:0.21665	eval-mlogloss:0.19411
[216]	train-mlogloss:0.21547	eval-mlogloss:0.19279
[217]	train-mlogloss:0.21426	eval-mlogloss:0.19131
[218]	train-mlogloss:0.21259	eval-mlogloss:0.18939
[219]	train-mlogloss:0.21089	eval-mlogloss:0.18729
[220]	train-mlogloss:0.20973	eval-mlogloss:0.18599
[221]	train-mlogloss:0.20878	eval-mlogloss:0.18509
[222]	train-mlogloss:0.20735	eval-mlogloss:0.18338
[223]	train-mlogloss:0.20681	eval-mlogloss:0.18284
[224]	train-mlogloss:0.20575	eval-mlogloss:0.18189
[225]	train-mlogloss:0.20507	eval-mlogloss:0.18125
[226]	train-mlogloss:0.20439	eval-mlogloss:0.18061
[227]	train-mlogloss:0.20280	eval-mlogloss:0.17869
[228]	train-mlogloss:0.20162	eval-mlogloss:0.17736
[229]	train-mlogloss:0.20100	eval-mlogloss:0.17685
[230]	train-mlogloss:0.19995	eval-mlogloss:0.17560
[231]	train-mlogloss:0.19925	eval-mlogloss:0.17503
[232]	train-mlogloss:0.19770	eval-mlogloss:0.17322
[233]	train-mlogloss:0.19730	eval-mlogloss:0.17287
[234]	train-mlogloss:0.19662	eval-mlogloss:0.17248
[235]	train-mlogloss:0.19522	eval-mlogloss:0.17090
[236]	train-mlogloss:0.19416	eval-mlogloss:0.16981
[237]	train-mlogloss:0.19343	eval-mlogloss:0.16901
[238]	train-mlogloss:0.19262	eval-mlogloss:0.16814
[239]	train-mlogloss:0.19157	eval-mlogloss:0.16675
[240]	train-mlogloss:0.19076	eval-mlogloss:0.16567
[241]	train-mlogloss:0.19042	eval-mlogloss:0.16533
[242]	train-mlogloss:0.18981	eval-mlogloss:0.16474
[243]	train-mlogloss:0.18916	eval-mlogloss:0.16404
[244]	train-mlogloss:0.18878	eval-mlogloss:0.16377
[245]	train-mlogloss:0.18758	eval-mlogloss:0.16243
[246]	train-mlogloss:0.18659	eval-mlogloss:0.16107
[247]	train-mlogloss:0.18561	eval-mlogloss:0.15990
[248]	train-mlogloss:0.18464	eval-mlogloss:0.15902
[249]	train-mlogloss:0.18371	eval-mlogloss:0.15818
[250]	train-mlogloss:0.18298	eval-mlogloss:0.15720
[251]	train-mlogloss:0.18196	eval-mlogloss:0.15590
[252]	train-mlogloss:0.18072	eval-mlogloss:0.15433
[253]	train-mlogloss:0.17961	eval-mlogloss:0.15268
[254]	train-mlogloss:0.17938	eval-mlogloss:0.15247
[255]	train-mlogloss:0.17847	eval-mlogloss:0.15132
[256]	train-mlogloss:0.17739	eval-mlogloss:0.14996
[257]	train-mlogloss:0.17719	eval-mlogloss:0.14973
[258]	train-mlogloss:0.17632	eval-mlogloss:0.14874
[259]	train-mlogloss:0.17513	eval-mlogloss:0.14718
[260]	train-mlogloss:0.17441	eval-mlogloss:0.14637
[261]	train-mlogloss:0.17369	eval-mlogloss:0.14557
[262]	train-mlogloss:0.17348	eval-mlogloss:0.14533
[263]	train-mlogloss:0.17233	eval-mlogloss:0.14378
[264]	train-mlogloss:0.17121	eval-mlogloss:0.14254
[265]	train-mlogloss:0.17021	eval-mlogloss:0.14133
[266]	train-mlogloss:0.16935	eval-mlogloss:0.14038
[267]	train-mlogloss:0.16865	eval-mlogloss:0.13981
[268]	train-mlogloss:0.16779	eval-mlogloss:0.13856
[269]	train-mlogloss:0.16730	eval-mlogloss:0.13796
[270]	train-mlogloss:0.16684	eval-mlogloss:0.13747
[271]	train-mlogloss:0.16608	eval-mlogloss:0.13649
[272]	train-mlogloss:0.16567	eval-mlogloss:0.13620
[273]	train-mlogloss:0.16513	eval-mlogloss:0.13577
[274]	train-mlogloss:0.16463	eval-mlogloss:0.13542
[275]	train-mlogloss:0.16389	eval-mlogloss:0.13463
[276]	train-mlogloss:0.16286	eval-mlogloss:0.13334
[277]	train-mlogloss:0.16178	eval-mlogloss:0.13194
[278]	train-mlogloss:0.16140	eval-mlogloss:0.13179
[279]	train-mlogloss:0.16059	eval-mlogloss:0.13097
[280]	train-mlogloss:0.16016	eval-mlogloss:0.13045
[281]	train-mlogloss:0.15915	eval-mlogloss:0.12948
[282]	train-mlogloss:0.15872	eval-mlogloss:0.12897
[283]	train-mlogloss:0.15798	eval-mlogloss:0.12834
[284]	train-mlogloss:0.15744	eval-mlogloss:0.12776
[285]	train-mlogloss:0.15651	eval-mlogloss:0.12681
[286]	train-mlogloss:0.15615	eval-mlogloss:0.12651
[287]	train-mlogloss:0.15521	eval-mlogloss:0.12532
[288]	train-mlogloss:0.15452	eval-mlogloss:0.12452
[289]	train-mlogloss:0.15438	eval-mlogloss:0.12450
[290]	train-mlogloss:0.15332	eval-mlogloss:0.12320
[291]	train-mlogloss:0.15299	eval-mlogloss:0.12306
[292]	train-mlogloss:0.15254	eval-mlogloss:0.12257
[293]	train-mlogloss:0.15161	eval-mlogloss:0.12144
[294]	train-mlogloss:0.15090	eval-mlogloss:0.12069
[295]	train-mlogloss:0.15043	eval-mlogloss:0.12001
[296]	train-mlogloss:0.14950	eval-mlogloss:0.11903
[297]	train-mlogloss:0.14859	eval-mlogloss:0.11794
[298]	train-mlogloss:0.14795	eval-mlogloss:0.11719
[299]	train-mlogloss:0.14721	eval-mlogloss:0.11612

[I 2026-10-02 10:09:05,072] Trial 31 finished with value: 1.0 and parameters: {'lambda': 0.09770179069382987, 'alpha': 0.004896587334437903, 'eta': 0.013001556831661999, 'gamma': 0.22629269491064577, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7525378934472486, 'colsample_bytree': 0.4478013032131119}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.06429	eval-mlogloss:1.06376
[1]	train-mlogloss:1.03031	eval-mlogloss:1.02851
[2]	train-mlogloss:1.01223	eval-mlogloss:1.01180
[3]	train-mlogloss:0.99600	eval-mlogloss:0.99555
[4]	train-mlogloss:0.96305	eval-mlogloss:0.96240
[5]	train-mlogloss:0.92816	eval-mlogloss:0.92674
[6]	train-mlogloss:0.91465	eval-mlogloss:0.91231
[7]	train-mlogloss:0.89739	eval-mlogloss:0.89604

[I 2026-10-02 10:09:05,247] Trial 32 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.08445	eval-mlogloss:1.08548
[1]	train-mlogloss:1.06771	eval-mlogloss:1.06784
[2]	train-mlogloss:1.05131	eval-mlogloss:1.05021
[3]	train-mlogloss:1.03701	eval-mlogloss:1.03579
[4]	train-mlogloss:1.02115	eval-mlogloss:1.01930
[5]	train-mlogloss:1.00715	eval-mlogloss:1.00562
[6]	train-mlogloss:0.99362	eval-mlogloss:0.99227
[7]	train-mlogloss:0.98323	eval-mlogloss:0.98159
[8]	train-mlogloss:0.97009	eval-mlogloss:0.96774
[9]	train-mlogloss:0.95598	eval-mlogloss:0.95304
[10]	train-mlogloss:0.94204	eval-mlogloss:0.93804
[11]	train-mlogloss:0.92872	eval-mlogloss:0.92342
[12]	train-mlogloss:0.91760	eval-mlogloss:0.91190
[13]	train-mlogloss:0.90689	eval-mlogloss:0.90047
[14]	train-mlogloss:0.89398	eval-mlogloss:0.88720
[15]	train-mlogloss:0.88132	eval-mlogloss:0.87347
[16]	train-mlogloss:0.86899	eval-mlogloss:0.85994
[17]	train-mlogloss:0.85691	eval-mlogloss:0.84714
[18]	train-mlogloss:0.84474	eval-mlogloss:0.83433
[19]	train-mlogloss:0.83489	eval-mlogloss:0.82446
[20]	train-mlogloss:0.82370	eval-mlogloss:0.81305
[21]	train-mlogloss:0.81258	eval-mlogloss:0.80122
[22]	train-mlogloss:0.80388	eval-mlogloss:0.79188
[23]	train-mlogloss:0.79307	eval-mlogloss:0.78111
[24]	train-mlogloss:0.78265	eval-mlogloss:0.76970
[25]	train-mlogloss:0.77194	eval-mlogloss:0.75878
[26]	train-mlogloss:0.76167	eval-mlogloss:0.74769
[27]	train-mlogloss:0.75134	eval-mlogloss:0.73710
[28]	train-mlogloss:0.74170	eval-mlogloss:0.72669
[29]	train-mlogloss:0.73217	eval-mlogloss:0.71681
[30]	train-mlogloss:0.72429	eval-mlogloss:0.70848
[31]	train-mlogloss:0.71489	eval-mlogloss:0.69838

[I 2026-10-02 10:09:06,312] Trial 33 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.06398	eval-mlogloss:1.06635
[1]	train-mlogloss:1.03069	eval-mlogloss:1.03255
[2]	train-mlogloss:1.01237	eval-mlogloss:1.01965
[3]	train-mlogloss:0.99490	eval-mlogloss:1.00639
[4]	train-mlogloss:0.96319	eval-mlogloss:0.97446
[5]	train-mlogloss:0.92975	eval-mlogloss:0.93963
[6]	train-mlogloss:0.91416	eval-mlogloss:0.92667
[7]	train-mlogloss:0.89631	eval-mlogloss:0.91029

[I 2026-10-02 10:09:06,433] Trial 34 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.03062	eval-mlogloss:1.03235
[1]	train-mlogloss:0.96757	eval-mlogloss:0.96804

[I 2026-10-02 10:09:07,381] Trial 35 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07867	eval-mlogloss:1.08046
[1]	train-mlogloss:1.05898	eval-mlogloss:1.05974
[2]	train-mlogloss:1.04843	eval-mlogloss:1.05167
[3]	train-mlogloss:1.03793	eval-mlogloss:1.04254
[4]	train-mlogloss:1.01937	eval-mlogloss:1.02378
[5]	train-mlogloss:0.99897	eval-mlogloss:1.00283
[6]	train-mlogloss:0.98971	eval-mlogloss:0.99430
[7]	train-mlogloss:0.97877	eval-mlogloss:0.98316
[8]	train-mlogloss:0.96138	eval-mlogloss:0.96510
[9]	train-mlogloss:0.94261	eval-mlogloss:0.94565
[10]	train-mlogloss:0.92773	eval-mlogloss:0.93024
[11]	train-mlogloss:0.91252	eval-mlogloss:0.91437
[12]	train-mlogloss:0.89734	eval-mlogloss:0.89927
[13]	train-mlogloss:0.88574	eval-mlogloss:0.88793
[14]	train-mlogloss:0.87101	eval-mlogloss:0.87351
[15]	train-mlogloss:0.85681	eval-mlogloss:0.85865
[16]	train-mlogloss:0.84309	eval-mlogloss:0.84446
[17]	train-mlogloss:0.82588	eval-mlogloss:0.82661
[18]	train-mlogloss:0.81223	eval-mlogloss:0.81271
[19]	train-mlogloss:0.79837	eval-mlogloss:0.79884
[20]	train-mlogloss:0.79047	eval-mlogloss:0.79205
[21]	train-mlogloss:0.77689	eval-mlogloss:0.77819
[22]	train-mlogloss:0.76538	eval-mlogloss:0.76572
[23]	train-mlogloss:0.75945	eval-mlogloss:0.76163
[24]	train-mlogloss:0.74467	eval-mlogloss:0.74555
[25]	train-mlogloss:0.72999	eval-mlogloss:0.72992
[26]	train-mlogloss:0.72066	eval-mlogloss:0.71982
[27]	train-mlogloss:0.71492	eval-mlogloss:0.71462
[28]	train-mlogloss:0.70618	eval-mlogloss:0.70600
[29]	train-mlogloss:0.69517	eval-mlogloss:0.69520
[30]	train-mlogloss:0.68886	eval-mlogloss:0.68979
[31]	train-mlogloss:0.67904	eval-mlogloss:0.67934

[I 2026-10-02 10:09:08,645] Trial 36 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.04749	eval-mlogloss:1.04804
[1]	train-mlogloss:0.99003	eval-mlogloss:0.98800

[I 2026-10-02 10:09:08,792] Trial 37 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08460	eval-mlogloss:1.08571
[1]	train-mlogloss:1.06858	eval-mlogloss:1.06882
[2]	train-mlogloss:1.05274	eval-mlogloss:1.05205
[3]	train-mlogloss:1.03868	eval-mlogloss:1.03737
[4]	train-mlogloss:1.02358	eval-mlogloss:1.02148
[5]	train-mlogloss:1.00976	eval-mlogloss:1.00694
[6]	train-mlogloss:0.99589	eval-mlogloss:0.99265
[7]	train-mlogloss:0.98495	eval-mlogloss:0.98220
[8]	train-mlogloss:0.97168	eval-mlogloss:0.96793
[9]	train-mlogloss:0.95810	eval-mlogloss:0.95378
[10]	train-mlogloss:0.94468	eval-mlogloss:0.93947
[11]	train-mlogloss:0.93163	eval-mlogloss:0.92578
[12]	train-mlogloss:0.92038	eval-mlogloss:0.91410
[13]	train-mlogloss:0.90979	eval-mlogloss:0.90285
[14]	train-mlogloss:0.89723	eval-mlogloss:0.88967
[15]	train-mlogloss:0.88487	eval-mlogloss:0.87661
[16]	train-mlogloss:0.87303	eval-mlogloss:0.86374
[17]	train-mlogloss:0.86108	eval-mlogloss:0.85107
[18]	train-mlogloss:0.84936	eval-mlogloss:0.83858
[19]	train-mlogloss:0.83964	eval-mlogloss:0.82908
[20]	train-mlogloss:0.82840	eval-mlogloss:0.81825
[21]	train-mlogloss:0.81743	eval-mlogloss:0.80670
[22]	train-mlogloss:0.80860	eval-mlogloss:0.79772
[23]	train-mlogloss:0.79813	eval-mlogloss:0.78700
[24]	train-mlogloss:0.78783	eval-mlogloss:0.77589
[25]	train-mlogloss:0.77748	eval-mlogloss:0.76526
[26]	train-mlogloss:0.76742	eval-mlogloss:0.75450
[27]	train-mlogloss:0.75740	eval-mlogloss:0.74406
[28]	train-mlogloss:0.74789	eval-mlogloss:0.73398
[29]	train-mlogloss:0.73855	eval-mlogloss:0.72407
[30]	train-mlogloss:0.73043	eval-mlogloss:0.71690
[31]	train-mlogloss:0.72105	eval-mlogloss:0.70734
[32]	train-mlogloss:0.71168	eval-mlogloss:0.69754
[33]	train-mlogloss:0.70527	eval-mlogloss:0.69202
[34]	train-mlogloss:0.69622	eval-mlogloss:0.68231
[35]	train-mlogloss:0.68767	eval-mlogloss:0.67324
[36]	train-mlogloss:0.67922	eval-mlogloss:0.66410
[37]	train-mlogloss:0.67131	eval-mlogloss:0.65559
[38]	train-mlogloss:0.66429	eval-mlogloss:0.64897
[39]	train-mlogloss:0.65597	eval-mlogloss:0.64015
[40]	train-mlogloss:0.64878	eval-mlogloss:0.63278
[41]	train-mlogloss:0.64219	eval-mlogloss:0.62618
[42]	train-mlogloss:0.63559	eval-mlogloss:0.61946
[43]	train-mlogloss:0.62801	eval-mlogloss:0.61131
[44]	train-mlogloss:0.62126	eval-mlogloss:0.60494
[45]	train-mlogloss:0.61402	eval-mlogloss:0.59699
[46]	train-mlogloss:0.60724	eval-mlogloss:0.58954
[47]	train-mlogloss:0.59998	eval-mlogloss:0.58169
[48]	train-mlogloss:0.59309	eval-mlogloss:0.57474
[49]	train-mlogloss:0.58631	eval-mlogloss:0.56742
[50]	train-mlogloss:0.58050	eval-mlogloss:0.56172
[51]	train-mlogloss:0.57372	eval-mlogloss:0.55446
[52]	train-mlogloss:0.56700	eval-mlogloss:0.54744
[53]	train-mlogloss:0.56128	eval-mlogloss:0.54192
[54]	train-mlogloss:0.55471	eval-mlogloss:0.53480
[55]	train-mlogloss:0.54825	eval-mlogloss:0.52790
[56]	train-mlogloss:0.54211	eval-mlogloss:0.52142
[57]	train-mlogloss:0.53719	eval-mlogloss:0.51668
[58]	train-mlogloss:0.53213	eval-mlogloss:0.51177
[59]	train-mlogloss:0.52615	eval-mlogloss:0.50537
[60]	train-mlogloss:0.52051	eval-mlogloss:0.49952
[61]	train-mlogloss:0.51472	eval-mlogloss:0.49355
[62]	train-mlogloss:0.50895	eval-mlogloss:0.48746
[63]	train-mlogloss:0.50328	eval-mlogloss:0.48137
[64]	train-mlogloss:0.49791	eval-mlogloss:0.47594
[65]	train-mlogloss:0.49442	eval-mlogloss:0.47315
[66]	train-mlogloss:0.48890	eval-mlogloss:0.46743
[67]	train-mlogloss:0.48314	eval-mlogloss:0.46119
[68]	train-mlogloss:0.47896	eval-mlogloss:0.45715
[69]	train-mlogloss:0.47380	eval-mlogloss:0.45186
[70]	train-mlogloss:0.47048	eval-mlogloss:0.44895
[71]	train-mlogloss:0.46558	eval-mlogloss:0.44366
[72]	train-mlogloss:0.46060	eval-mlogloss:0.43832
[73]	train-mlogloss:0.45686	eval-mlogloss:0.43482
[74]	train-mlogloss:0.45182	eval-mlogloss:0.42936
[75]	train-mlogloss:0.44905	eval-mlogloss:0.42694
[76]	train-mlogloss:0.44420	eval-mlogloss:0.42174
[77]	train-mlogloss:0.43947	eval-mlogloss:0.41689
[78]	train-mlogloss:0.43465	eval-mlogloss:0.41165
[79]	train-mlogloss:0.42986	eval-mlogloss:0.40658
[80]	train-mlogloss:0.42574	eval-mlogloss:0.40216
[81]	train-mlogloss:0.42218	eval-mlogloss:0.39882
[82]	train-mlogloss:0.41821	eval-mlogloss:0.39482
[83]	train-mlogloss:0.41394	eval-mlogloss:0.39012
[84]	train-mlogloss:0.40971	eval-mlogloss:0.38571
[85]	train-mlogloss:0.40542	eval-mlogloss:0.38134
[86]	train-mlogloss:0.40137	eval-mlogloss:0.37715
[87]	train-mlogloss:0.39734	eval-mlogloss:0.37297
[88]	train-mlogloss:0.39339	eval-mlogloss:0.36856
[89]	train-mlogloss:0.38952	eval-mlogloss:0.36452
[90]	train-mlogloss:0.38555	eval-mlogloss:0.36026
[91]	train-mlogloss:0.38235	eval-mlogloss:0.35715
[92]	train-mlogloss:0.37912	eval-mlogloss:0.35354
[93]	train-mlogloss:0.37540	eval-mlogloss:0.34959
[94]	train-mlogloss:0.37249	eval-mlogloss:0.34658
[95]	train-mlogloss:0.36878	eval-mlogloss:0.34259
[96]	train-mlogloss:0.36572	eval-mlogloss:0.33953
[97]	train-mlogloss:0.36225	eval-mlogloss:0.33584
[98]	train-mlogloss:0.35976	eval-mlogloss:0.33403
[99]	train-mlogloss:0.35636	eval-mlogloss:0.33043
[100]	train-mlogloss:0.35355	eval-mlogloss:0.32747
[101]	train-mlogloss:0.35025	eval-mlogloss:0.32477
[102]	train-mlogloss:0.34693	eval-mlogloss:0.32103
[103]	train-mlogloss:0.34358	eval-mlogloss:0.31754
[104]	train-mlogloss:0.34079	eval-mlogloss:0.31473
[105]	train-mlogloss:0.33747	eval-mlogloss:0.31116
[106]	train-mlogloss:0.33487	eval-mlogloss:0.30860
[107]	train-mlogloss:0.33253	eval-mlogloss:0.30648
[108]	train-mlogloss:0.32936	eval-mlogloss:0.30288
[109]	train-mlogloss:0.32673	eval-mlogloss:0.30030
[110]	train-mlogloss:0.32366	eval-mlogloss:0.29686
[111]	train-mlogloss:0.32070	eval-mlogloss:0.29356
[112]	train-mlogloss:0.31806	eval-mlogloss:0.29078
[113]	train-mlogloss:0.31530	eval-mlogloss:0.28803
[114]	train-mlogloss:0.31236	eval-mlogloss:0.28491
[115]	train-mlogloss:0.30939	eval-mlogloss:0.28170
[116]	train-mlogloss:0.30652	eval-mlogloss:0.27838
[117]	train-mlogloss:0.30364	eval-mlogloss:0.27554
[118]	train-mlogloss:0.30091	eval-mlogloss:0.27278
[119]	train-mlogloss:0.29820	eval-mlogloss:0.26981
[120]	train-mlogloss:0.29536	eval-mlogloss:0.26673
[121]	train-mlogloss:0.29271	eval-mlogloss:0.26401
[122]	train-mlogloss:0.28997	eval-mlogloss:0.26098
[123]	train-mlogloss:0.28740	eval-mlogloss:0.25845
[124]	train-mlogloss:0.28510	eval-mlogloss:0.25584
[125]	train-mlogloss:0.28263	eval-mlogloss:0.25336
[126]	train-mlogloss:0.28023	eval-mlogloss:0.25059
[127]	train-mlogloss:0.27763	eval-mlogloss:0.24818

[I 2026-10-02 10:09:11,611] Trial 38 pruned. Trial was pruned at iteration 128.

[0]	train-mlogloss:1.05850	eval-mlogloss:1.05996
[1]	train-mlogloss:1.01909	eval-mlogloss:1.01963

[I 2026-10-02 10:09:11,694] Trial 39 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08342	eval-mlogloss:1.08523
[1]	train-mlogloss:1.06510	eval-mlogloss:1.06616
[2]	train-mlogloss:1.04767	eval-mlogloss:1.04789
[3]	train-mlogloss:1.03179	eval-mlogloss:1.03140
[4]	train-mlogloss:1.01529	eval-mlogloss:1.01454
[5]	train-mlogloss:0.99958	eval-mlogloss:0.99804
[6]	train-mlogloss:0.98524	eval-mlogloss:0.98407
[7]	train-mlogloss:0.97339	eval-mlogloss:0.97191

[I 2026-10-02 10:09:11,769] Trial 40 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.04913	eval-mlogloss:1.05215
[1]	train-mlogloss:1.00167	eval-mlogloss:1.00289

[I 2026-10-02 10:09:12,359] Trial 41 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06883	eval-mlogloss:1.06926
[1]	train-mlogloss:1.03901	eval-mlogloss:1.03971
[2]	train-mlogloss:1.02405	eval-mlogloss:1.02522
[3]	train-mlogloss:1.01052	eval-mlogloss:1.01150
[4]	train-mlogloss:0.98198	eval-mlogloss:0.98288
[5]	train-mlogloss:0.95114	eval-mlogloss:0.95142
[6]	train-mlogloss:0.93899	eval-mlogloss:0.94049
[7]	train-mlogloss:0.92445	eval-mlogloss:0.92442

[I 2026-10-02 10:09:12,673] Trial 42 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.08055	eval-mlogloss:1.08226
[1]	train-mlogloss:1.06280	eval-mlogloss:1.06385
[2]	train-mlogloss:1.05356	eval-mlogloss:1.05627
[3]	train-mlogloss:1.04473	eval-mlogloss:1.04842
[4]	train-mlogloss:1.02774	eval-mlogloss:1.03098
[5]	train-mlogloss:1.00949	eval-mlogloss:1.01150
[6]	train-mlogloss:1.00120	eval-mlogloss:1.00445
[7]	train-mlogloss:0.99104	eval-mlogloss:0.99532
[8]	train-mlogloss:0.97486	eval-mlogloss:0.97856
[9]	train-mlogloss:0.95711	eval-mlogloss:0.96021
[10]	train-mlogloss:0.94360	eval-mlogloss:0.94584
[11]	train-mlogloss:0.92949	eval-mlogloss:0.93021
[12]	train-mlogloss:0.91534	eval-mlogloss:0.91607
[13]	train-mlogloss:0.90450	eval-mlogloss:0.90549
[14]	train-mlogloss:0.89074	eval-mlogloss:0.89157
[15]	train-mlogloss:0.87754	eval-mlogloss:0.87736
[16]	train-mlogloss:0.86477	eval-mlogloss:0.86393
[17]	train-mlogloss:0.84815	eval-mlogloss:0.84638
[18]	train-mlogloss:0.83543	eval-mlogloss:0.83328
[19]	train-mlogloss:0.82237	eval-mlogloss:0.82054
[20]	train-mlogloss:0.81519	eval-mlogloss:0.81389
[21]	train-mlogloss:0.80249	eval-mlogloss:0.80063
[22]	train-mlogloss:0.79145	eval-mlogloss:0.78846
[23]	train-mlogloss:0.78582	eval-mlogloss:0.78360
[24]	train-mlogloss:0.77175	eval-mlogloss:0.76836
[25]	train-mlogloss:0.75781	eval-mlogloss:0.75356
[26]	train-mlogloss:0.74904	eval-mlogloss:0.74382
[27]	train-mlogloss:0.74383	eval-mlogloss:0.73868
[28]	train-mlogloss:0.73576	eval-mlogloss:0.73092
[29]	train-mlogloss:0.72543	eval-mlogloss:0.72008
[30]	train-mlogloss:0.71929	eval-mlogloss:0.71483
[31]	train-mlogloss:0.70982	eval-mlogloss:0.70464

[I 2026-10-02 10:09:13,929] Trial 43 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.07629	eval-mlogloss:1.07785
[1]	train-mlogloss:1.05412	eval-mlogloss:1.05507
[2]	train-mlogloss:1.04242	eval-mlogloss:1.04639
[3]	train-mlogloss:1.03112	eval-mlogloss:1.03618
[4]	train-mlogloss:1.01073	eval-mlogloss:1.01553
[5]	train-mlogloss:0.98799	eval-mlogloss:0.99223
[6]	train-mlogloss:0.97782	eval-mlogloss:0.98286
[7]	train-mlogloss:0.96582	eval-mlogloss:0.97122

[I 2026-10-02 10:09:14,131] Trial 44 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.01924	eval-mlogloss:1.02105
[1]	train-mlogloss:0.93394	eval-mlogloss:0.93245

[I 2026-10-02 10:09:14,217] Trial 45 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08566	eval-mlogloss:1.08802
[1]	train-mlogloss:1.07289	eval-mlogloss:1.07525
[2]	train-mlogloss:1.06567	eval-mlogloss:1.07043
[3]	train-mlogloss:1.05842	eval-mlogloss:1.06483
[4]	train-mlogloss:1.04555	eval-mlogloss:1.05217
[5]	train-mlogloss:1.03137	eval-mlogloss:1.03769
[6]	train-mlogloss:1.02472	eval-mlogloss:1.03172
[7]	train-mlogloss:1.01650	eval-mlogloss:1.02424
[8]	train-mlogloss:1.00445	eval-mlogloss:1.01209
[9]	train-mlogloss:0.99130	eval-mlogloss:0.99821
[10]	train-mlogloss:0.98074	eval-mlogloss:0.98690
[11]	train-mlogloss:0.96996	eval-mlogloss:0.97535
[12]	train-mlogloss:0.95894	eval-mlogloss:0.96399
[13]	train-mlogloss:0.95033	eval-mlogloss:0.95652
[14]	train-mlogloss:0.93970	eval-mlogloss:0.94624
[15]	train-mlogloss:0.92898	eval-mlogloss:0.93587
[16]	train-mlogloss:0.91868	eval-mlogloss:0.92507
[17]	train-mlogloss:0.90587	eval-mlogloss:0.91156
[18]	train-mlogloss:0.89529	eval-mlogloss:0.90082
[19]	train-mlogloss:0.88461	eval-mlogloss:0.89046
[20]	train-mlogloss:0.87822	eval-mlogloss:0.88469
[21]	train-mlogloss:0.86767	eval-mlogloss:0.87467
[22]	train-mlogloss:0.85872	eval-mlogloss:0.86505
[23]	train-mlogloss:0.85377	eval-mlogloss:0.86046
[24]	train-mlogloss:0.84241	eval-mlogloss:0.84791
[25]	train-mlogloss:0.83120	eval-mlogloss:0.83613
[26]	train-mlogloss:0.82371	eval-mlogloss:0.82810
[27]	train-mlogloss:0.81875	eval-mlogloss:0.82421
[28]	train-mlogloss:0.81188	eval-mlogloss:0.81757
[29]	train-mlogloss:0.80283	eval-mlogloss:0.80873
[30]	train-mlogloss:0.79745	eval-mlogloss:0.80416
[31]	train-mlogloss:0.78932	eval-mlogloss:0.79568
[32]	train-mlogloss:0.78075	eval-mlogloss:0.78631
[33]	train-mlogloss:0.77685	eval-mlogloss:0.78310
[34]	train-mlogloss:0.76650	eval-mlogloss:0.77244
[35]	train-mlogloss:0.75884	eval-mlogloss:0.76489
[36]	train-mlogloss:0.75043	eval-mlogloss:0.75599
[37]	train-mlogloss:0.74544	eval-mlogloss:0.75218
[38]	train-mlogloss:0.74001	eval-mlogloss:0.74694
[39]	train-mlogloss:0.73506	eval-mlogloss:0.74216
[40]	train-mlogloss:0.72903	eval-mlogloss:0.73639
[41]	train-mlogloss:0.72294	eval-mlogloss:0.73067
[42]	train-mlogloss:0.71591	eval-mlogloss:0.72381
[43]	train-mlogloss:0.71037	eval-mlogloss:0.71803
[44]	train-mlogloss:0.70388	eval-mlogloss:0.71174
[45]	train-mlogloss:0.69520	eval-mlogloss:0.70194
[46]	train-mlogloss:0.69027	eval-mlogloss:0.69725
[47]	train-mlogloss:0.68318	eval-mlogloss:0.68950
[48]	train-mlogloss:0.67805	eval-mlogloss:0.68365
[49]	train-mlogloss:0.67403	eval-mlogloss:0.68007
[50]	train-mlogloss:0.66949	eval-mlogloss:0.67588
[51]	train-mlogloss:0.66318	eval-mlogloss:0.66950
[52]	train-mlogloss:0.65492	eval-mlogloss:0.66092
[53]	train-mlogloss:0.64889	eval-mlogloss:0.65436
[54]	train-mlogloss:0.64093	eval-mlogloss:0.64533
[55]	train-mlogloss:0.63472	eval-mlogloss:0.63842
[56]	train-mlogloss:0.62877	eval-mlogloss:0.63271
[57]	train-mlogloss:0.62564	eval-mlogloss:0.63034
[58]	train-mlogloss:0.62334	eval-mlogloss:0.62884
[59]	train-mlogloss:0.61584	eval-mlogloss:0.62069
[60]	train-mlogloss:0.61093	eval-mlogloss:0.61555
[61]	train-mlogloss:0.60697	eval-mlogloss:0.61180
[62]	train-mlogloss:0.60149	eval-mlogloss:0.60626
[63]	train-mlogloss:0.59799	eval-mlogloss:0.60352
[64]	train-mlogloss:0.59469	eval-mlogloss:0.60039
[65]	train-mlogloss:0.59258	eval-mlogloss:0.59919
[66]	train-mlogloss:0.58558	eval-mlogloss:0.59166
[67]	train-mlogloss:0.58160	eval-mlogloss:0.58822
[68]	train-mlogloss:0.57782	eval-mlogloss:0.58488
[69]	train-mlogloss:0.57186	eval-mlogloss:0.57840
[70]	train-mlogloss:0.56852	eval-mlogloss:0.57579
[71]	train-mlogloss:0.56273	eval-mlogloss:0.56998
[72]	train-mlogloss:0.55695	eval-mlogloss:0.56417
[73]	train-mlogloss:0.55446	eval-mlogloss:0.56242
[74]	train-mlogloss:0.54955	eval-mlogloss:0.55728
[75]	train-mlogloss:0.54697	eval-mlogloss:0.55559
[76]	train-mlogloss:0.54170	eval-mlogloss:0.55035
[77]	train-mlogloss:0.53935	eval-mlogloss:0.54811
[78]	train-mlogloss:0.53470	eval-mlogloss:0.54308
[79]	train-mlogloss:0.52912	eval-mlogloss:0.53679
[80]	train-mlogloss:0.52671	eval-mlogloss:0.53465
[81]	train-mlogloss:0.52241	eval-mlogloss:0.53048
[82]	train-mlogloss:0.52069	eval-mlogloss:0.52965
[83]	train-mlogloss:0.51490	eval-mlogloss:0.52314
[84]	train-mlogloss:0.51278	eval-mlogloss:0.52197
[85]	train-mlogloss:0.50669	eval-mlogloss:0.51509
[86]	train-mlogloss:0.50338	eval-mlogloss:0.51221
[87]	train-mlogloss:0.49916	eval-mlogloss:0.50774
[88]	train-mlogloss:0.49439	eval-mlogloss:0.50276
[89]	train-mlogloss:0.49127	eval-mlogloss:0.49989
[90]	train-mlogloss:0.48644	eval-mlogloss:0.49504
[91]	train-mlogloss:0.48383	eval-mlogloss:0.49302
[92]	train-mlogloss:0.47946	eval-mlogloss:0.48864
[93]	train-mlogloss:0.47557	eval-mlogloss:0.48459
[94]	train-mlogloss:0.47289	eval-mlogloss:0.48201
[95]	train-mlogloss:0.46821	eval-mlogloss:0.47668
[96]	train-mlogloss:0.46530	eval-mlogloss:0.47346
[97]	train-mlogloss:0.46014	eval-mlogloss:0.46783
[98]	train-mlogloss:0.45796	eval-mlogloss:0.46629
[99]	train-mlogloss:0.45394	eval-mlogloss:0.46190
[100]	train-mlogloss:0.45218	eval-mlogloss:0.46076
[101]	train-mlogloss:0.45032	eval-mlogloss:0.45970
[102]	train-mlogloss:0.44567	eval-mlogloss:0.45443
[103]	train-mlogloss:0.44224	eval-mlogloss:0.45100
[104]	train-mlogloss:0.43918	eval-mlogloss:0.44770
[105]	train-mlogloss:0.43426	eval-mlogloss:0.44209
[106]	train-mlogloss:0.43225	eval-mlogloss:0.44028
[107]	train-mlogloss:0.42977	eval-mlogloss:0.43805
[108]	train-mlogloss:0.42631	eval-mlogloss:0.43420
[109]	train-mlogloss:0.42259	eval-mlogloss:0.43041
[110]	train-mlogloss:0.41992	eval-mlogloss:0.42789
[111]	train-mlogloss:0.41716	eval-mlogloss:0.42529
[112]	train-mlogloss:0.41331	eval-mlogloss:0.42122
[113]	train-mlogloss:0.41222	eval-mlogloss:0.42035
[114]	train-mlogloss:0.40872	eval-mlogloss:0.41656
[115]	train-mlogloss:0.40442	eval-mlogloss:0.41194
[116]	train-mlogloss:0.40191	eval-mlogloss:0.40973
[117]	train-mlogloss:0.39848	eval-mlogloss:0.40621
[118]	train-mlogloss:0.39541	eval-mlogloss:0.40366
[119]	train-mlogloss:0.39176	eval-mlogloss:0.39940
[120]	train-mlogloss:0.38777	eval-mlogloss:0.39526
[121]	train-mlogloss:0.38462	eval-mlogloss:0.39211
[122]	train-mlogloss:0.38057	eval-mlogloss:0.38770
[123]	train-mlogloss:0.37807	eval-mlogloss:0.38489
[124]	train-mlogloss:0.37553	eval-mlogloss:0.38223
[125]	train-mlogloss:0.37198	eval-mlogloss:0.37840
[126]	train-mlogloss:0.36989	eval-mlogloss:0.37666
[127]	train-mlogloss:0.36698	eval-mlogloss:0.37345
[128]	train-mlogloss:0.36504	eval-mlogloss:0.37142
[129]	train-mlogloss:0.36311	eval-mlogloss:0.37004
[130]	train-mlogloss:0.36225	eval-mlogloss:0.36971
[131]	train-mlogloss:0.36061	eval-mlogloss:0.36858
[132]	train-mlogloss:0.35764	eval-mlogloss:0.36515
[133]	train-mlogloss:0.35536	eval-mlogloss:0.36255
[134]	train-mlogloss:0.35169	eval-mlogloss:0.35809
[135]	train-mlogloss:0.35052	eval-mlogloss:0.35728
[136]	train-mlogloss:0.34806	eval-mlogloss:0.35500
[137]	train-mlogloss:0.34528	eval-mlogloss:0.35134
[138]	train-mlogloss:0.34274	eval-mlogloss:0.34870
[139]	train-mlogloss:0.33926	eval-mlogloss:0.34469
[140]	train-mlogloss:0.33675	eval-mlogloss:0.34167
[141]	train-mlogloss:0.33440	eval-mlogloss:0.33918
[142]	train-mlogloss:0.33255	eval-mlogloss:0.33743
[143]	train-mlogloss:0.32997	eval-mlogloss:0.33521
[144]	train-mlogloss:0.32793	eval-mlogloss:0.33298
[145]	train-mlogloss:0.32482	eval-mlogloss:0.32937
[146]	train-mlogloss:0.32410	eval-mlogloss:0.32890
[147]	train-mlogloss:0.32170	eval-mlogloss:0.32626
[148]	train-mlogloss:0.31861	eval-mlogloss:0.32244
[149]	train-mlogloss:0.31734	eval-mlogloss:0.32126
[150]	train-mlogloss:0.31511	eval-mlogloss:0.31881
[151]	train-mlogloss:0.31425	eval-mlogloss:0.31794
[152]	train-mlogloss:0.31268	eval-mlogloss:0.31616
[153]	train-mlogloss:0.31043	eval-mlogloss:0.31359
[154]	train-mlogloss:0.30948	eval-mlogloss:0.31297
[155]	train-mlogloss:0.30723	eval-mlogloss:0.31054
[156]	train-mlogloss:0.30468	eval-mlogloss:0.30769
[157]	train-mlogloss:0.30169	eval-mlogloss:0.30416
[158]	train-mlogloss:0.29952	eval-mlogloss:0.30155
[159]	train-mlogloss:0.29691	eval-mlogloss:0.29862
[160]	train-mlogloss:0.29562	eval-mlogloss:0.29750
[161]	train-mlogloss:0.29380	eval-mlogloss:0.29548
[162]	train-mlogloss:0.29106	eval-mlogloss:0.29222
[163]	train-mlogloss:0.28937	eval-mlogloss:0.29020
[164]	train-mlogloss:0.28736	eval-mlogloss:0.28808
[165]	train-mlogloss:0.28592	eval-mlogloss:0.28653
[166]	train-mlogloss:0.28422	eval-mlogloss:0.28474
[167]	train-mlogloss:0.28244	eval-mlogloss:0.28269
[168]	train-mlogloss:0.28199	eval-mlogloss:0.28246
[169]	train-mlogloss:0.27997	eval-mlogloss:0.28023
[170]	train-mlogloss:0.27731	eval-mlogloss:0.27711
[171]	train-mlogloss:0.27525	eval-mlogloss:0.27522
[172]	train-mlogloss:0.27272	eval-mlogloss:0.27254
[173]	train-mlogloss:0.27080	eval-mlogloss:0.27065
[174]	train-mlogloss:0.26900	eval-mlogloss:0.26859
[175]	train-mlogloss:0.26793	eval-mlogloss:0.26766
[176]	train-mlogloss:0.26614	eval-mlogloss:0.26579
[177]	train-mlogloss:0.26428	eval-mlogloss:0.26369
[178]	train-mlogloss:0.26216	eval-mlogloss:0.26095
[179]	train-mlogloss:0.26048	eval-mlogloss:0.25916
[180]	train-mlogloss:0.25878	eval-mlogloss:0.25735
[181]	train-mlogloss:0.25716	eval-mlogloss:0.25556
[182]	train-mlogloss:0.25564	eval-mlogloss:0.25380
[183]	train-mlogloss:0.25418	eval-mlogloss:0.25214
[184]	train-mlogloss:0.25253	eval-mlogloss:0.25064
[185]	train-mlogloss:0.25096	eval-mlogloss:0.24909
[186]	train-mlogloss:0.25031	eval-mlogloss:0.24855
[187]	train-mlogloss:0.24883	eval-mlogloss:0.24699
[188]	train-mlogloss:0.24667	eval-mlogloss:0.24431
[189]	train-mlogloss:0.24561	eval-mlogloss:0.24312
[190]	train-mlogloss:0.24435	eval-mlogloss:0.24180
[191]	train-mlogloss:0.24287	eval-mlogloss:0.24035
[192]	train-mlogloss:0.24074	eval-mlogloss:0.23793
[193]	train-mlogloss:0.23969	eval-mlogloss:0.23681
[194]	train-mlogloss:0.23907	eval-mlogloss:0.23640
[195]	train-mlogloss:0.23778	eval-mlogloss:0.23515
[196]	train-mlogloss:0.23674	eval-mlogloss:0.23449
[197]	train-mlogloss:0.23525	eval-mlogloss:0.23310
[198]	train-mlogloss:0.23358	eval-mlogloss:0.23093
[199]	train-mlogloss:0.23215	eval-mlogloss:0.22950
[200]	train-mlogloss:0.23059	eval-mlogloss:0.22808
[201]	train-mlogloss:0.22998	eval-mlogloss:0.22767
[202]	train-mlogloss:0.22878	eval-mlogloss:0.22632
[203]	train-mlogloss:0.22778	eval-mlogloss:0.22576
[204]	train-mlogloss:0.22650	eval-mlogloss:0.22459
[205]	train-mlogloss:0.22522	eval-mlogloss:0.22330
[206]	train-mlogloss:0.22413	eval-mlogloss:0.22252
[207]	train-mlogloss:0.22265	eval-mlogloss:0.22095
[208]	train-mlogloss:0.22136	eval-mlogloss:0.21975
[209]	train-mlogloss:0.22052	eval-mlogloss:0.21898
[210]	train-mlogloss:0.21931	eval-mlogloss:0.21767
[211]	train-mlogloss:0.21843	eval-mlogloss:0.21725
[212]	train-mlogloss:0.21720	eval-mlogloss:0.21583
[213]	train-mlogloss:0.21558	eval-mlogloss:0.21363
[214]	train-mlogloss:0.21478	eval-mlogloss:0.21286
[215]	train-mlogloss:0.21311	eval-mlogloss:0.21067
[216]	train-mlogloss:0.21194	eval-mlogloss:0.20937
[217]	train-mlogloss:0.21070	eval-mlogloss:0.20780
[218]	train-mlogloss:0.20903	eval-mlogloss:0.20587
[219]	train-mlogloss:0.20732	eval-mlogloss:0.20381
[220]	train-mlogloss:0.20615	eval-mlogloss:0.20227
[221]	train-mlogloss:0.20515	eval-mlogloss:0.20131
[222]	train-mlogloss:0.20363	eval-mlogloss:0.19963
[223]	train-mlogloss:0.20306	eval-mlogloss:0.19918
[224]	train-mlogloss:0.20197	eval-mlogloss:0.19816
[225]	train-mlogloss:0.20120	eval-mlogloss:0.19739
[226]	train-mlogloss:0.20043	eval-mlogloss:0.19672
[227]	train-mlogloss:0.19885	eval-mlogloss:0.19485
[228]	train-mlogloss:0.19758	eval-mlogloss:0.19355
[229]	train-mlogloss:0.19699	eval-mlogloss:0.19288
[230]	train-mlogloss:0.19583	eval-mlogloss:0.19180
[231]	train-mlogloss:0.19504	eval-mlogloss:0.19143
[232]	train-mlogloss:0.19346	eval-mlogloss:0.18951
[233]	train-mlogloss:0.19297	eval-mlogloss:0.18912
[234]	train-mlogloss:0.19236	eval-mlogloss:0.18877
[235]	train-mlogloss:0.19092	eval-mlogloss:0.18703
[236]	train-mlogloss:0.18979	eval-mlogloss:0.18612
[237]	train-mlogloss:0.18902	eval-mlogloss:0.18533
[238]	train-mlogloss:0.18819	eval-mlogloss:0.18439
[239]	train-mlogloss:0.18703	eval-mlogloss:0.18287
[240]	train-mlogloss:0.18623	eval-mlogloss:0.18176
[241]	train-mlogloss:0.18579	eval-mlogloss:0.18151
[242]	train-mlogloss:0.18498	eval-mlogloss:0.18070
[243]	train-mlogloss:0.18423	eval-mlogloss:0.17988
[244]	train-mlogloss:0.18370	eval-mlogloss:0.17974
[245]	train-mlogloss:0.18246	eval-mlogloss:0.17829
[246]	train-mlogloss:0.18135	eval-mlogloss:0.17675
[247]	train-mlogloss:0.18034	eval-mlogloss:0.17548
[248]	train-mlogloss:0.17939	eval-mlogloss:0.17463
[249]	train-mlogloss:0.17851	eval-mlogloss:0.17395
[250]	train-mlogloss:0.17771	eval-mlogloss:0.17295
[251]	train-mlogloss:0.17672	eval-mlogloss:0.17163
[252]	train-mlogloss:0.17539	eval-mlogloss:0.16979
[253]	train-mlogloss:0.17429	eval-mlogloss:0.16809
[254]	train-mlogloss:0.17393	eval-mlogloss:0.16817
[255]	train-mlogloss:0.17304	eval-mlogloss:0.16693
[256]	train-mlogloss:0.17184	eval-mlogloss:0.16536
[257]	train-mlogloss:0.17144	eval-mlogloss:0.16547
[258]	train-mlogloss:0.17062	eval-mlogloss:0.16439
[259]	train-mlogloss:0.16942	eval-mlogloss:0.16274
[260]	train-mlogloss:0.16864	eval-mlogloss:0.16191
[261]	train-mlogloss:0.16786	eval-mlogloss:0.16101
[262]	train-mlogloss:0.16756	eval-mlogloss:0.16093
[263]	train-mlogloss:0.16637	eval-mlogloss:0.15929
[264]	train-mlogloss:0.16521	eval-mlogloss:0.15806
[265]	train-mlogloss:0.16420	eval-mlogloss:0.15675
[266]	train-mlogloss:0.16330	eval-mlogloss:0.15586
[267]	train-mlogloss:0.16266	eval-mlogloss:0.15537
[268]	train-mlogloss:0.16179	eval-mlogloss:0.15405
[269]	train-mlogloss:0.16127	eval-mlogloss:0.15345
[270]	train-mlogloss:0.16072	eval-mlogloss:0.15321
[271]	train-mlogloss:0.15995	eval-mlogloss:0.15209
[272]	train-mlogloss:0.15957	eval-mlogloss:0.15166
[273]	train-mlogloss:0.15899	eval-mlogloss:0.15109
[274]	train-mlogloss:0.15848	eval-mlogloss:0.15081
[275]	train-mlogloss:0.15772	eval-mlogloss:0.15005
[276]	train-mlogloss:0.15671	eval-mlogloss:0.14868
[277]	train-mlogloss:0.15565	eval-mlogloss:0.14718
[278]	train-mlogloss:0.15529	eval-mlogloss:0.14707
[279]	train-mlogloss:0.15452	eval-mlogloss:0.14624
[280]	train-mlogloss:0.15407	eval-mlogloss:0.14582
[281]	train-mlogloss:0.15302	eval-mlogloss:0.14476
[282]	train-mlogloss:0.15248	eval-mlogloss:0.14423
[283]	train-mlogloss:0.15169	eval-mlogloss:0.14355
[284]	train-mlogloss:0.15109	eval-mlogloss:0.14291
[285]	train-mlogloss:0.15011	eval-mlogloss:0.14180
[286]	train-mlogloss:0.14968	eval-mlogloss:0.14160
[287]	train-mlogloss:0.14870	eval-mlogloss:0.14040
[288]	train-mlogloss:0.14799	eval-mlogloss:0.13944
[289]	train-mlogloss:0.14769	eval-mlogloss:0.13974
[290]	train-mlogloss:0.14666	eval-mlogloss:0.13837
[291]	train-mlogloss:0.14633	eval-mlogloss:0.13814
[292]	train-mlogloss:0.14585	eval-mlogloss:0.13771
[293]	train-mlogloss:0.14489	eval-mlogloss:0.13646
[294]	train-mlogloss:0.14414	eval-mlogloss:0.13568
[295]	train-mlogloss:0.14360	eval-mlogloss:0.13494
[296]	train-mlogloss:0.14269	eval-mlogloss:0.13387
[297]	train-mlogloss:0.14181	eval-mlogloss:0.13275
[298]	train-mlogloss:0.14117	eval-mlogloss:0.13206
[299]	train-mlogloss:0.14037	eval-mlogloss:0.13090

[I 2026-10-02 10:09:22,598] Trial 46 finished with value: 1.0 and parameters: {'lambda': 0.02743225473329192, 'alpha': 0.001649738059353, 'eta': 0.01254883757705166, 'gamma': 0.0012543123435334552, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.6163041157967732, 'colsample_bytree': 0.42389260368384896}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.07295	eval-mlogloss:1.07412
[1]	train-mlogloss:1.04765	eval-mlogloss:1.04906

[I 2026-10-02 10:09:22,648] Trial 47 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07994	eval-mlogloss:1.08278
[1]	train-mlogloss:1.06178	eval-mlogloss:1.06442
[2]	train-mlogloss:1.05148	eval-mlogloss:1.05790
[3]	train-mlogloss:1.04137	eval-mlogloss:1.05026
[4]	train-mlogloss:1.02411	eval-mlogloss:1.03284
[5]	train-mlogloss:1.00541	eval-mlogloss:1.01377
[6]	train-mlogloss:0.99608	eval-mlogloss:1.00521
[7]	train-mlogloss:0.98517	eval-mlogloss:0.99522
[8]	train-mlogloss:0.96900	eval-mlogloss:0.97913
[9]	train-mlogloss:0.95139	eval-mlogloss:0.96091
[10]	train-mlogloss:0.93720	eval-mlogloss:0.94635
[11]	train-mlogloss:0.92274	eval-mlogloss:0.93128
[12]	train-mlogloss:0.90861	eval-mlogloss:0.91713
[13]	train-mlogloss:0.89734	eval-mlogloss:0.90734
[14]	train-mlogloss:0.88345	eval-mlogloss:0.89364
[15]	train-mlogloss:0.86984	eval-mlogloss:0.87986
[16]	train-mlogloss:0.85697	eval-mlogloss:0.86648
[17]	train-mlogloss:0.84073	eval-mlogloss:0.84954
[18]	train-mlogloss:0.82761	eval-mlogloss:0.83619
[19]	train-mlogloss:0.81445	eval-mlogloss:0.82351
[20]	train-mlogloss:0.80664	eval-mlogloss:0.81659
[21]	train-mlogloss:0.79349	eval-mlogloss:0.80371
[22]	train-mlogloss:0.78233	eval-mlogloss:0.79178
[23]	train-mlogloss:0.77619	eval-mlogloss:0.78694
[24]	train-mlogloss:0.76210	eval-mlogloss:0.77145
[25]	train-mlogloss:0.74827	eval-mlogloss:0.75664
[26]	train-mlogloss:0.73933	eval-mlogloss:0.74683
[27]	train-mlogloss:0.73339	eval-mlogloss:0.74188
[28]	train-mlogloss:0.72498	eval-mlogloss:0.73392
[29]	train-mlogloss:0.71426	eval-mlogloss:0.72357
[30]	train-mlogloss:0.70782	eval-mlogloss:0.71818
[31]	train-mlogloss:0.69823	eval-mlogloss:0.70810

[I 2026-10-02 10:09:23,449] Trial 48 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.06422	eval-mlogloss:1.06664
[1]	train-mlogloss:1.03086	eval-mlogloss:1.03241

[I 2026-10-02 10:09:24,184] Trial 49 pruned. Trial was pruned at iteration 2.

Best trial: {'lambda': 1.2228682677245145e-06, 'alpha': 0.001356651354882829, 'eta': 0.10290696426865867, 'gamma': 6.497256432362295e-06, 'max_depth': 8, 'min_child_weight': 6, 'subsample': 0.7562278153728188, 'colsample_bytree': 0.4121805001705988}
Best accuracy: 1.0

In [104]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()