In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [19]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [20]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [21]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [22]:
df = df[df['species'] != 'setosa']
df.head()

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor

In [23]:
df['species'] = df['species'].map({'versicolor': 0, 'virginica': 1})
df.head()

    sepal_length  sepal_width  petal_length  petal_width  species
50           7.0          3.2           4.7          1.4        0
51           6.4          3.2           4.5          1.5        0
52           6.9          3.1           4.9          1.5        0
53           5.5          2.3           4.0          1.3        0
54           6.5          2.8           4.6          1.5        0

In [24]:
X = df.drop('species', axis=1)
y = df['species']

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [26]:
X_train

     sepal_length  sepal_width  petal_length  petal_width
65            6.7          3.1           4.4          1.4
90            5.5          2.6           4.4          1.2
146           6.3          2.5           5.0          1.9
59            5.2          2.7           3.9          1.4
122           7.7          2.8           6.7          2.0
..            ...          ...           ...          ...
110           6.5          3.2           5.1          2.0
121           5.6          2.8           4.9          2.0
64            5.6          2.9           3.6          1.3
142           5.8          2.7           5.1          1.9
101           5.8          2.7           5.1          1.9

[75 rows x 4 columns]

In [27]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()

In [28]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'penalty': ['l1', 'l2', 'elasticnet', 'none'],
    'max_iter': [100, 150, 200, 300, 400, 500],
    'C': [1, 2, 3, 4, 6, 8, 10, 20, 30, 40, 50]
    }

In [29]:
logistic_classifier = GridSearchCV(logistic_model, param_grid, cv=5, scoring='accuracy')

In [30]:
logistic_classifier.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 6, 8, 10, 20, 30, 40, 50],
                         'max_iter': [100, 150, 200, 300, 400, 500],
                         'penalty': ['l1', 'l2', 'elasticnet', 'none']},
             scoring='accuracy')

In [31]:
print(logistic_classifier.best_params_)

{'C': 1, 'max_iter': 100, 'penalty': 'l2'}

In [32]:
print(logistic_classifier.best_score_)

0.9733333333333334

In [33]:
logistic_pred = logistic_classifier.predict(X_test)

In [34]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, logistic_pred))
print(confusion_matrix(y_test, logistic_pred))
print(classification_report(y_test, logistic_pred))

0.92
[[13  1]
 [ 1 10]]
              precision    recall  f1-score   support

           0       0.93      0.93      0.93        14
           1       0.91      0.91      0.91        11

    accuracy                           0.92        25
   macro avg       0.92      0.92      0.92        25
weighted avg       0.92      0.92      0.92        25